libstdc++: __gnu_debug::_Safe_iterator< _Iterator, _Sequence > Class Template Reference
__gnu_debug::_Safe_iterator< _Iterator, _Sequence > Class Template Reference
Public Types
typedef _Traits::difference_type difference_type
typedef _Traits::iterator_category iterator_category
typedef _Iterator iterator_type
typedef _Traits::pointer pointer
typedef _Traits::reference reference
typedef _Traits::value_type value_type
Public Member Functions
_Safe_iterator () noexcept
_Safe_iterator (const _Iterator &__i, const _Safe_sequence_base *__seq) noexcept
_Safe_iterator (const _Safe_iterator &__x) noexcept
_Safe_iterator (_Safe_iterator &&__x) noexcept
template<typename _MutableIterator >
_Safe_iterator (const _Safe_iterator< _MutableIterator, typename __gnu_cxx::__enable_if<(std::__are_same< _MutableIterator, typename _Sequence::iterator::iterator_type >::__value), _Sequence >::__type > &__x) noexcept
void _M_attach (_Safe_sequence_base *__seq, bool __constant)
void _M_attach (_Safe_sequence_base *__seq)
void _M_attach_single (_Safe_sequence_base *__seq, bool __constant) throw ()
void _M_attach_single (_Safe_sequence_base *__seq)
bool _M_attached_to (const _Safe_sequence_base *__seq) const
bool _M_before_dereferenceable () const
bool _M_can_advance (const difference_type &__n) const
bool _M_can_compare (const _Safe_iterator_base &__x) const throw ()
bool _M_decrementable () const
bool _M_dereferenceable () const
void _M_detach ()
void _M_detach_single () throw ()
__gnu_cxx::__conditional_type< std::__are_same< _Const_iterator, _Safe_iterator >::__value, const _Sequence *, _Sequence * >::__type _M_get_sequence () const
bool _M_incrementable () const
void _M_invalidate ()
bool _M_is_before_begin () const
bool _M_is_begin () const
bool _M_is_beginnest () const
bool _M_is_end () const
void _M_reset () throw ()
bool _M_singular () const throw ()
void _M_unlink () throw ()
bool _M_valid_range (const _Safe_iterator &__rhs) const
_Iterator & base () noexcept
const _Iterator & base () const noexcept
operator _Iterator () const noexcept
reference operator* () const noexcept
_Safe_iterator operator+ (const difference_type &__n) const noexcept
_Safe_iterator & operator++ () noexcept
_Safe_iterator operator++ (int) noexcept
_Safe_iterator & operator+= (const difference_type &__n) noexcept
_Safe_iterator operator- (const difference_type &__n) const noexcept
_Safe_iterator & operator-- () noexcept
_Safe_iterator operator-- (int) noexcept
_Safe_iterator & operator-= (const difference_type &__n) noexcept
pointer operator-> () const noexcept
_Safe_iterator & operator= (const _Safe_iterator &__x) noexcept
_Safe_iterator & operator= (_Safe_iterator &&__x) noexcept
reference operator[] (const difference_type &__n) const noexcept
Public Attributes
_Safe_iterator_base * _M_next
_Safe_iterator_base * _M_prior
_Safe_sequence_base * _M_sequence
unsigned int _M_version
Protected Member Functions
__gnu_cxx::__mutex & _M_get_mutex () throw ()
Detailed Description
template<typename _Iterator, typename _Sequence>
class __gnu_debug::_Safe_iterator< _Iterator, _Sequence >
Safe iterator wrapper.
The class template _Safe_iterator is a wrapper around an iterator that tracks the iterator's movement among sequences and checks that operations performed on the "safe" iterator are legal. In additional to the basic iterator operations (which are validated, and then passed to the underlying iterator), _Safe_iterator has member functions for iterator invalidation, attaching/detaching the iterator from sequences, and querying the iterator's state.
Note that _Iterator must be the first base class so that it gets initialized before the iterator is being attached to the container's list of iterators and it is being detached before _Iterator get destroyed. Otherwise it would result in a data race.
Definition at line 46 of file formatter.h.
Constructor & Destructor Documentation
template<typename _Iterator, typename _Sequence> __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_Safe_iterator () inline noexcept
Postcondition
the iterator is singular and unattached
Definition at line 152 of file safe_iterator.h.
Referenced by __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator++(), and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator--().
template<typename _Iterator, typename _Sequence> __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_Safe_iterator (const _Iterator & __i, const _Safe_sequence_base * __seq) inline noexcept
Safe iterator construction from an unsafe iterator and its sequence.
Precondition
seq is not NULL
Postcondition
this is not singular
Definition at line 161 of file safe_iterator.h.
References __gnu_debug::_Safe_iterator_base::_M_singular().
template<typename _Iterator, typename _Sequence> __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_Safe_iterator (const _Safe_iterator< _Iterator, _Sequence > & __x) inline noexcept
Copy construction.
Definition at line 173 of file safe_iterator.h.
References __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_attach().
template<typename _Iterator, typename _Sequence> __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_Safe_iterator (_Safe_iterator< _Iterator, _Sequence > && __x) inline noexcept
Move construction.
Postcondition
__x is singular and unattached
Definition at line 191 of file safe_iterator.h.
References __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_attach(), __gnu_debug::_Safe_sequence_base::_M_detach(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::base(), and std::swap().
template<typename _Iterator, typename _Sequence> template<typename _MutableIterator > __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_Safe_iterator (const _Safe_iterator< _MutableIterator, typename __gnu_cxx::__enable_if<(std::__are_same< _MutableIterator, typename _Sequence::iterator::iterator_type >::__value), _Sequence >::__type > & __x) inline noexcept
Converting constructor from a mutable iterator to a constant iterator.
Definition at line 211 of file safe_iterator.h.
References __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_attach().
Member Function Documentation
void __gnu_debug::_Safe_iterator_base::_M_attach (_Safe_sequence_base * __seq, bool __constant) inherited
Attaches this iterator to the given sequence, detaching it from whatever sequence it was attached to originally. If the new sequence is the NULL pointer, the iterator is left unattached.
Referenced by __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_attach(), and __gnu_debug::_Safe_iterator_base::_Safe_iterator_base().
template<typename _Iterator, typename _Sequence> void __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_attach (_Safe_sequence_base * __seq) inline
Attach iterator to the given sequence.
Definition at line 450 of file safe_iterator.h.
References __gnu_debug::_Safe_iterator_base::_M_attach().
Referenced by __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_Safe_iterator(), and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator=().
void __gnu_debug::_Safe_iterator_base::_M_attach_single (_Safe_sequence_base * __seq, bool __constant) throw () inherited
Likewise, but not thread-safe.
Referenced by __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_attach_single().
template<typename _Iterator, typename _Sequence> void __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_attach_single (_Safe_sequence_base * __seq) inline
Likewise, but not thread-safe.
Definition at line 455 of file safe_iterator.h.
References __gnu_debug::_Safe_iterator_base::_M_attach_single().
bool __gnu_debug::_Safe_iterator_base::_M_attached_to (const _Safe_sequence_base * __seq) const inline inherited
Determines if we are attached to the given sequence.
Definition at line 129 of file safe_base.h.
template<typename _Iterator, typename _Sequence> bool __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_before_dereferenceable () const inline
Is the iterator before a dereferenceable one?
Definition at line 465 of file safe_iterator.h.
References __gnu_debug::__base(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_incrementable(), and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::base().
bool __gnu_debug::_Safe_iterator_base::_M_can_compare (const _Safe_iterator_base & __x) const throw () inherited
Can we compare this iterator to the given iterator __x? Returns true if both iterators are nonsingular and reference the same sequence.
template<typename _Iterator, typename _Sequence> bool __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_dereferenceable () const inline
Is the iterator dereferenceable?
Definition at line 460 of file safe_iterator.h.
References __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_is_before_begin(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_is_end(), and __gnu_debug::_Safe_iterator_base::_M_singular().
Referenced by __gnu_debug::__check_dereferenceable(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator*(), and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator->().
void __gnu_debug::_Safe_iterator_base::_M_detach () inherited
Detach the iterator for whatever sequence it is attached to, if any.
Referenced by __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator=().
void __gnu_debug::_Safe_iterator_base::_M_detach_single () throw () inherited
Likewise, but not thread-safe.
__gnu_cxx::__mutex& __gnu_debug::_Safe_iterator_base::_M_get_mutex () throw () protected inherited
For use in _Safe_iterator.
Referenced by __gnu_debug::_Safe_local_iterator< _Iterator, _Sequence >::operator++(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator++(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator--(), __gnu_debug::_Safe_local_iterator< _Iterator, _Sequence >::operator=(), and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator=().
template<typename _Iterator, typename _Sequence> bool __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_incrementable () const inline
Is the iterator incrementable?
Definition at line 477 of file safe_iterator.h.
References __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_is_end(), and __gnu_debug::_Safe_iterator_base::_M_singular().
Referenced by __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_before_dereferenceable(), and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator++().
void __gnu_debug::_Safe_iterator_base::_M_invalidate () inline inherited
Invalidate the iterator, making it singular.
Definition at line 144 of file safe_base.h.
template<typename _Iterator, typename _Sequence> bool __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_is_before_begin () const inline
Is this iterator equal to the sequence's before_begin() iterator if any?
Definition at line 514 of file safe_iterator.h.
Referenced by __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_dereferenceable().
template<typename _Iterator, typename _Sequence> bool __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_is_begin () const inline
Is this iterator equal to the sequence's begin() iterator?
Definition at line 503 of file safe_iterator.h.
References __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::base().
template<typename _Iterator, typename _Sequence> bool __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_is_beginnest () const inline
Is this iterator equal to the sequence's before_begin() iterator if any or begin() otherwise?
Definition at line 520 of file safe_iterator.h.
template<typename _Iterator, typename _Sequence> bool __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_is_end () const inline
Is this iterator equal to the sequence's end() iterator?
Definition at line 508 of file safe_iterator.h.
References __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::base().
Referenced by __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_dereferenceable(), and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_incrementable().
void __gnu_debug::_Safe_iterator_base::_M_reset () throw () inherited
Reset all member variables
bool __gnu_debug::_Safe_iterator_base::_M_singular () const throw () inherited
Is this iterator singular?
Referenced by __gnu_debug::__check_singular_aux(), __gnu_debug::_Safe_local_iterator< _Iterator, _Sequence >::_M_dereferenceable(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_dereferenceable(), __gnu_debug::_Safe_local_iterator< _Iterator, _Sequence >::_M_incrementable(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_incrementable(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_Safe_iterator(), and __gnu_debug::_Safe_local_iterator< _Iterator, _Sequence >::_Safe_local_iterator().
void __gnu_debug::_Safe_iterator_base::_M_unlink () throw () inline inherited
Unlink itself
Definition at line 153 of file safe_base.h.
References __gnu_debug::_Safe_iterator_base::_M_next, and __gnu_debug::_Safe_iterator_base::_M_prior.
template<typename _Iterator, typename _Sequence> _Iterator& __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::base () inline noexcept
Return the underlying iterator.
Definition at line 437 of file safe_iterator.h.
Referenced by __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_before_dereferenceable(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_is_begin(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_is_end(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_Safe_iterator(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator*(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator++(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator--(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator->(), and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator=().
template<typename _Iterator, typename _Sequence> __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator _Iterator () const inline noexcept
Conversion to underlying non-debug iterator to allow better interaction with non-debug containers.
Definition at line 446 of file safe_iterator.h.
template<typename _Iterator, typename _Sequence> reference __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator* () const inline noexcept
Iterator dereference.
Precondition
iterator is dereferenceable
Definition at line 299 of file safe_iterator.h.
References __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_dereferenceable(), and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::base().
template<typename _Iterator, typename _Sequence> _Safe_iterator& __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator++ () inline noexcept
Iterator preincrement.
Precondition
iterator is incrementable
Definition at line 327 of file safe_iterator.h.
References __gnu_debug::_Safe_iterator_base::_M_get_mutex(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_incrementable(), and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::base().
template<typename _Iterator, typename _Sequence> _Safe_iterator __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator++ (int) inline noexcept
Iterator postincrement.
Precondition
iterator is incrementable
Definition at line 342 of file safe_iterator.h.
References __gnu_debug::_Safe_iterator_base::_M_get_mutex(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_incrementable(), __gnu_debug::_Safe_iterator_base::_M_sequence, __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_Safe_iterator(), and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::base().
template<typename _Iterator, typename _Sequence> _Safe_iterator& __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator-- () inline noexcept
Iterator predecrement.
Precondition
iterator is decrementable
Definition at line 357 of file safe_iterator.h.
References __gnu_debug::_Safe_iterator_base::_M_get_mutex(), and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::base().
template<typename _Iterator, typename _Sequence> _Safe_iterator __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator-- (int) inline noexcept
Iterator postdecrement.
Precondition
iterator is decrementable
Definition at line 372 of file safe_iterator.h.
References __gnu_debug::_Safe_iterator_base::_M_get_mutex(), __gnu_debug::_Safe_iterator_base::_M_sequence, __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_Safe_iterator(), and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::base().
template<typename _Iterator, typename _Sequence> pointer __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator-> () const inline noexcept
Iterator dereference.
Precondition
iterator is dereferenceable
Todo:
Make this correct w.r.t. iterators that return proxies
Definition at line 313 of file safe_iterator.h.
References std::__addressof(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_dereferenceable(), and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::base().
template<typename _Iterator, typename _Sequence> _Safe_iterator& __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator= (const _Safe_iterator< _Iterator, _Sequence > & __x) inline noexcept
Copy assignment.
Definition at line 232 of file safe_iterator.h.
References __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_attach(), __gnu_debug::_Safe_iterator_base::_M_detach(), __gnu_debug::_Safe_iterator_base::_M_get_mutex(), __gnu_debug::_Safe_iterator_base::_M_sequence, __gnu_debug::_Safe_iterator_base::_M_version, and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::base().
template<typename _Iterator, typename _Sequence> _Safe_iterator& __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator= (_Safe_iterator< _Iterator, _Sequence > && __x) inline noexcept
Move assignment.
Postcondition
__x is singular and unattached
Definition at line 264 of file safe_iterator.h.
References __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_attach(), __gnu_debug::_Safe_iterator_base::_M_detach(), __gnu_debug::_Safe_iterator_base::_M_get_mutex(), __gnu_debug::_Safe_iterator_base::_M_sequence, __gnu_debug::_Safe_iterator_base::_M_version, and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::base().
Member Data Documentation
_Safe_iterator_base* __gnu_debug::_Safe_iterator_base::_M_next inherited
Pointer to the next iterator in the sequence's list of iterators. Only valid when _M_sequence != NULL.
Definition at line 72 of file safe_base.h.
Referenced by __gnu_debug::_Safe_iterator_base::_M_unlink().
_Safe_iterator_base* __gnu_debug::_Safe_iterator_base::_M_prior inherited
Pointer to the previous iterator in the sequence's list of iterators. Only valid when _M_sequence != NULL.
Definition at line 68 of file safe_base.h.
Referenced by __gnu_debug::_Safe_iterator_base::_M_unlink().
_Safe_sequence_base* __gnu_debug::_Safe_iterator_base::_M_sequence inherited
The sequence this iterator references; may be NULL to indicate a singular iterator.
Definition at line 55 of file safe_base.h.
Referenced by __gnu_debug::_Safe_iterator_base::_Safe_iterator_base(), __gnu_debug::_Safe_local_iterator_base::_Safe_local_iterator_base(), __gnu_debug::_Safe_local_iterator< _Iterator, _Sequence >::operator++(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator++(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator--(), __gnu_debug::_Safe_local_iterator< _Iterator, _Sequence >::operator=(), and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator=().
unsigned int __gnu_debug::_Safe_iterator_base::_M_version inherited
The version number of this iterator. The sentinel value 0 is used to indicate an invalidated iterator (i.e., one that is singular because of an operation on the container). This version number must equal the version number in the sequence referenced by _M_sequence for the iterator to be non-singular.
Definition at line 64 of file safe_base.h.
Referenced by __gnu_debug::_Safe_local_iterator< _Iterator, _Sequence >::operator=(), and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator=().
The documentation for this class was generated from the following files:
formatter.h
safe_iterator.h