libstdc++: std Namespace Reference
std Namespace Reference
Namespaces
__debug
__detail
__parallel
__profile
regex_constants
rel_ops
tr1
tr2
Classes
struct __allocated_ptr
struct __atomic_base
struct __atomic_base< _PTp * >
struct __atomic_flag_base
class __codecvt_abstract_base
class __ctype_abstract_base
struct __iterator_traits
class _Deque_base
struct _Deque_iterator
struct _Enable_copy_move
struct _Enable_default_constructor
struct _Enable_destructor
struct _Enable_special_members
struct _Fwd_list_base
struct _Fwd_list_const_iterator
struct _Fwd_list_iterator
struct _Fwd_list_node
struct _Fwd_list_node_base
class _Hashtable
class _List_base
struct _List_const_iterator
struct _List_iterator
struct _List_node
struct _Sp_ebo_helper< _Nm, _Tp, false >
struct _Sp_ebo_helper< _Nm, _Tp, true >
class _Temporary_buffer
struct _Vector_base
class allocator
class allocator< void >
struct allocator_arg_t
struct allocator_traits
struct atomic_flag
class auto_ptr
struct auto_ptr_ref
class back_insert_iterator
class bad_weak_ptr
class basic_ios
class basic_regex
class basic_string
class bernoulli_distribution
struct bidirectional_iterator_tag
struct binary_function
class binary_negate
class binder1st
class binder2nd
class binomial_distribution
class cauchy_distribution
struct char_traits
struct char_traits< __gnu_cxx::character< _Value, _Int, _St > >
struct char_traits< char >
struct char_traits< wchar_t >
class chi_squared_distribution
class codecvt
class codecvt< _InternT, _ExternT, encoding_state >
class codecvt< char, char, mbstate_t >
class codecvt< char16_t, char, mbstate_t >
class codecvt< char32_t, char, mbstate_t >
class codecvt< wchar_t, char, mbstate_t >
class codecvt_base
class codecvt_byname
class collate
class collate_byname
class const_mem_fun1_ref_t
class const_mem_fun1_t
class const_mem_fun_ref_t
class const_mem_fun_t
class ctype
class ctype< char >
class ctype< wchar_t >
struct ctype_base
class ctype_byname
class ctype_byname< char >
struct default_delete
struct default_delete< _Tp[]>
class deque
class discard_block_engine
class discrete_distribution
struct divides
class enable_shared_from_this
struct equal_to
class exponential_distribution
class extreme_value_distribution
class fisher_f_distribution
struct forward_iterator_tag
class forward_list
class fpos
class front_insert_iterator
class gamma_distribution
class geometric_distribution
struct greater
struct greater_equal
class gslice
class gslice_array
struct hash
struct hash< __gnu_cxx::__u16vstring >
struct hash< __gnu_cxx::__u32vstring >
struct hash< __gnu_cxx::__vstring >
struct hash< __gnu_cxx::__wvstring >
struct hash< __gnu_cxx::throw_value_limit >
struct hash< __gnu_cxx::throw_value_random >
struct hash< __shared_ptr< _Tp, _Lp > >
struct hash< _Tp * >
struct hash< bool >
struct hash< char >
struct hash< char16_t >
struct hash< char32_t >
struct hash< double >
struct hash< float >
struct hash< int >
struct hash< long >
struct hash< long double >
struct hash< long long >
struct hash< shared_ptr< _Tp > >
struct hash< short >
struct hash< signed char >
struct hash< string >
struct hash< u16string >
struct hash< u32string >
struct hash< unique_ptr< _Tp, _Dp > >
struct hash< unsigned char >
struct hash< unsigned int >
struct hash< unsigned long >
struct hash< unsigned long long >
struct hash< unsigned short >
struct hash< wchar_t >
struct hash< wstring >
struct hash<::vector< bool, _Alloc > >
class independent_bits_engine
class indirect_array
struct input_iterator_tag
class insert_iterator
class ios_base
class istream_iterator
class istreambuf_iterator
struct iterator
struct iterator_traits< _Tp * >
struct iterator_traits< const _Tp * >
struct less
struct less_equal
class linear_congruential_engine
class list
class locale
struct logical_and
struct logical_not
struct logical_or
class lognormal_distribution
class map
class mask_array
class match_results
class mem_fun1_ref_t
class mem_fun1_t
class mem_fun_ref_t
class mem_fun_t
class mersenne_twister_engine
class messages
struct messages_base
class messages_byname
struct minus
struct modulus
class money_base
class money_get
class money_put
class moneypunct
class moneypunct_byname
class move_iterator
class multimap
struct multiplies
class multiset
struct negate
class negative_binomial_distribution
class nested_exception
class normal_distribution
struct not_equal_to
class num_get
class num_put
class numpunct
class numpunct_byname
class ostream_iterator
class ostreambuf_iterator
struct output_iterator_tag
struct owner_less
struct owner_less< shared_ptr< _Tp > >
struct owner_less< weak_ptr< _Tp > >
struct pair
class piecewise_constant_distribution
struct piecewise_construct_t
class piecewise_linear_distribution
struct plus
class pointer_to_binary_function
class pointer_to_unary_function
struct pointer_traits
struct pointer_traits< _Tp * >
class poisson_distribution
class priority_queue
class queue
struct random_access_iterator_tag
class random_device
class raw_storage_iterator
class regex_error
class regex_iterator
class regex_token_iterator
struct regex_traits
class reverse_iterator
class seed_seq
class set
class shared_ptr
class shuffle_order_engine
class slice
class slice_array
class stack
class student_t_distribution
class sub_match
class subtract_with_carry_engine
class time_base
class time_get
class time_get_byname
class time_put
class time_put_byname
struct unary_function
class unary_negate
class uniform_int_distribution
class uniform_real_distribution
class unique_ptr
class unique_ptr< _Tp[], _Dp >
class unordered_map
class unordered_multimap
class unordered_multiset
class unordered_set
struct uses_allocator
class vector
class vector< bool, _Alloc >
class wbuffer_convert
class weak_ptr
class weibull_distribution
class wstring_convert
Typedefs
template<typename _Alloc , typename _Tp >
using __alloc_rebind = typename __alloctr_rebind< _Alloc, _Tp >::__type
template<typename _Tp >
using __allocator_base = __gnu_cxx::new_allocator< _Tp >
typedef unsigned char __atomic_flag_data_type
typedef FILE __c_file
typedef __locale_t __c_locale
typedef __gthread_mutex_t __c_lock
template<typename _Tp , typename _Hash >
using __cache_default = __not_< __and_< __is_fast_hash< _Hash >, __detail::__is_noexcept_hash< _Tp, _Hash >>>
template<typename _Bi_iter , typename _Ch_traits , typename _Ch_alloc >
using __sub_match_string = basic_string< typename iterator_traits< _Bi_iter >::value_type, _Ch_traits, _Ch_alloc >
template<typename _Key , typename _Tp , typename _Hash = hash<_Key>, typename _Pred = std::equal_to<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >, typename _Tr = __umap_traits<__cache_default<_Key, _Hash>::value>>
using __umap_hashtable = _Hashtable< _Key, std::pair< const _Key, _Tp >, _Alloc, __detail::_Select1st, _Pred, _Hash, __detail::_Mod_range_hashing, __detail::_Default_ranged_hash, __detail::_Prime_rehash_policy, _Tr >
template<bool _Cache>
using __umap_traits = __detail::_Hashtable_traits< _Cache, false, true >
template<typename _Key , typename _Tp , typename _Hash = hash<_Key>, typename _Pred = std::equal_to<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >, typename _Tr = __ummap_traits<__cache_default<_Key, _Hash>::value>>
using __ummap_hashtable = _Hashtable< _Key, std::pair< const _Key, _Tp >, _Alloc, __detail::_Select1st, _Pred, _Hash, __detail::_Mod_range_hashing, __detail::_Default_ranged_hash, __detail::_Prime_rehash_policy, _Tr >
template<bool _Cache>
using __ummap_traits = __detail::_Hashtable_traits< _Cache, false, false >
template<typename _Value , typename _Hash = hash<_Value>, typename _Pred = std::equal_to<_Value>, typename _Alloc = std::allocator<_Value>, typename _Tr = __umset_traits<__cache_default<_Value, _Hash>::value>>
using __umset_hashtable = _Hashtable< _Value, _Value, _Alloc, __detail::_Identity, _Pred, _Hash, __detail::_Mod_range_hashing, __detail::_Default_ranged_hash, __detail::_Prime_rehash_policy, _Tr >
template<bool _Cache>
using __umset_traits = __detail::_Hashtable_traits< _Cache, true, false >
template<typename _Tp , typename _Alloc , typename... _Args>
using __uses_alloc_t = __uses_alloc< uses_allocator< _Tp, _Alloc >::value, _Tp, _Alloc, _Args...>
template<typename _Value , typename _Hash = hash<_Value>, typename _Pred = std::equal_to<_Value>, typename _Alloc = std::allocator<_Value>, typename _Tr = __uset_traits<__cache_default<_Value, _Hash>::value>>
using __uset_hashtable = _Hashtable< _Value, _Value, _Alloc, __detail::_Identity, _Pred, _Hash, __detail::_Mod_range_hashing, __detail::_Default_ranged_hash, __detail::_Prime_rehash_policy, _Tr >
template<bool _Cache>
using __uset_traits = __detail::_Hashtable_traits< _Cache, true, true >
typedef unsigned long _Bit_type
template<typename _InIter >
using _RequireInputIter = typename enable_if< is_convertible< typename iterator_traits< _InIter >::iterator_category, input_iterator_tag >::value >::type
typedef match_results< const char * > cmatch
typedef regex_iterator< const char * > cregex_iterator
typedef regex_token_iterator< const char * > cregex_token_iterator
typedef sub_match< const char * > csub_match
typedef minstd_rand0 default_random_engine
typedef shuffle_order_engine< minstd_rand0, 256 > knuth_b
typedef enum std::memory_order memory_order
typedef linear_congruential_engine< uint_fast32_t, 48271UL, 0UL, 2147483647UL > minstd_rand
typedef linear_congruential_engine< uint_fast32_t, 16807UL, 0UL, 2147483647UL > minstd_rand0
typedef mersenne_twister_engine< uint_fast32_t, 32, 624, 397, 31, 0x9908b0dfUL, 11, 0xffffffffUL, 7, 0x9d2c5680UL, 15, 0xefc60000UL, 18, 1812433253UL > mt19937
typedef mersenne_twister_engine< uint_fast64_t, 64, 312, 156, 31, 0xb5026f5aa96619e9ULL, 29, 0x5555555555555555ULL, 17, 0x71d67fffeda60000ULL, 37, 0xfff7eee000000000ULL, 43, 6364136223846793005ULL > mt19937_64
typedef __PTRDIFF_TYPE__ ptrdiff_t
typedef discard_block_engine< ranlux24_base, 223, 23 > ranlux24
typedef subtract_with_carry_engine< uint_fast32_t, 24, 10, 24 > ranlux24_base
typedef discard_block_engine< ranlux48_base, 389, 11 > ranlux48
typedef subtract_with_carry_engine< uint_fast64_t, 48, 5, 12 > ranlux48_base
typedef basic_regex< char > regex
typedef __SIZE_TYPE__ size_t
typedef match_results< string::const_iterator > smatch
typedef regex_iterator< string::const_iterator > sregex_iterator
typedef regex_token_iterator< string::const_iterator > sregex_token_iterator
typedef sub_match< string::const_iterator > ssub_match
typedef long long streamoff
typedef fpos< mbstate_t > streampos
typedef ptrdiff_t streamsize
typedef basic_string< char > string
typedef fpos< mbstate_t > u16streampos
typedef basic_string< char16_t > u16string
typedef fpos< mbstate_t > u32streampos
typedef basic_string< char32_t > u32string
typedef match_results< const wchar_t * > wcmatch
typedef regex_iterator< const wchar_t * > wcregex_iterator
typedef regex_token_iterator< const wchar_t * > wcregex_token_iterator
typedef sub_match< const wchar_t * > wcsub_match
typedef basic_regex< wchar_t > wregex
typedef match_results< wstring::const_iterator > wsmatch
typedef regex_iterator< wstring::const_iterator > wsregex_iterator
typedef regex_token_iterator< wstring::const_iterator > wsregex_token_iterator
typedef sub_match< wstring::const_iterator > wssub_match
typedef fpos< mbstate_t > wstreampos
typedef basic_string< wchar_t > wstring
Enumerations
enum { _S_threshold }
enum { _S_chunk_size }
enum { _S_word_bit }
enum __memory_order_modifier { __memory_order_mask, __memory_order_modifier_mask, __memory_order_hle_acquire, __memory_order_hle_release }
enum _Ios_Fmtflags {
_S_boolalpha, _S_dec, _S_fixed, _S_hex,
_S_internal, _S_left, _S_oct, _S_right,
_S_scientific, _S_showbase, _S_showpoint, _S_showpos,
_S_skipws, _S_unitbuf, _S_uppercase, _S_adjustfield,
_S_basefield, _S_floatfield, _S_ios_fmtflags_end, _S_ios_fmtflags_max,
_S_ios_fmtflags_min
}
enum _Ios_Iostate {
_S_goodbit, _S_badbit, _S_eofbit, _S_failbit,
_S_ios_iostate_end, _S_ios_iostate_max, _S_ios_iostate_min
}
enum _Ios_Openmode {
_S_app, _S_ate, _S_bin, _S_in,
_S_out, _S_trunc, _S_ios_openmode_end, _S_ios_openmode_max,
_S_ios_openmode_min
}
enum _Ios_Seekdir { _S_beg, _S_cur, _S_end, _S_ios_seekdir_end }
enum _Rb_tree_color { _S_red, _S_black }
enum errc {
address_family_not_supported, address_in_use, address_not_available, already_connected,
argument_list_too_long, argument_out_of_domain, bad_address, bad_file_descriptor,
broken_pipe, connection_aborted, connection_already_in_progress, connection_refused,
connection_reset, cross_device_link, destination_address_required, device_or_resource_busy,
directory_not_empty, executable_format_error, file_exists, file_too_large,
filename_too_long, function_not_supported, host_unreachable, illegal_byte_sequence,
inappropriate_io_control_operation, interrupted, invalid_argument, invalid_seek,
io_error, is_a_directory, message_size, network_down,
network_reset, network_unreachable, no_buffer_space, no_child_process,
no_lock_available, no_message, no_protocol_option, no_space_on_device,
no_such_device_or_address, no_such_device, no_such_file_or_directory, no_such_process,
not_a_directory, not_a_socket, not_connected, not_enough_memory,
operation_in_progress, operation_not_permitted, operation_not_supported, operation_would_block,
permission_denied, protocol_not_supported, read_only_file_system, resource_deadlock_would_occur,
resource_unavailable_try_again, result_out_of_range, timed_out, too_many_files_open_in_system,
too_many_files_open, too_many_links, too_many_symbolic_link_levels, wrong_protocol_type
}
enum io_errc { stream }
enum memory_order {
memory_order_relaxed, memory_order_consume, memory_order_acquire, memory_order_release,
memory_order_acq_rel, memory_order_seq_cst
}
Functions
template<typename _CharT >
_CharT * __add_grouping (_CharT *__s, _CharT __sep, const char *__gbeg, size_t __gsize, const _CharT *__first, const _CharT *__last)
template<typename _Tp >
_Tp * __addressof (_Tp &__r) noexcept
template<typename _ForwardIterator , typename _BinaryPredicate >
_ForwardIterator __adjacent_find (_ForwardIterator __first, _ForwardIterator __last, _BinaryPredicate __binary_pred)
template<typename _RandomAccessIterator , typename _Distance , typename _Tp , typename _Compare >
void __adjust_heap (_RandomAccessIterator __first, _Distance __holeIndex, _Distance __len, _Tp __value, _Compare __comp)
template<typename _InputIterator , typename _Distance >
void __advance (_InputIterator &__i, _Distance __n, input_iterator_tag)
template<typename _BidirectionalIterator , typename _Distance >
void __advance (_BidirectionalIterator &__i, _Distance __n, bidirectional_iterator_tag)
template<typename _RandomAccessIterator , typename _Distance >
void __advance (_RandomAccessIterator &__i, _Distance __n, random_access_iterator_tag)
template<typename _Alloc >
void __alloc_on_copy (_Alloc &__one, const _Alloc &__two)
template<typename _Alloc >
_Alloc __alloc_on_copy (const _Alloc &__a)
template<typename _Alloc >
void __alloc_on_move (_Alloc &__one, _Alloc &__two)
template<typename _Alloc >
void __alloc_on_swap (_Alloc &__one, _Alloc &__two)
template<typename _Alloc >
__allocated_ptr< _Alloc > __allocate_guarded (_Alloc &__a)
template<typename _Tp , _Lock_policy _Lp, typename _Alloc , typename... _Args>
__shared_ptr< _Tp, _Lp > __allocate_shared (const _Alloc &__a, _Args &&...__args)
__attribute__ ((__always_inline__)) void atomic_thread_fence(memory_order __m) noexcept
namespace __cxx11 __attribute__ ((__abi_tag__("cxx11")))
template<typename _Facet >
const _Facet & __check_facet (const _Facet *__f)
template<typename _RandomAccessIterator , typename _Distance , typename _Compare >
void __chunk_insertion_sort (_RandomAccessIterator __first, _RandomAccessIterator __last, _Distance __chunk_size, _Compare __comp)
constexpr memory_order __cmpexch_failure_order (memory_order __m) noexcept
constexpr memory_order __cmpexch_failure_order2 (memory_order __m) noexcept
int __convert_from_v (const __c_locale &__cloc __attribute__((__unused__)), char *__out, const int __size __attribute__((__unused__)), const char *__fmt,...)
template<typename _Tp >
void __convert_to_v (const char *, _Tp &, ios_base::iostate &, const __c_locale &) throw ()
template<>
void __convert_to_v (const char *, float &, ios_base::iostate &, const __c_locale &) throw ()
template<>
void __convert_to_v (const char *, double &, ios_base::iostate &, const __c_locale &) throw ()
template<>
void __convert_to_v (const char *, long double &, ios_base::iostate &, const __c_locale &) throw ()
template<bool _IsMove, typename _II , typename _OI >
_OI __copy_move_a (_II __first, _II __last, _OI __result)
template<bool _IsMove, typename _CharT >
__gnu_cxx::__enable_if< __is_char< _CharT >::__value, ostreambuf_iterator< _CharT > >::__type __copy_move_a2 (_CharT *__first, _CharT *__last, ostreambuf_iterator< _CharT > __result)
template<bool _IsMove, typename _CharT >
__gnu_cxx::__enable_if< __is_char< _CharT >::__value, ostreambuf_iterator< _CharT > >::__type __copy_move_a2 (const _CharT *__first, const _CharT *__last, ostreambuf_iterator< _CharT > __result)
template<bool _IsMove, typename _CharT >
__gnu_cxx::__enable_if< __is_char< _CharT >::__value, _CharT * >::__type __copy_move_a2 (istreambuf_iterator< _CharT > __first, istreambuf_iterator< _CharT > __last, _CharT *__result)
template<bool _IsMove, typename _CharT >
__gnu_cxx::__enable_if< __is_char< _CharT >::__value, ostreambuf_iterator< _CharT, char_traits< _CharT > > >::__type __copy_move_a2 (_CharT *, _CharT *, ostreambuf_iterator< _CharT, char_traits< _CharT > >)
template<bool _IsMove, typename _CharT >
__gnu_cxx::__enable_if< __is_char< _CharT >::__value, ostreambuf_iterator< _CharT, char_traits< _CharT > > >::__type __copy_move_a2 (const _CharT *, const _CharT *, ostreambuf_iterator< _CharT, char_traits< _CharT > >)
template<bool _IsMove, typename _CharT >
__gnu_cxx::__enable_if< __is_char< _CharT >::__value, _CharT * >::__type __copy_move_a2 (istreambuf_iterator< _CharT, char_traits< _CharT > >, istreambuf_iterator< _CharT, char_traits< _CharT > >, _CharT *)
template<bool _IsMove, typename _II , typename _OI >
_OI __copy_move_a2 (_II __first, _II __last, _OI __result)
template<bool _IsMove, typename _BI1 , typename _BI2 >
_BI2 __copy_move_backward_a (_BI1 __first, _BI1 __last, _BI2 __result)
template<bool _IsMove, typename _BI1 , typename _BI2 >
_BI2 __copy_move_backward_a2 (_BI1 __first, _BI1 __last, _BI2 __result)
template<typename _InputIterator , typename _Size , typename _OutputIterator >
_OutputIterator __copy_n (_InputIterator __first, _Size __n, _OutputIterator __result, input_iterator_tag)
template<typename _RandomAccessIterator , typename _Size , typename _OutputIterator >
_OutputIterator __copy_n (_RandomAccessIterator __first, _Size __n, _OutputIterator __result, random_access_iterator_tag)
template<typename _InputIterator , typename _Predicate >
iterator_traits< _InputIterator >::difference_type __count_if (_InputIterator __first, _InputIterator __last, _Predicate __pred)
constexpr size_t __deque_buf_size (size_t __size)
template<typename _InputIterator >
iterator_traits< _InputIterator >::difference_type __distance (_InputIterator __first, _InputIterator __last, input_iterator_tag)
template<typename _RandomAccessIterator >
iterator_traits< _RandomAccessIterator >::difference_type __distance (_RandomAccessIterator __first, _RandomAccessIterator __last, random_access_iterator_tag)
template<typename _Alloc >
void __do_alloc_on_copy (_Alloc &__one, const _Alloc &__two, true_type)
template<typename _Alloc >
void __do_alloc_on_copy (_Alloc &, const _Alloc &, false_type)
template<typename _Alloc >
void __do_alloc_on_move (_Alloc &__one, _Alloc &__two, true_type)
template<typename _Alloc >
void __do_alloc_on_move (_Alloc &, _Alloc &, false_type)
template<typename _Alloc >
void __do_alloc_on_swap (_Alloc &__one, _Alloc &__two, true_type)
template<typename _Alloc >
void __do_alloc_on_swap (_Alloc &, _Alloc &, false_type)
template<typename _OutStr , typename _InChar , typename _Codecvt , typename _State , typename _Fn >
bool __do_str_codecvt (const _InChar *__first, const _InChar *__last, _OutStr &__outstr, const _Codecvt &__cvt, _State &__state, size_t &__count, _Fn __fn)
template<_Lock_policy _Lp, typename _Tp1 , typename _Tp2 >
void __enable_shared_from_this_helper (const __shared_count< _Lp > &, const __enable_shared_from_this< _Tp1, _Lp > *, const _Tp2 *) noexcept
template<typename _Tp1 , typename _Tp2 >
void __enable_shared_from_this_helper (const __shared_count<> &, const enable_shared_from_this< _Tp1 > *, const _Tp2 *) noexcept
template<_Lock_policy _Lp>
void __enable_shared_from_this_helper (const __shared_count< _Lp > &,...) noexcept
template<typename _II1 , typename _II2 >
bool __equal_aux (_II1 __first1, _II1 __last1, _II2 __first2)
template<typename _ForwardIterator , typename _Tp , typename _CompareItTp , typename _CompareTpIt >
pair< _ForwardIterator, _ForwardIterator > __equal_range (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__val, _CompareItTp __comp_it_val, _CompareTpIt __comp_val_it)
template<typename _Tp , typename _Up = _Tp>
_Tp __exchange (_Tp &__obj, _Up &&__new_val)
template<typename _ForwardIterator , typename _Tp >
__gnu_cxx::__enable_if<!__is_scalar< _Tp >::__value, void >::__type __fill_a (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__value)
template<typename _ForwardIterator , typename _Tp >
__gnu_cxx::__enable_if< __is_scalar< _Tp >::__value, void >::__type __fill_a (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__value)
template<typename _Tp >
__gnu_cxx::__enable_if< __is_byte< _Tp >::__value, void >::__type __fill_a (_Tp *__first, _Tp *__last, const _Tp &__c)
void __fill_bvector (_Bit_iterator __first, _Bit_iterator __last, bool __x)
template<typename _OutputIterator , typename _Size , typename _Tp >
__gnu_cxx::__enable_if<!__is_scalar< _Tp >::__value, _OutputIterator >::__type __fill_n_a (_OutputIterator __first, _Size __n, const _Tp &__value)
template<typename _OutputIterator , typename _Size , typename _Tp >
__gnu_cxx::__enable_if< __is_scalar< _Tp >::__value, _OutputIterator >::__type __fill_n_a (_OutputIterator __first, _Size __n, const _Tp &__value)
template<typename _Size , typename _Tp >
__gnu_cxx::__enable_if< __is_byte< _Tp >::__value, _Tp * >::__type __fill_n_a (_Tp *__first, _Size __n, const _Tp &__c)
template<typename _RandomAccessIterator , typename _Compare >
void __final_insertion_sort (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _ForwardIterator1 , typename _ForwardIterator2 , typename _BinaryPredicate >
_ForwardIterator1 __find_end (_ForwardIterator1 __first1, _ForwardIterator1 __last1, _ForwardIterator2 __first2, _ForwardIterator2 __last2, forward_iterator_tag, forward_iterator_tag, _BinaryPredicate __comp)
template<typename _BidirectionalIterator1 , typename _BidirectionalIterator2 , typename _BinaryPredicate >
_BidirectionalIterator1 __find_end (_BidirectionalIterator1 __first1, _BidirectionalIterator1 __last1, _BidirectionalIterator2 __first2, _BidirectionalIterator2 __last2, bidirectional_iterator_tag, bidirectional_iterator_tag, _BinaryPredicate __comp)
template<typename _InputIterator , typename _Predicate >
_InputIterator __find_if (_InputIterator __first, _InputIterator __last, _Predicate __pred, input_iterator_tag)
template<typename _RandomAccessIterator , typename _Predicate >
_RandomAccessIterator __find_if (_RandomAccessIterator __first, _RandomAccessIterator __last, _Predicate __pred, random_access_iterator_tag)
template<typename _Iterator , typename _Predicate >
_Iterator __find_if (_Iterator __first, _Iterator __last, _Predicate __pred)
template<typename _InputIterator , typename _Predicate >
_InputIterator __find_if_not (_InputIterator __first, _InputIterator __last, _Predicate __pred)
template<typename _InputIterator , typename _Predicate , typename _Distance >
_InputIterator __find_if_not_n (_InputIterator __first, _Distance &__len, _Predicate __pred)
template<typename _EuclideanRingElement >
_EuclideanRingElement __gcd (_EuclideanRingElement __m, _EuclideanRingElement __n)
template<typename _RandomAccessIterator , typename _Compare >
void __heap_select (_RandomAccessIterator __first, _RandomAccessIterator __middle, _RandomAccessIterator __last, _Compare __comp)
template<typename _Tp >
size_t __iconv_adaptor (size_t(*__func)(iconv_t, _Tp, size_t *, char **, size_t *), iconv_t __cd, char **__inbuf, size_t *__inbytes, char **__outbuf, size_t *__outbytes)
template<typename _InputIterator1 , typename _InputIterator2 , typename _Compare >
bool __includes (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _Compare __comp)
template<typename _BidirectionalIterator , typename _Compare >
void __inplace_merge (_BidirectionalIterator __first, _BidirectionalIterator __middle, _BidirectionalIterator __last, _Compare __comp)
template<typename _RandomAccessIterator , typename _Compare >
void __inplace_stable_sort (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _RandomAccessIterator , typename _Compare >
void __insertion_sort (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _RandomAccessIterator , typename _Size , typename _Compare >
void __introselect (_RandomAccessIterator __first, _RandomAccessIterator __nth, _RandomAccessIterator __last, _Size __depth_limit, _Compare __comp)
template<typename _RandomAccessIterator , typename _Size , typename _Compare >
void __introsort_loop (_RandomAccessIterator __first, _RandomAccessIterator __last, _Size __depth_limit, _Compare __comp)
template<typename _RandomAccessIterator , typename _Distance >
bool __is_heap (_RandomAccessIterator __first, _Distance __n)
template<typename _RandomAccessIterator , typename _Compare , typename _Distance >
bool __is_heap (_RandomAccessIterator __first, _Compare __comp, _Distance __n)
template<typename _RandomAccessIterator >
bool __is_heap (_RandomAccessIterator __first, _RandomAccessIterator __last)
template<typename _RandomAccessIterator , typename _Compare >
bool __is_heap (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _RandomAccessIterator , typename _Distance , typename _Compare >
_Distance __is_heap_until (_RandomAccessIterator __first, _Distance __n, _Compare __comp)
template<typename _ForwardIterator1 , typename _ForwardIterator2 , typename _BinaryPredicate >
bool __is_permutation (_ForwardIterator1 __first1, _ForwardIterator1 __last1, _ForwardIterator2 __first2, _BinaryPredicate __pred)
template<typename _ForwardIterator , typename _Compare >
_ForwardIterator __is_sorted_until (_ForwardIterator __first, _ForwardIterator __last, _Compare __comp)
template<typename _Iter >
iterator_traits< _Iter >::iterator_category __iterator_category (const _Iter &)
template<typename _II1 , typename _II2 >
bool __lexicographical_compare_aux (_II1 __first1, _II1 __last1, _II2 __first2, _II2 __last2)
template<typename _II1 , typename _II2 , typename _Compare >
bool __lexicographical_compare_impl (_II1 __first1, _II1 __last1, _II2 __first2, _II2 __last2, _Compare __comp)
constexpr int __lg (int __n)
constexpr unsigned __lg (unsigned __n)
constexpr long __lg (long __n)
constexpr unsigned long __lg (unsigned long __n)
constexpr long long __lg (long long __n)
constexpr unsigned long long __lg (unsigned long long __n)
template<typename _ForwardIterator , typename _Tp , typename _Compare >
_ForwardIterator __lower_bound (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__val, _Compare __comp)
template<typename _RandomAccessIterator , typename _Compare >
void __make_heap (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _Iterator , typename _ReturnType = typename conditional<__move_if_noexcept_cond <typename iterator_traits<_Iterator>::value_type>::value, _Iterator, move_iterator<_Iterator>>::type>
_ReturnType __make_move_if_noexcept_iterator (_Iterator __i)
template<typename _Tp , _Lock_policy _Lp, typename... _Args>
__shared_ptr< _Tp, _Lp > __make_shared (_Args &&...__args)
template<typename _ForwardIterator , typename _Compare >
_GLIBCXX14_CONSTEXPR _ForwardIterator __max_element (_ForwardIterator __first, _ForwardIterator __last, _Compare __comp)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator , typename _Compare >
_OutputIterator __merge (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result, _Compare __comp)
template<typename _BidirectionalIterator , typename _Distance , typename _Pointer , typename _Compare >
void __merge_adaptive (_BidirectionalIterator __first, _BidirectionalIterator __middle, _BidirectionalIterator __last, _Distance __len1, _Distance __len2, _Pointer __buffer, _Distance __buffer_size, _Compare __comp)
template<typename _RandomAccessIterator1 , typename _RandomAccessIterator2 , typename _Distance , typename _Compare >
void __merge_sort_loop (_RandomAccessIterator1 __first, _RandomAccessIterator1 __last, _RandomAccessIterator2 __result, _Distance __step_size, _Compare __comp)
template<typename _RandomAccessIterator , typename _Pointer , typename _Compare >
void __merge_sort_with_buffer (_RandomAccessIterator __first, _RandomAccessIterator __last, _Pointer __buffer, _Compare __comp)
template<typename _BidirectionalIterator , typename _Distance , typename _Compare >
void __merge_without_buffer (_BidirectionalIterator __first, _BidirectionalIterator __middle, _BidirectionalIterator __last, _Distance __len1, _Distance __len2, _Compare __comp)
template<typename _ForwardIterator , typename _Compare >
_GLIBCXX14_CONSTEXPR _ForwardIterator __min_element (_ForwardIterator __first, _ForwardIterator __last, _Compare __comp)
template<typename _ForwardIterator , typename _Compare >
_GLIBCXX14_CONSTEXPR pair< _ForwardIterator, _ForwardIterator > __minmax_element (_ForwardIterator __first, _ForwardIterator __last, _Compare __comp)
template<typename _InputIterator1 , typename _InputIterator2 , typename _BinaryPredicate >
pair< _InputIterator1, _InputIterator2 > __mismatch (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _BinaryPredicate __binary_pred)
template<typename _Iterator >
_Miter_base< _Iterator >::iterator_type __miter_base (_Iterator __it)
template<typename _Iterator , typename _Compare >
void __move_median_to_first (_Iterator __result, _Iterator __a, _Iterator __b, _Iterator __c, _Compare __comp)
template<typename _InputIterator , typename _OutputIterator , typename _Compare >
_OutputIterator __move_merge (_InputIterator __first1, _InputIterator __last1, _InputIterator __first2, _InputIterator __last2, _OutputIterator __result, _Compare __comp)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator , typename _Compare >
void __move_merge_adaptive (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result, _Compare __comp)
template<typename _BidirectionalIterator1 , typename _BidirectionalIterator2 , typename _BidirectionalIterator3 , typename _Compare >
void __move_merge_adaptive_backward (_BidirectionalIterator1 __first1, _BidirectionalIterator1 __last1, _BidirectionalIterator2 __first2, _BidirectionalIterator2 __last2, _BidirectionalIterator3 __result, _Compare __comp)
template<typename _BidirectionalIterator , typename _Compare >
bool __next_permutation (_BidirectionalIterator __first, _BidirectionalIterator __last, _Compare __comp)
template<typename _Iterator >
_Niter_base< _Iterator >::iterator_type __niter_base (_Iterator __it)
template<typename _CharT , typename _Traits >
void __ostream_fill (basic_ostream< _CharT, _Traits > &__out, streamsize __n)
template<typename _CharT , typename _Traits >
basic_ostream< _CharT, _Traits > & __ostream_insert (basic_ostream< _CharT, _Traits > &__out, const _CharT *__s, streamsize __n)
template<typename _CharT , typename _Traits >
void __ostream_write (basic_ostream< _CharT, _Traits > &__out, const _CharT *__s, streamsize __n)
template<typename _RandomAccessIterator , typename _Compare >
void __partial_sort (_RandomAccessIterator __first, _RandomAccessIterator __middle, _RandomAccessIterator __last, _Compare __comp)
template<typename _InputIterator , typename _RandomAccessIterator , typename _Compare >
_RandomAccessIterator __partial_sort_copy (_InputIterator __first, _InputIterator __last, _RandomAccessIterator __result_first, _RandomAccessIterator __result_last, _Compare __comp)
template<typename _ForwardIterator , typename _Predicate >
_ForwardIterator __partition (_ForwardIterator __first, _ForwardIterator __last, _Predicate __pred, forward_iterator_tag)
template<typename _BidirectionalIterator , typename _Predicate >
_BidirectionalIterator __partition (_BidirectionalIterator __first, _BidirectionalIterator __last, _Predicate __pred, bidirectional_iterator_tag)
template<typename _RandomAccessIterator , typename _Compare >
void __pop_heap (_RandomAccessIterator __first, _RandomAccessIterator __last, _RandomAccessIterator __result, _Compare __comp)
template<typename _BidirectionalIterator , typename _Compare >
bool __prev_permutation (_BidirectionalIterator __first, _BidirectionalIterator __last, _Compare __comp)
template<typename _RandomAccessIterator , typename _Distance , typename _Tp , typename _Compare >
void __push_heap (_RandomAccessIterator __first, _Distance __holeIndex, _Distance __topIndex, _Tp __value, _Compare __comp)
template<typename _InputIterator , typename _OutputIterator , typename _Predicate >
_OutputIterator __remove_copy_if (_InputIterator __first, _InputIterator __last, _OutputIterator __result, _Predicate __pred)
template<typename _ForwardIterator , typename _Predicate >
_ForwardIterator __remove_if (_ForwardIterator __first, _ForwardIterator __last, _Predicate __pred)
template<typename _InputIterator , typename _OutputIterator , typename _Predicate , typename _Tp >
_OutputIterator __replace_copy_if (_InputIterator __first, _InputIterator __last, _OutputIterator __result, _Predicate __pred, const _Tp &__new_value)
template<typename _BidirectionalIterator >
void __reverse (_BidirectionalIterator __first, _BidirectionalIterator __last, bidirectional_iterator_tag)
template<typename _RandomAccessIterator >
void __reverse (_RandomAccessIterator __first, _RandomAccessIterator __last, random_access_iterator_tag)
template<typename _BidirectionalIterator1 , typename _BidirectionalIterator2 , typename _Distance >
_BidirectionalIterator1 __rotate_adaptive (_BidirectionalIterator1 __first, _BidirectionalIterator1 __middle, _BidirectionalIterator1 __last, _Distance __len1, _Distance __len2, _BidirectionalIterator2 __buffer, _Distance __buffer_size)
template<typename _ForwardIterator1 , typename _ForwardIterator2 , typename _BinaryPredicate >
_ForwardIterator1 __search (_ForwardIterator1 __first1, _ForwardIterator1 __last1, _ForwardIterator2 __first2, _ForwardIterator2 __last2, _BinaryPredicate __predicate)
template<typename _ForwardIterator , typename _Integer , typename _UnaryPredicate >
_ForwardIterator __search_n (_ForwardIterator __first, _ForwardIterator __last, _Integer __count, _UnaryPredicate __unary_pred)
template<typename _ForwardIterator , typename _Integer , typename _UnaryPredicate >
_ForwardIterator __search_n_aux (_ForwardIterator __first, _ForwardIterator __last, _Integer __count, _UnaryPredicate __unary_pred, std::forward_iterator_tag)
template<typename _RandomAccessIter , typename _Integer , typename _UnaryPredicate >
_RandomAccessIter __search_n_aux (_RandomAccessIter __first, _RandomAccessIter __last, _Integer __count, _UnaryPredicate __unary_pred, std::random_access_iterator_tag)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator , typename _Compare >
_OutputIterator __set_difference (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result, _Compare __comp)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator , typename _Compare >
_OutputIterator __set_intersection (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result, _Compare __comp)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator , typename _Compare >
_OutputIterator __set_symmetric_difference (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result, _Compare __comp)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator , typename _Compare >
_OutputIterator __set_union (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result, _Compare __comp)
template<typename _RandomAccessIterator , typename _Compare >
void __sort (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _RandomAccessIterator , typename _Compare >
void __sort_heap (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _ForwardIterator , typename _Predicate >
_ForwardIterator __stable_partition (_ForwardIterator __first, _ForwardIterator __last, _Predicate __pred)
template<typename _ForwardIterator , typename _Pointer , typename _Predicate , typename _Distance >
_ForwardIterator __stable_partition_adaptive (_ForwardIterator __first, _ForwardIterator __last, _Predicate __pred, _Distance __len, _Pointer __buffer, _Distance __buffer_size)
template<typename _RandomAccessIterator , typename _Compare >
void __stable_sort (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _RandomAccessIterator , typename _Pointer , typename _Distance , typename _Compare >
void __stable_sort_adaptive (_RandomAccessIterator __first, _RandomAccessIterator __last, _Pointer __buffer, _Distance __buffer_size, _Compare __comp)
template<typename _CharT , typename _Traits , typename _Alloc , typename _State >
bool __str_codecvt_in (const char *__first, const char *__last, basic_string< _CharT, _Traits, _Alloc > &__outstr, const codecvt< _CharT, char, _State > &__cvt, _State &__state, size_t &__count)
template<typename _CharT , typename _Traits , typename _Alloc , typename _State >
bool __str_codecvt_in (const char *__first, const char *__last, basic_string< _CharT, _Traits, _Alloc > &__outstr, const codecvt< _CharT, char, _State > &__cvt)
template<typename _CharT , typename _Traits , typename _Alloc , typename _State >
bool __str_codecvt_out (const _CharT *__first, const _CharT *__last, basic_string< char, _Traits, _Alloc > &__outstr, const codecvt< _CharT, char, _State > &__cvt, _State &__state, size_t &__count)
template<typename _CharT , typename _Traits , typename _Alloc , typename _State >
bool __str_codecvt_out (const _CharT *__first, const _CharT *__last, basic_string< char, _Traits, _Alloc > &__outstr, const codecvt< _CharT, char, _State > &__cvt)
void __throw_bad_alloc (void) __attribute__((__noreturn__))
void __throw_bad_cast (void) __attribute__((__noreturn__))
void __throw_bad_exception (void) __attribute__((__noreturn__))
void __throw_bad_function_call () __attribute__((__noreturn__))
void __throw_bad_typeid (void) __attribute__((__noreturn__))
void __throw_bad_weak_ptr ()
void __throw_domain_error (const char *) __attribute__((__noreturn__))
void __throw_future_error (int) __attribute__((__noreturn__))
void __throw_invalid_argument (const char *) __attribute__((__noreturn__))
void __throw_ios_failure (const char *) __attribute__((__noreturn__))
void __throw_length_error (const char *) __attribute__((__noreturn__))
void __throw_logic_error (const char *) __attribute__((__noreturn__))
void __throw_out_of_range (const char *) __attribute__((__noreturn__))
void __throw_out_of_range_fmt (const char *,...) __attribute__((__noreturn__)) __attribute__((__format__(__gnu_printf__
void __throw_overflow_error (const char *) __attribute__((__noreturn__))
void __throw_range_error (const char *) __attribute__((__noreturn__))
void __throw_regex_error (regex_constants::error_type __ecode)
void void __throw_runtime_error (const char *) __attribute__((__noreturn__))
void __throw_system_error (int) __attribute__((__noreturn__))
void __throw_underflow_error (const char *) __attribute__((__noreturn__))
template<typename _RandomAccessIterator , typename _Compare >
void __unguarded_insertion_sort (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _RandomAccessIterator , typename _Compare >
void __unguarded_linear_insert (_RandomAccessIterator __last, _Compare __comp)
template<typename _RandomAccessIterator , typename _Compare >
_RandomAccessIterator __unguarded_partition (_RandomAccessIterator __first, _RandomAccessIterator __last, _RandomAccessIterator __pivot, _Compare __comp)
template<typename _RandomAccessIterator , typename _Compare >
_RandomAccessIterator __unguarded_partition_pivot (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _Pointer , typename _ForwardIterator >
void __uninitialized_construct_buf (_Pointer __first, _Pointer __last, _ForwardIterator __seed)
template<typename _InputIterator , typename _ForwardIterator , typename _Allocator >
_ForwardIterator __uninitialized_copy_a (_InputIterator __first, _InputIterator __last, _ForwardIterator __result, _Allocator &__alloc)
template<typename _InputIterator , typename _ForwardIterator , typename _Tp >
_ForwardIterator __uninitialized_copy_a (_InputIterator __first, _InputIterator __last, _ForwardIterator __result, allocator< _Tp > &)
template<typename _InputIterator1 , typename _InputIterator2 , typename _ForwardIterator , typename _Allocator >
_ForwardIterator __uninitialized_copy_move (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _ForwardIterator __result, _Allocator &__alloc)
template<typename _InputIterator , typename _Size , typename _ForwardIterator >
_ForwardIterator __uninitialized_copy_n (_InputIterator __first, _Size __n, _ForwardIterator __result, input_iterator_tag)
template<typename _RandomAccessIterator , typename _Size , typename _ForwardIterator >
_ForwardIterator __uninitialized_copy_n (_RandomAccessIterator __first, _Size __n, _ForwardIterator __result, random_access_iterator_tag)
template<typename _ForwardIterator >
void __uninitialized_default (_ForwardIterator __first, _ForwardIterator __last)
template<typename _ForwardIterator , typename _Allocator >
void __uninitialized_default_a (_ForwardIterator __first, _ForwardIterator __last, _Allocator &__alloc)
template<typename _ForwardIterator , typename _Tp >
void __uninitialized_default_a (_ForwardIterator __first, _ForwardIterator __last, allocator< _Tp > &)
template<typename _ForwardIterator , typename _Size >
_ForwardIterator __uninitialized_default_n (_ForwardIterator __first, _Size __n)
template<typename _ForwardIterator , typename _Size , typename _Allocator >
_ForwardIterator __uninitialized_default_n_a (_ForwardIterator __first, _Size __n, _Allocator &__alloc)
template<typename _ForwardIterator , typename _Size , typename _Tp >
_ForwardIterator __uninitialized_default_n_a (_ForwardIterator __first, _Size __n, allocator< _Tp > &)
template<typename _ForwardIterator , typename _Tp , typename _Allocator >
void __uninitialized_fill_a (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__x, _Allocator &__alloc)
template<typename _ForwardIterator , typename _Tp , typename _Tp2 >
void __uninitialized_fill_a (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__x, allocator< _Tp2 > &)
template<typename _ForwardIterator , typename _Tp , typename _InputIterator , typename _Allocator >
_ForwardIterator __uninitialized_fill_move (_ForwardIterator __result, _ForwardIterator __mid, const _Tp &__x, _InputIterator __first, _InputIterator __last, _Allocator &__alloc)
template<typename _ForwardIterator , typename _Size , typename _Tp , typename _Allocator >
_ForwardIterator __uninitialized_fill_n_a (_ForwardIterator __first, _Size __n, const _Tp &__x, _Allocator &__alloc)
template<typename _ForwardIterator , typename _Size , typename _Tp , typename _Tp2 >
_ForwardIterator __uninitialized_fill_n_a (_ForwardIterator __first, _Size __n, const _Tp &__x, allocator< _Tp2 > &)
template<typename _InputIterator , typename _ForwardIterator , typename _Allocator >
_ForwardIterator __uninitialized_move_a (_InputIterator __first, _InputIterator __last, _ForwardIterator __result, _Allocator &__alloc)
template<typename _InputIterator1 , typename _InputIterator2 , typename _ForwardIterator , typename _Allocator >
_ForwardIterator __uninitialized_move_copy (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _ForwardIterator __result, _Allocator &__alloc)
template<typename _InputIterator , typename _ForwardIterator , typename _Tp , typename _Allocator >
void __uninitialized_move_fill (_InputIterator __first1, _InputIterator __last1, _ForwardIterator __first2, _ForwardIterator __last2, const _Tp &__x, _Allocator &__alloc)
template<typename _InputIterator , typename _ForwardIterator , typename _Allocator >
_ForwardIterator __uninitialized_move_if_noexcept_a (_InputIterator __first, _InputIterator __last, _ForwardIterator __result, _Allocator &__alloc)
template<typename _ForwardIterator , typename _BinaryPredicate >
_ForwardIterator __unique (_ForwardIterator __first, _ForwardIterator __last, _BinaryPredicate __binary_pred)
template<typename _ForwardIterator , typename _OutputIterator , typename _BinaryPredicate >
_OutputIterator __unique_copy (_ForwardIterator __first, _ForwardIterator __last, _OutputIterator __result, _BinaryPredicate __binary_pred, forward_iterator_tag, output_iterator_tag)
template<typename _InputIterator , typename _OutputIterator , typename _BinaryPredicate >
_OutputIterator __unique_copy (_InputIterator __first, _InputIterator __last, _OutputIterator __result, _BinaryPredicate __binary_pred, input_iterator_tag, output_iterator_tag)
template<typename _InputIterator , typename _ForwardIterator , typename _BinaryPredicate >
_ForwardIterator __unique_copy (_InputIterator __first, _InputIterator __last, _ForwardIterator __result, _BinaryPredicate __binary_pred, input_iterator_tag, forward_iterator_tag)
template<typename _ForwardIterator , typename _Tp , typename _Compare >
_ForwardIterator __upper_bound (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__val, _Compare __comp)
template<typename _Tp , typename _Alloc , typename... _Args>
__uses_alloc_t< _Tp, _Alloc, _Args...> __use_alloc (const _Alloc &__a)
template<typename _Tp >
void __valarray_copy (const _Tp *__restrict__ __a, size_t __n, _Tp *__restrict__ __b)
template<typename _Tp >
void __valarray_copy (const _Tp *__restrict__ __a, size_t __n, size_t __s, _Tp *__restrict__ __b)
template<typename _Tp >
void __valarray_copy (const _Tp *__restrict__ __a, _Tp *__restrict__ __b, size_t __n, size_t __s)
template<typename _Tp >
void __valarray_copy (const _Tp *__restrict__ __src, size_t __n, size_t __s1, _Tp *__restrict__ __dst, size_t __s2)
template<typename _Tp >
void __valarray_copy (const _Tp *__restrict__ __a, const size_t *__restrict__ __i, _Tp *__restrict__ __b, size_t __n)
template<typename _Tp >
void __valarray_copy (const _Tp *__restrict__ __a, size_t __n, _Tp *__restrict__ __b, const size_t *__restrict__ __i)
template<typename _Tp >
void __valarray_copy (const _Tp *__restrict__ __src, size_t __n, const size_t *__restrict__ __i, _Tp *__restrict__ __dst, const size_t *__restrict__ __j)
template<typename _Tp >
void __valarray_copy (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b)
template<typename _Tp >
void __valarray_copy (_Array< _Tp > __a, size_t __n, size_t __s, _Array< _Tp > __b)
template<typename _Tp >
void __valarray_copy (_Array< _Tp > __a, _Array< _Tp > __b, size_t __n, size_t __s)
template<typename _Tp >
void __valarray_copy (_Array< _Tp > __a, size_t __n, size_t __s1, _Array< _Tp > __b, size_t __s2)
template<typename _Tp >
void __valarray_copy (_Array< _Tp > __a, _Array< size_t > __i, _Array< _Tp > __b, size_t __n)
template<typename _Tp >
void __valarray_copy (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< size_t > __i)
template<typename _Tp >
void __valarray_copy (_Array< _Tp > __src, size_t __n, _Array< size_t > __i, _Array< _Tp > __dst, _Array< size_t > __j)
template<typename _Tp >
void __valarray_copy_construct (const _Tp *__b, const _Tp *__e, _Tp *__restrict__ __o)
template<typename _Tp >
void __valarray_copy_construct (const _Tp *__restrict__ __a, size_t __n, size_t __s, _Tp *__restrict__ __o)
template<typename _Tp >
void __valarray_copy_construct (const _Tp *__restrict__ __a, const size_t *__restrict__ __i, _Tp *__restrict__ __o, size_t __n)
template<typename _Tp >
void __valarray_copy_construct (_Array< _Tp > __a, _Array< size_t > __i, _Array< _Tp > __b, size_t __n)
template<typename _Tp >
void __valarray_copy_construct (_Array< _Tp > __a, size_t __n, size_t __s, _Array< _Tp > __b)
template<typename _Tp >
void __valarray_default_construct (_Tp *__b, _Tp *__e)
template<typename _Tp >
void __valarray_destroy_elements (_Tp *__b, _Tp *__e)
template<typename _Tp >
void __valarray_fill (_Tp *__restrict__ __a, size_t __n, const _Tp &__t)
template<typename _Tp >
void __valarray_fill (_Tp *__restrict__ __a, size_t __n, size_t __s, const _Tp &__t)
template<typename _Tp >
void __valarray_fill (_Tp *__restrict__ __a, const size_t *__restrict__ __i, size_t __n, const _Tp &__t)
template<typename _Tp >
void __valarray_fill (_Array< _Tp > __a, size_t __n, const _Tp &__t)
template<typename _Tp >
void __valarray_fill (_Array< _Tp > __a, size_t __n, size_t __s, const _Tp &__t)
template<typename _Tp >
void __valarray_fill (_Array< _Tp > __a, _Array< size_t > __i, size_t __n, const _Tp &__t)
template<typename _Tp >
void __valarray_fill_construct (_Tp *__b, _Tp *__e, const _Tp __t)
void * __valarray_get_memory (size_t __n)
template<typename _Tp >
_Tp *__restrict__ __valarray_get_storage (size_t __n)
template<typename _Ta >
_Ta::value_type __valarray_max (const _Ta &__a)
template<typename _Ta >
_Ta::value_type __valarray_min (const _Ta &__a)
template<typename _Tp >
_Tp __valarray_product (const _Tp *__f, const _Tp *__l)
void __valarray_release_memory (void *__p)
template<typename _Tp >
_Tp __valarray_sum (const _Tp *__f, const _Tp *__l)
template<typename _CharT >
ostreambuf_iterator< _CharT > __write (ostreambuf_iterator< _CharT > __s, const _CharT *__ws, int __len)
template<typename _CharT , typename _OutIter >
_OutIter __write (_OutIter __s, const _CharT *__ws, int __len)
template<typename _Tp >
void _Array_augmented___bitwise_and (_Array< _Tp > __a, size_t __n, const _Tp &__t)
template<typename _Tp >
void _Array_augmented___bitwise_and (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b)
template<typename _Tp , class _Dom >
void _Array_augmented___bitwise_and (_Array< _Tp > __a, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___bitwise_and (_Array< _Tp > __a, size_t __n, size_t __s, _Array< _Tp > __b)
template<typename _Tp >
void _Array_augmented___bitwise_and (_Array< _Tp > __a, _Array< _Tp > __b, size_t __n, size_t __s)
template<typename _Tp , class _Dom >
void _Array_augmented___bitwise_and (_Array< _Tp > __a, size_t __s, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___bitwise_and (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< size_t > __i)
template<typename _Tp , class _Dom >
void _Array_augmented___bitwise_and (_Array< _Tp > __a, _Array< size_t > __i, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___bitwise_and (_Array< _Tp > __a, _Array< bool > __m, _Array< _Tp > __b, size_t __n)
template<typename _Tp , class _Dom >
void _Array_augmented___bitwise_and (_Array< _Tp > __a, _Array< bool > __m, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___bitwise_and (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< bool > __m)
template<typename _Tp >
void _Array_augmented___bitwise_and (_Array< _Tp > __a, _Array< size_t > __i, _Array< _Tp > __b, size_t __n)
template<typename _Tp >
void _Array_augmented___bitwise_or (_Array< _Tp > __a, _Array< size_t > __i, _Array< _Tp > __b, size_t __n)
template<typename _Tp >
void _Array_augmented___bitwise_or (_Array< _Tp > __a, size_t __n, const _Tp &__t)
template<typename _Tp >
void _Array_augmented___bitwise_or (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b)
template<typename _Tp , class _Dom >
void _Array_augmented___bitwise_or (_Array< _Tp > __a, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___bitwise_or (_Array< _Tp > __a, size_t __n, size_t __s, _Array< _Tp > __b)
template<typename _Tp >
void _Array_augmented___bitwise_or (_Array< _Tp > __a, _Array< _Tp > __b, size_t __n, size_t __s)
template<typename _Tp , class _Dom >
void _Array_augmented___bitwise_or (_Array< _Tp > __a, size_t __s, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___bitwise_or (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< size_t > __i)
template<typename _Tp , class _Dom >
void _Array_augmented___bitwise_or (_Array< _Tp > __a, _Array< size_t > __i, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___bitwise_or (_Array< _Tp > __a, _Array< bool > __m, _Array< _Tp > __b, size_t __n)
template<typename _Tp , class _Dom >
void _Array_augmented___bitwise_or (_Array< _Tp > __a, _Array< bool > __m, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___bitwise_or (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< bool > __m)
template<typename _Tp >
void _Array_augmented___bitwise_xor (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b)
template<typename _Tp , class _Dom >
void _Array_augmented___bitwise_xor (_Array< _Tp > __a, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___bitwise_xor (_Array< _Tp > __a, size_t __n, size_t __s, _Array< _Tp > __b)
template<typename _Tp >
void _Array_augmented___bitwise_xor (_Array< _Tp > __a, _Array< _Tp > __b, size_t __n, size_t __s)
template<typename _Tp , class _Dom >
void _Array_augmented___bitwise_xor (_Array< _Tp > __a, size_t __s, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___bitwise_xor (_Array< _Tp > __a, _Array< bool > __m, _Array< _Tp > __b, size_t __n)
template<typename _Tp >
void _Array_augmented___bitwise_xor (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< bool > __m)
template<typename _Tp >
void _Array_augmented___bitwise_xor (_Array< _Tp > __a, size_t __n, const _Tp &__t)
template<typename _Tp , class _Dom >
void _Array_augmented___bitwise_xor (_Array< _Tp > __a, _Array< bool > __m, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___bitwise_xor (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< size_t > __i)
template<typename _Tp , class _Dom >
void _Array_augmented___bitwise_xor (_Array< _Tp > __a, _Array< size_t > __i, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___bitwise_xor (_Array< _Tp > __a, _Array< size_t > __i, _Array< _Tp > __b, size_t __n)
template<typename _Tp >
void _Array_augmented___divides (_Array< _Tp > __a, size_t __n, const _Tp &__t)
template<typename _Tp >
void _Array_augmented___divides (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b)
template<typename _Tp , class _Dom >
void _Array_augmented___divides (_Array< _Tp > __a, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___divides (_Array< _Tp > __a, size_t __n, size_t __s, _Array< _Tp > __b)
template<typename _Tp >
void _Array_augmented___divides (_Array< _Tp > __a, _Array< _Tp > __b, size_t __n, size_t __s)
template<typename _Tp , class _Dom >
void _Array_augmented___divides (_Array< _Tp > __a, size_t __s, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___divides (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< size_t > __i)
template<typename _Tp , class _Dom >
void _Array_augmented___divides (_Array< _Tp > __a, _Array< size_t > __i, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___divides (_Array< _Tp > __a, _Array< bool > __m, _Array< _Tp > __b, size_t __n)
template<typename _Tp , class _Dom >
void _Array_augmented___divides (_Array< _Tp > __a, _Array< bool > __m, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___divides (_Array< _Tp > __a, _Array< size_t > __i, _Array< _Tp > __b, size_t __n)
template<typename _Tp >
void _Array_augmented___divides (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< bool > __m)
template<typename _Tp >
void _Array_augmented___minus (_Array< _Tp > __a, size_t __n, const _Tp &__t)
template<typename _Tp >
void _Array_augmented___minus (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b)
template<typename _Tp , class _Dom >
void _Array_augmented___minus (_Array< _Tp > __a, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___minus (_Array< _Tp > __a, size_t __n, size_t __s, _Array< _Tp > __b)
template<typename _Tp >
void _Array_augmented___minus (_Array< _Tp > __a, _Array< _Tp > __b, size_t __n, size_t __s)
template<typename _Tp , class _Dom >
void _Array_augmented___minus (_Array< _Tp > __a, size_t __s, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___minus (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< size_t > __i)
template<typename _Tp , class _Dom >
void _Array_augmented___minus (_Array< _Tp > __a, _Array< size_t > __i, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___minus (_Array< _Tp > __a, _Array< bool > __m, _Array< _Tp > __b, size_t __n)
template<typename _Tp >
void _Array_augmented___minus (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< bool > __m)
template<typename _Tp , class _Dom >
void _Array_augmented___minus (_Array< _Tp > __a, _Array< bool > __m, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___minus (_Array< _Tp > __a, _Array< size_t > __i, _Array< _Tp > __b, size_t __n)
template<typename _Tp >
void _Array_augmented___modulus (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< bool > __m)
template<typename _Tp >
void _Array_augmented___modulus (_Array< _Tp > __a, size_t __n, const _Tp &__t)
template<typename _Tp >
void _Array_augmented___modulus (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b)
template<typename _Tp , class _Dom >
void _Array_augmented___modulus (_Array< _Tp > __a, size_t __s, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___modulus (_Array< _Tp > __a, _Array< size_t > __i, _Array< _Tp > __b, size_t __n)
template<typename _Tp >
void _Array_augmented___modulus (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< size_t > __i)
template<typename _Tp , class _Dom >
void _Array_augmented___modulus (_Array< _Tp > __a, _Array< size_t > __i, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___modulus (_Array< _Tp > __a, _Array< bool > __m, _Array< _Tp > __b, size_t __n)
template<typename _Tp >
void _Array_augmented___modulus (_Array< _Tp > __a, size_t __n, size_t __s, _Array< _Tp > __b)
template<typename _Tp >
void _Array_augmented___modulus (_Array< _Tp > __a, _Array< _Tp > __b, size_t __n, size_t __s)
template<typename _Tp , class _Dom >
void _Array_augmented___modulus (_Array< _Tp > __a, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp , class _Dom >
void _Array_augmented___modulus (_Array< _Tp > __a, _Array< bool > __m, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp , class _Dom >
void _Array_augmented___multiplies (_Array< _Tp > __a, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___multiplies (_Array< _Tp > __a, size_t __n, const _Tp &__t)
template<typename _Tp >
void _Array_augmented___multiplies (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b)
template<typename _Tp >
void _Array_augmented___multiplies (_Array< _Tp > __a, size_t __n, size_t __s, _Array< _Tp > __b)
template<typename _Tp >
void _Array_augmented___multiplies (_Array< _Tp > __a, _Array< _Tp > __b, size_t __n, size_t __s)
template<typename _Tp , class _Dom >
void _Array_augmented___multiplies (_Array< _Tp > __a, size_t __s, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___multiplies (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< size_t > __i)
template<typename _Tp , class _Dom >
void _Array_augmented___multiplies (_Array< _Tp > __a, _Array< size_t > __i, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___multiplies (_Array< _Tp > __a, _Array< bool > __m, _Array< _Tp > __b, size_t __n)
template<typename _Tp , class _Dom >
void _Array_augmented___multiplies (_Array< _Tp > __a, _Array< bool > __m, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___multiplies (_Array< _Tp > __a, _Array< size_t > __i, _Array< _Tp > __b, size_t __n)
template<typename _Tp >
void _Array_augmented___multiplies (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< bool > __m)
template<typename _Tp >
void _Array_augmented___plus (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b)
template<typename _Tp >
void _Array_augmented___plus (_Array< _Tp > __a, size_t __n, size_t __s, _Array< _Tp > __b)
template<typename _Tp >
void _Array_augmented___plus (_Array< _Tp > __a, _Array< _Tp > __b, size_t __n, size_t __s)
template<typename _Tp , class _Dom >
void _Array_augmented___plus (_Array< _Tp > __a, size_t __s, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___plus (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< size_t > __i)
template<typename _Tp , class _Dom >
void _Array_augmented___plus (_Array< _Tp > __a, _Array< size_t > __i, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___plus (_Array< _Tp > __a, _Array< bool > __m, _Array< _Tp > __b, size_t __n)
template<typename _Tp , class _Dom >
void _Array_augmented___plus (_Array< _Tp > __a, _Array< bool > __m, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp , class _Dom >
void _Array_augmented___plus (_Array< _Tp > __a, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___plus (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< bool > __m)
template<typename _Tp >
void _Array_augmented___plus (_Array< _Tp > __a, size_t __n, const _Tp &__t)
template<typename _Tp >
void _Array_augmented___plus (_Array< _Tp > __a, _Array< size_t > __i, _Array< _Tp > __b, size_t __n)
template<typename _Tp >
void _Array_augmented___shift_left (_Array< _Tp > __a, size_t __n, const _Tp &__t)
template<typename _Tp >
void _Array_augmented___shift_left (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b)
template<typename _Tp >
void _Array_augmented___shift_left (_Array< _Tp > __a, size_t __n, size_t __s, _Array< _Tp > __b)
template<typename _Tp >
void _Array_augmented___shift_left (_Array< _Tp > __a, _Array< _Tp > __b, size_t __n, size_t __s)
template<typename _Tp , class _Dom >
void _Array_augmented___shift_left (_Array< _Tp > __a, size_t __s, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___shift_left (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< size_t > __i)
template<typename _Tp , class _Dom >
void _Array_augmented___shift_left (_Array< _Tp > __a, _Array< size_t > __i, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___shift_left (_Array< _Tp > __a, _Array< bool > __m, _Array< _Tp > __b, size_t __n)
template<typename _Tp , class _Dom >
void _Array_augmented___shift_left (_Array< _Tp > __a, _Array< bool > __m, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___shift_left (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< bool > __m)
template<typename _Tp , class _Dom >
void _Array_augmented___shift_left (_Array< _Tp > __a, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___shift_left (_Array< _Tp > __a, _Array< size_t > __i, _Array< _Tp > __b, size_t __n)
template<typename _Tp >
void _Array_augmented___shift_right (_Array< _Tp > __a, size_t __n, const _Tp &__t)
template<typename _Tp >
void _Array_augmented___shift_right (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b)
template<typename _Tp >
void _Array_augmented___shift_right (_Array< _Tp > __a, size_t __n, size_t __s, _Array< _Tp > __b)
template<typename _Tp >
void _Array_augmented___shift_right (_Array< _Tp > __a, _Array< _Tp > __b, size_t __n, size_t __s)
template<typename _Tp , class _Dom >
void _Array_augmented___shift_right (_Array< _Tp > __a, size_t __s, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp , class _Dom >
void _Array_augmented___shift_right (_Array< _Tp > __a, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___shift_right (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< size_t > __i)
template<typename _Tp , class _Dom >
void _Array_augmented___shift_right (_Array< _Tp > __a, _Array< size_t > __i, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___shift_right (_Array< _Tp > __a, _Array< bool > __m, _Array< _Tp > __b, size_t __n)
template<typename _Tp , class _Dom >
void _Array_augmented___shift_right (_Array< _Tp > __a, _Array< bool > __m, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___shift_right (_Array< _Tp > __a, _Array< size_t > __i, _Array< _Tp > __b, size_t __n)
template<typename _Tp >
void _Array_augmented___shift_right (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< bool > __m)
template<typename _T1 , typename... _Args>
void _Construct (_T1 *__p, _Args &&...__args)
template<typename _Tp >
void _Destroy (_Tp *__pointer)
template<typename _ForwardIterator >
void _Destroy (_ForwardIterator __first, _ForwardIterator __last)
template<typename _ForwardIterator , typename _Allocator >
void _Destroy (_ForwardIterator __first, _ForwardIterator __last, _Allocator &__alloc)
template<typename _ForwardIterator , typename _Tp >
void _Destroy (_ForwardIterator __first, _ForwardIterator __last, allocator< _Tp > &)
size_t _Fnv_hash_bytes (const void *__ptr, size_t __len, size_t __seed)
size_t _Hash_bytes (const void *__ptr, size_t __len, size_t __seed)
unsigned int _Rb_tree_black_count (const _Rb_tree_node_base *__node, const _Rb_tree_node_base *__root) throw ()
_Rb_tree_node_base * _Rb_tree_decrement (_Rb_tree_node_base *__x) throw ()
const _Rb_tree_node_base * _Rb_tree_decrement (const _Rb_tree_node_base *__x) throw ()
_Rb_tree_node_base * _Rb_tree_increment (_Rb_tree_node_base *__x) throw ()
const _Rb_tree_node_base * _Rb_tree_increment (const _Rb_tree_node_base *__x) throw ()
void _Rb_tree_insert_and_rebalance (const bool __insert_left, _Rb_tree_node_base *__x, _Rb_tree_node_base *__p, _Rb_tree_node_base &__header) throw ()
_Rb_tree_node_base * _Rb_tree_rebalance_for_erase (_Rb_tree_node_base *const __z, _Rb_tree_node_base &__header) throw ()
template<class _Dom >
_Expr< _UnClos< _Abs, _Expr, _Dom >, typename _Dom::value_type > abs (const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp >
_Expr< _UnClos< _Abs, _ValArray, _Tp >, _Tp > abs (const valarray< _Tp > &__v)
template<typename _InputIterator , typename _Tp >
_Tp accumulate (_InputIterator __first, _InputIterator __last, _Tp __init)
template<typename _InputIterator , typename _Tp , typename _BinaryOperation >
_Tp accumulate (_InputIterator __first, _InputIterator __last, _Tp __init, _BinaryOperation __binary_op)
template<class _Dom >
_Expr< _UnClos< _Acos, _Expr, _Dom >, typename _Dom::value_type > acos (const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp >
_Expr< _UnClos< _Acos, _ValArray, _Tp >, _Tp > acos (const valarray< _Tp > &__v)
template<typename _Tp >
_Tp * addressof (_Tp &__r) noexcept
template<typename _InputIterator , typename _OutputIterator >
_OutputIterator adjacent_difference (_InputIterator __first, _InputIterator __last, _OutputIterator __result)
template<typename _InputIterator , typename _OutputIterator , typename _BinaryOperation >
_OutputIterator adjacent_difference (_InputIterator __first, _InputIterator __last, _OutputIterator __result, _BinaryOperation __binary_op)
template<typename _FIter >
_FIter adjacent_find (_FIter, _FIter)
template<typename _FIter , typename _BinaryPredicate >
_FIter adjacent_find (_FIter, _FIter, _BinaryPredicate)
template<typename _ForwardIterator >
_ForwardIterator adjacent_find (_ForwardIterator __first, _ForwardIterator __last)
template<typename _ForwardIterator , typename _BinaryPredicate >
_ForwardIterator adjacent_find (_ForwardIterator __first, _ForwardIterator __last, _BinaryPredicate __binary_pred)
template<typename _InputIterator , typename _Distance >
void advance (_InputIterator &__i, _Distance __n)
template<typename _IIter , typename _Predicate >
bool all_of (_IIter, _IIter, _Predicate)
template<typename _InputIterator , typename _Predicate >
bool all_of (_InputIterator __first, _InputIterator __last, _Predicate __pred)
template<typename _Tp , typename _Alloc , typename... _Args>
shared_ptr< _Tp > allocate_shared (const _Alloc &__a, _Args &&...__args)
template<typename _IIter , typename _Predicate >
bool any_of (_IIter, _IIter, _Predicate)
template<typename _InputIterator , typename _Predicate >
bool any_of (_InputIterator __first, _InputIterator __last, _Predicate __pred)
template<class _Dom >
_Expr< _UnClos< _Asin, _Expr, _Dom >, typename _Dom::value_type > asin (const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp >
_Expr< _UnClos< _Asin, _ValArray, _Tp >, _Tp > asin (const valarray< _Tp > &__v)
template<class _Dom >
_Expr< _UnClos< _Atan, _Expr, _Dom >, typename _Dom::value_type > atan (const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp >
_Expr< _UnClos< _Atan, _ValArray, _Tp >, _Tp > atan (const valarray< _Tp > &__v)
template<class _Dom1 , class _Dom2 >
_Expr< _BinClos< _Atan2, _Expr, _Expr, _Dom1, _Dom2 >, typename _Dom1::value_type > atan2 (const _Expr< _Dom1, typename _Dom1::value_type > &__e1, const _Expr< _Dom2, typename _Dom2::value_type > &__e2)
template<class _Dom >
_Expr< _BinClos< _Atan2, _Expr, _ValArray, _Dom, typename _Dom::value_type >, typename _Dom::value_type > atan2 (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom >
_Expr< _BinClos< _Atan2, _ValArray, _Expr, typename _Dom::value_type, _Dom >, typename _Dom::value_type > atan2 (const valarray< typename _Dom::valarray > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<class _Dom >
_Expr< _BinClos< _Atan2, _Expr, _Constant, _Dom, typename _Dom::value_type >, typename _Dom::value_type > atan2 (const _Expr< _Dom, typename _Dom::value_type > &__e, const typename _Dom::value_type &__t)
template<class _Dom >
_Expr< _BinClos< _Atan2, _Constant, _Expr, typename _Dom::value_type, _Dom >, typename _Dom::value_type > atan2 (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp >
_Expr< _BinClos< _Atan2, _ValArray, _Constant, _Tp, _Tp >, _Tp > atan2 (const valarray< _Tp > &__v, const _Tp &__t)
template<typename _Tp >
_Expr< _BinClos< _Atan2, _Constant, _ValArray, _Tp, _Tp >, _Tp > atan2 (const _Tp &__t, const valarray< _Tp > &__v)
template<typename _Tp >
_Expr< _BinClos< _Atan2, _ValArray, _ValArray, _Tp, _Tp >, _Tp > atan2 (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<typename _Container >
back_insert_iterator< _Container > back_inserter (_Container &__x)
template<class _Container >
auto begin (_Container &__cont) -> decltype(__cont.begin())
template<class _Container >
auto begin (const _Container &__cont) -> decltype(__cont.begin())
template<class _Tp , size_t _Nm>
_GLIBCXX14_CONSTEXPR _Tp * begin (_Tp(&__arr)[_Nm])
template<typename _FIter , typename _Tp >
bool binary_search (_FIter, _FIter, const _Tp &)
template<typename _FIter , typename _Tp , typename _Compare >
bool binary_search (_FIter, _FIter, const _Tp &, _Compare)
template<typename _ForwardIterator , typename _Tp >
bool binary_search (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__val)
template<typename _ForwardIterator , typename _Tp , typename _Compare >
bool binary_search (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__val, _Compare __comp)
template<typename _Operation , typename _Tp >
binder1st< _Operation > bind1st (const _Operation &__fn, const _Tp &__x)
template<typename _Operation , typename _Tp >
binder2nd< _Operation > bind2nd (const _Operation &__fn, const _Tp &__x)
ios_base & boolalpha (ios_base &__base)
template<typename _Tp , typename _Tp1 >
shared_ptr< _Tp > const_pointer_cast (const shared_ptr< _Tp1 > &__r) noexcept
template<typename _Tp , typename _Tp1 , _Lock_policy _Lp>
__shared_ptr< _Tp, _Lp > const_pointer_cast (const __shared_ptr< _Tp1, _Lp > &__r) noexcept
template<typename _IIter , typename _OIter >
_OIter copy (_IIter, _IIter, _OIter)
template<typename _CharT >
__gnu_cxx::__enable_if< __is_char< _CharT >::__value, ostreambuf_iterator< _CharT > >::__type copy (istreambuf_iterator< _CharT > __first, istreambuf_iterator< _CharT > __last, ostreambuf_iterator< _CharT > __result)
template<typename _Tp >
_Deque_iterator< _Tp, _Tp &, _Tp * > copy (_Deque_iterator< _Tp, const _Tp &, const _Tp * >, _Deque_iterator< _Tp, const _Tp &, const _Tp * >, _Deque_iterator< _Tp, _Tp &, _Tp * >)
template<typename _Tp >
_Deque_iterator< _Tp, _Tp &, _Tp * > copy (_Deque_iterator< _Tp, _Tp &, _Tp * > __first, _Deque_iterator< _Tp, _Tp &, _Tp * > __last, _Deque_iterator< _Tp, _Tp &, _Tp * > __result)
template<typename _II , typename _OI >
_OI copy (_II __first, _II __last, _OI __result)
template<typename _BIter1 , typename _BIter2 >
_BIter2 copy_backward (_BIter1, _BIter1, _BIter2)
template<typename _Tp >
_Deque_iterator< _Tp, _Tp &, _Tp * > copy_backward (_Deque_iterator< _Tp, const _Tp &, const _Tp * >, _Deque_iterator< _Tp, const _Tp &, const _Tp * >, _Deque_iterator< _Tp, _Tp &, _Tp * >)
template<typename _Tp >
_Deque_iterator< _Tp, _Tp &, _Tp * > copy_backward (_Deque_iterator< _Tp, _Tp &, _Tp * > __first, _Deque_iterator< _Tp, _Tp &, _Tp * > __last, _Deque_iterator< _Tp, _Tp &, _Tp * > __result)
template<typename _BI1 , typename _BI2 >
_BI2 copy_backward (_BI1 __first, _BI1 __last, _BI2 __result)
template<typename _Ex >
exception_ptr copy_exception (_Ex __ex) noexcept 1
template<typename _IIter , typename _OIter , typename _Predicate >
_OIter copy_if (_IIter, _IIter, _OIter, _Predicate)
template<typename _InputIterator , typename _OutputIterator , typename _Predicate >
_OutputIterator copy_if (_InputIterator __first, _InputIterator __last, _OutputIterator __result, _Predicate __pred)
template<typename _IIter , typename _Size , typename _OIter >
_OIter copy_n (_IIter, _Size, _OIter)
template<typename _InputIterator , typename _Size , typename _OutputIterator >
_OutputIterator copy_n (_InputIterator __first, _Size __n, _OutputIterator __result)
template<typename _Tp >
_Expr< _UnClos< _Cos, _ValArray, _Tp >, _Tp > cos (const valarray< _Tp > &__v)
template<class _Dom >
_Expr< _UnClos< _Cos, _Expr, _Dom >, typename _Dom::value_type > cos (const _Expr< _Dom, typename _Dom::value_type > &__e)
template<class _Dom >
_Expr< _UnClos< _Cosh, _Expr, _Dom >, typename _Dom::value_type > cosh (const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp >
_Expr< _UnClos< _Cosh, _ValArray, _Tp >, _Tp > cosh (const valarray< _Tp > &__v)
template<typename _IIter , typename _Tp >
iterator_traits< _IIter >::difference_type count (_IIter, _IIter, const _Tp &)
template<typename _InputIterator , typename _Tp >
iterator_traits< _InputIterator >::difference_type count (_InputIterator __first, _InputIterator __last, const _Tp &__value)
template<typename _IIter , typename _Predicate >
iterator_traits< _IIter >::difference_type count_if (_IIter, _IIter, _Predicate)
template<typename _InputIterator , typename _Predicate >
iterator_traits< _InputIterator >::difference_type count_if (_InputIterator __first, _InputIterator __last, _Predicate __pred)
exception_ptr current_exception () noexcept
ios_base & dec (ios_base &__base)
ios_base & defaultfloat (ios_base &__base)
template<typename _InputIterator >
iterator_traits< _InputIterator >::difference_type distance (_InputIterator __first, _InputIterator __last)
template<typename _Tp , typename _Tp1 >
shared_ptr< _Tp > dynamic_pointer_cast (const shared_ptr< _Tp1 > &__r) noexcept
template<typename _Tp , typename _Tp1 , _Lock_policy _Lp>
__shared_ptr< _Tp, _Lp > dynamic_pointer_cast (const __shared_ptr< _Tp1, _Lp > &__r) noexcept
template<class _Container >
auto end (_Container &__cont) -> decltype(__cont.end())
template<class _Container >
auto end (const _Container &__cont) -> decltype(__cont.end())
template<class _Tp , size_t _Nm>
_GLIBCXX14_CONSTEXPR _Tp * end (_Tp(&__arr)[_Nm])
template<typename _IIter1 , typename _IIter2 >
bool equal (_IIter1, _IIter1, _IIter2)
template<typename _IIter1 , typename _IIter2 , typename _BinaryPredicate >
bool equal (_IIter1 __first1, _IIter1 __last1, _IIter2 __first2, _BinaryPredicate __binary_pred)
template<typename _II1 , typename _II2 >
bool equal (_II1 __first1, _II1 __last1, _II2 __first2)
template<typename _FIter , typename _Tp >
pair< _FIter, _FIter > equal_range (_FIter, _FIter, const _Tp &)
template<typename _FIter , typename _Tp , typename _Compare >
pair< _FIter, _FIter > equal_range (_FIter, _FIter, const _Tp &, _Compare)
template<typename _ForwardIterator , typename _Tp >
pair< _ForwardIterator, _ForwardIterator > equal_range (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__val)
template<typename _ForwardIterator , typename _Tp , typename _Compare >
pair< _ForwardIterator, _ForwardIterator > equal_range (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__val, _Compare __comp)
template<class _Dom >
_Expr< _UnClos< _Exp, _Expr, _Dom >, typename _Dom::value_type > exp (const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp >
_Expr< _UnClos< _Exp, _ValArray, _Tp >, _Tp > exp (const valarray< _Tp > &__v)
template<typename _FIter , typename _Tp >
void fill (_FIter, _FIter, const _Tp &)
template<typename _Tp >
void fill (const _Deque_iterator< _Tp, _Tp &, _Tp * > &, const _Deque_iterator< _Tp, _Tp &, _Tp * > &, const _Tp &)
void fill (_Bit_iterator __first, _Bit_iterator __last, const bool &__x)
template<typename _ForwardIterator , typename _Tp >
void fill (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__value)
template<typename _OIter , typename _Size , typename _Tp >
_OIter fill_n (_OIter, _Size, const _Tp &)
template<typename _OI , typename _Size , typename _Tp >
_OI fill_n (_OI __first, _Size __n, const _Tp &__value)
template<typename _CharT >
__gnu_cxx::__enable_if< __is_char< _CharT >::__value, istreambuf_iterator< _CharT > >::__type find (istreambuf_iterator< _CharT > __first, istreambuf_iterator< _CharT > __last, const _CharT &__val)
template<typename _IIter , typename _Tp >
_IIter find (_IIter, _IIter, const _Tp &)
template<typename _InputIterator , typename _Tp >
_InputIterator find (_InputIterator __first, _InputIterator __last, const _Tp &__val)
template<typename _FIter1 , typename _FIter2 >
_FIter1 find_end (_FIter1, _FIter1, _FIter2, _FIter2)
template<typename _FIter1 , typename _FIter2 , typename _BinaryPredicate >
_FIter1 find_end (_FIter1, _FIter1, _FIter2, _FIter2, _BinaryPredicate)
template<typename _ForwardIterator1 , typename _ForwardIterator2 >
_ForwardIterator1 find_end (_ForwardIterator1 __first1, _ForwardIterator1 __last1, _ForwardIterator2 __first2, _ForwardIterator2 __last2)
template<typename _ForwardIterator1 , typename _ForwardIterator2 , typename _BinaryPredicate >
_ForwardIterator1 find_end (_ForwardIterator1 __first1, _ForwardIterator1 __last1, _ForwardIterator2 __first2, _ForwardIterator2 __last2, _BinaryPredicate __comp)
template<typename _FIter1 , typename _FIter2 >
_FIter1 find_first_of (_FIter1, _FIter1, _FIter2, _FIter2)
template<typename _FIter1 , typename _FIter2 , typename _BinaryPredicate >
_FIter1 find_first_of (_FIter1, _FIter1, _FIter2, _FIter2, _BinaryPredicate)
template<typename _InputIterator , typename _ForwardIterator >
_InputIterator find_first_of (_InputIterator __first1, _InputIterator __last1, _ForwardIterator __first2, _ForwardIterator __last2)
template<typename _InputIterator , typename _ForwardIterator , typename _BinaryPredicate >
_InputIterator find_first_of (_InputIterator __first1, _InputIterator __last1, _ForwardIterator __first2, _ForwardIterator __last2, _BinaryPredicate __comp)
template<typename _IIter , typename _Predicate >
_IIter find_if (_IIter, _IIter, _Predicate)
template<typename _InputIterator , typename _Predicate >
_InputIterator find_if (_InputIterator __first, _InputIterator __last, _Predicate __pred)
template<typename _IIter , typename _Predicate >
_IIter find_if_not (_IIter, _IIter, _Predicate)
template<typename _InputIterator , typename _Predicate >
_InputIterator find_if_not (_InputIterator __first, _InputIterator __last, _Predicate __pred)
ios_base & fixed (ios_base &__base)
template<typename _IIter , typename _Funct >
_Funct for_each (_IIter, _IIter, _Funct)
template<typename _InputIterator , typename _Function >
_Function for_each (_InputIterator __first, _InputIterator __last, _Function __f)
template<typename _Tp >
constexpr _Tp && forward (typename std::remove_reference< _Tp >::type &__t) noexcept
template<typename _Tp >
constexpr _Tp && forward (typename std::remove_reference< _Tp >::type &&__t) noexcept
template<typename _Container >
front_insert_iterator< _Container > front_inserter (_Container &__x)
template<typename _FIter , typename _Generator >
void generate (_FIter, _FIter, _Generator)
template<typename _ForwardIterator , typename _Generator >
void generate (_ForwardIterator __first, _ForwardIterator __last, _Generator __gen)
template<typename _RealType , size_t __bits, typename _UniformRandomNumberGenerator >
_RealType generate_canonical (_UniformRandomNumberGenerator &__g)
template<typename _OIter , typename _Size , typename _Generator >
_OIter generate_n (_OIter, _Size, _Generator)
template<typename _OutputIterator , typename _Size , typename _Generator >
_OutputIterator generate_n (_OutputIterator __first, _Size __n, _Generator __gen)
template<typename _Del , typename _Tp , _Lock_policy _Lp>
_Del * get_deleter (const __shared_ptr< _Tp, _Lp > &__p) noexcept
template<typename _Tp >
pair< _Tp *, ptrdiff_t > get_temporary_buffer (ptrdiff_t __len) noexcept
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base>
basic_istream< _CharT, _Traits > & getline (basic_istream< _CharT, _Traits > &__is, __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base > &__str, _CharT __delim)
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base>
basic_istream< _CharT, _Traits > & getline (basic_istream< _CharT, _Traits > &__is, __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base > &__str)
template<typename _CharT , typename _Traits , typename _Alloc >
basic_istream< _CharT, _Traits > & getline (basic_istream< _CharT, _Traits > &__is, basic_string< _CharT, _Traits, _Alloc > &__str, _CharT __delim)
template<typename _CharT , typename _Traits , typename _Alloc >
basic_istream< _CharT, _Traits > & getline (basic_istream< _CharT, _Traits > &__is, basic_string< _CharT, _Traits, _Alloc > &__str)
template<typename _CharT , typename _Traits , typename _Alloc >
basic_istream< _CharT, _Traits > & getline (basic_istream< _CharT, _Traits > &&__is, basic_string< _CharT, _Traits, _Alloc > &__str, _CharT __delim)
template<typename _CharT , typename _Traits , typename _Alloc >
basic_istream< _CharT, _Traits > & getline (basic_istream< _CharT, _Traits > &&__is, basic_string< _CharT, _Traits, _Alloc > &__str)
template<>
basic_istream< char > & getline (basic_istream< char > &__in, basic_string< char > &__str, char __delim)
template<>
basic_istream< wchar_t > & getline (basic_istream< wchar_t > &__in, basic_string< wchar_t > &__str, wchar_t __delim)
template<typename _Facet >
bool has_facet (const locale &) throw ()
ios_base & hex (ios_base &__base)
ios_base & hexfloat (ios_base &__base)
template<typename _IIter1 , typename _IIter2 >
bool includes (_IIter1, _IIter1, _IIter2, _IIter2)
template<typename _IIter1 , typename _IIter2 , typename _Compare >
bool includes (_IIter1, _IIter1, _IIter2, _IIter2, _Compare)
template<typename _InputIterator1 , typename _InputIterator2 >
bool includes (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2)
template<typename _InputIterator1 , typename _InputIterator2 , typename _Compare >
bool includes (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _Compare __comp)
template<typename _InputIterator1 , typename _InputIterator2 , typename _Tp >
_Tp inner_product (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _Tp __init)
template<typename _InputIterator1 , typename _InputIterator2 , typename _Tp , typename _BinaryOperation1 , typename _BinaryOperation2 >
_Tp inner_product (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _Tp __init, _BinaryOperation1 __binary_op1, _BinaryOperation2 __binary_op2)
template<typename _BIter >
void inplace_merge (_BIter, _BIter, _BIter)
template<typename _BIter , typename _Compare >
void inplace_merge (_BIter, _BIter, _BIter, _Compare)
template<typename _BidirectionalIterator >
void inplace_merge (_BidirectionalIterator __first, _BidirectionalIterator __middle, _BidirectionalIterator __last)
template<typename _BidirectionalIterator , typename _Compare >
void inplace_merge (_BidirectionalIterator __first, _BidirectionalIterator __middle, _BidirectionalIterator __last, _Compare __comp)
template<typename _Container , typename _Iterator >
insert_iterator< _Container > inserter (_Container &__x, _Iterator __i)
ios_base & internal (ios_base &__base)
const error_category & iostream_category () noexcept
template<typename _ForwardIterator , typename _Tp >
void iota (_ForwardIterator __first, _ForwardIterator __last, _Tp __value)
template<typename _RAIter >
bool is_heap (_RAIter, _RAIter)
template<typename _RAIter , typename _Compare >
bool is_heap (_RAIter, _RAIter, _Compare)
template<typename _RandomAccessIterator >
bool is_heap (_RandomAccessIterator __first, _RandomAccessIterator __last)
template<typename _RandomAccessIterator , typename _Compare >
bool is_heap (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _RAIter >
_RAIter is_heap_until (_RAIter, _RAIter)
template<typename _RAIter , typename _Compare >
_RAIter is_heap_until (_RAIter, _RAIter, _Compare)
template<typename _RandomAccessIterator >
_RandomAccessIterator is_heap_until (_RandomAccessIterator __first, _RandomAccessIterator __last)
template<typename _RandomAccessIterator , typename _Compare >
_RandomAccessIterator is_heap_until (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _IIter , typename _Predicate >
bool is_partitioned (_IIter, _IIter, _Predicate)
template<typename _InputIterator , typename _Predicate >
bool is_partitioned (_InputIterator __first, _InputIterator __last, _Predicate __pred)
template<typename _FIter1 , typename _FIter2 >
bool is_permutation (_FIter1, _FIter1, _FIter2)
template<typename _FIter1 , typename _FIter2 , typename _BinaryPredicate >
bool is_permutation (_FIter1, _FIter1, _FIter2, _BinaryPredicate)
template<typename _ForwardIterator1 , typename _ForwardIterator2 >
bool is_permutation (_ForwardIterator1 __first1, _ForwardIterator1 __last1, _ForwardIterator2 __first2)
template<typename _ForwardIterator1 , typename _ForwardIterator2 , typename _BinaryPredicate >
bool is_permutation (_ForwardIterator1 __first1, _ForwardIterator1 __last1, _ForwardIterator2 __first2, _BinaryPredicate __pred)
template<typename _FIter >
bool is_sorted (_FIter, _FIter)
template<typename _FIter , typename _Compare >
bool is_sorted (_FIter, _FIter, _Compare)
template<typename _ForwardIterator >
bool is_sorted (_ForwardIterator __first, _ForwardIterator __last)
template<typename _ForwardIterator , typename _Compare >
bool is_sorted (_ForwardIterator __first, _ForwardIterator __last, _Compare __comp)
template<typename _FIter >
_FIter is_sorted_until (_FIter, _FIter)
template<typename _FIter , typename _Compare >
_FIter is_sorted_until (_FIter, _FIter, _Compare)
template<typename _ForwardIterator >
_ForwardIterator is_sorted_until (_ForwardIterator __first, _ForwardIterator __last)
template<typename _ForwardIterator , typename _Compare >
_ForwardIterator is_sorted_until (_ForwardIterator __first, _ForwardIterator __last, _Compare __comp)
template<typename _CharT >
bool isalnum (_CharT __c, const locale &__loc)
template<typename _CharT >
bool isalpha (_CharT __c, const locale &__loc)
template<typename _CharT >
bool isblank (_CharT __c, const locale &__loc)
template<typename _CharT >
bool iscntrl (_CharT __c, const locale &__loc)
template<typename _CharT >
bool isdigit (_CharT __c, const locale &__loc)
template<typename _CharT >
bool isgraph (_CharT __c, const locale &__loc)
template<typename _CharT >
bool islower (_CharT __c, const locale &__loc)
template<typename _CharT >
bool isprint (_CharT __c, const locale &__loc)
template<typename _CharT >
bool ispunct (_CharT __c, const locale &__loc)
template<typename _CharT >
bool isspace (_CharT __c, const locale &__loc)
template<typename _CharT >
bool isupper (_CharT __c, const locale &__loc)
template<typename _CharT >
bool isxdigit (_CharT __c, const locale &__loc)
template<typename _ForwardIterator1 , typename _ForwardIterator2 >
void iter_swap (_ForwardIterator1 __a, _ForwardIterator2 __b)
template<typename _FIter1 , typename _FIter2 >
void iter_swap (_FIter1, _FIter2)
template<typename _Tp >
_Tp kill_dependency (_Tp __y) noexcept
ios_base & left (ios_base &__base)
template<typename _IIter1 , typename _IIter2 >
bool lexicographical_compare (_IIter1, _IIter1, _IIter2, _IIter2)
template<typename _IIter1 , typename _IIter2 , typename _Compare >
bool lexicographical_compare (_IIter1, _IIter1, _IIter2, _IIter2, _Compare)
template<typename _II1 , typename _II2 >
bool lexicographical_compare (_II1 __first1, _II1 __last1, _II2 __first2, _II2 __last2)
template<typename _II1 , typename _II2 , typename _Compare >
bool lexicographical_compare (_II1 __first1, _II1 __last1, _II2 __first2, _II2 __last2, _Compare __comp)
template<class _Dom >
_Expr< _UnClos< _Log, _Expr, _Dom >, typename _Dom::value_type > log (const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp >
_Expr< _UnClos< _Log, _ValArray, _Tp >, _Tp > log (const valarray< _Tp > &__v)
template<class _Dom >
_Expr< _UnClos< _Log10, _Expr, _Dom >, typename _Dom::value_type > log10 (const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp >
_Expr< _UnClos< _Log10, _ValArray, _Tp >, _Tp > log10 (const valarray< _Tp > &__v)
template<typename _FIter , typename _Tp >
_FIter lower_bound (_FIter, _FIter, const _Tp &)
template<typename _FIter , typename _Tp , typename _Compare >
_FIter lower_bound (_FIter, _FIter, const _Tp &, _Compare)
template<typename _ForwardIterator , typename _Tp >
_ForwardIterator lower_bound (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__val)
template<typename _ForwardIterator , typename _Tp , typename _Compare >
_ForwardIterator lower_bound (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__val, _Compare __comp)
error_code make_error_code (io_errc e) noexcept
error_condition make_error_condition (io_errc e) noexcept
template<typename _Ex >
exception_ptr make_exception_ptr (_Ex __ex) noexcept
template<typename _RAIter >
void make_heap (_RAIter, _RAIter)
template<typename _RandomAccessIterator >
void make_heap (_RandomAccessIterator __first, _RandomAccessIterator __last)
template<typename _RAIter , typename _Compare >
void make_heap (_RAIter, _RAIter, _Compare)
template<typename _RandomAccessIterator , typename _Compare >
void make_heap (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _Iterator >
move_iterator< _Iterator > make_move_iterator (_Iterator __i)
template<class _T1 , class _T2 >
constexpr pair< typename __decay_and_strip< _T1 >::__type, typename __decay_and_strip< _T2 >::__type > make_pair (_T1 &&__x, _T2 &&__y)
template<typename _Tp , typename... _Args>
shared_ptr< _Tp > make_shared (_Args &&...__args)
template<typename _Tp >
_GLIBCXX14_CONSTEXPR const _Tp & max (const _Tp &__a, const _Tp &__b)
template<typename _Tp , typename _Compare >
_GLIBCXX14_CONSTEXPR const _Tp & max (const _Tp &__a, const _Tp &__b, _Compare __comp)
template<typename _Tp >
_GLIBCXX14_CONSTEXPR _Tp max (initializer_list< _Tp >)
template<typename _Tp , typename _Compare >
_GLIBCXX14_CONSTEXPR _Tp max (initializer_list< _Tp >, _Compare)
template<typename _FIter >
_GLIBCXX14_CONSTEXPR _FIter max_element (_FIter, _FIter)
template<typename _FIter , typename _Compare >
_GLIBCXX14_CONSTEXPR _FIter max_element (_FIter, _FIter, _Compare)
template<typename _ForwardIterator >
_GLIBCXX14_CONSTEXPR _ForwardIterator max_element (_ForwardIterator __first, _ForwardIterator __last)
template<typename _ForwardIterator , typename _Compare >
_GLIBCXX14_CONSTEXPR _ForwardIterator max_element (_ForwardIterator __first, _ForwardIterator __last, _Compare __comp)
template<typename _Ret , typename _Tp >
mem_fun_t< _Ret, _Tp > mem_fun (_Ret(_Tp::*__f)())
template<typename _Ret , typename _Tp >
const_mem_fun_t< _Ret, _Tp > mem_fun (_Ret(_Tp::*__f)() const)
template<typename _Ret , typename _Tp , typename _Arg >
mem_fun1_t< _Ret, _Tp, _Arg > mem_fun (_Ret(_Tp::*__f)(_Arg))
template<typename _Ret , typename _Tp , typename _Arg >
const_mem_fun1_t< _Ret, _Tp, _Arg > mem_fun (_Ret(_Tp::*__f)(_Arg) const)
template<typename _Ret , typename _Tp >
mem_fun_ref_t< _Ret, _Tp > mem_fun_ref (_Ret(_Tp::*__f)())
template<typename _Ret , typename _Tp >
const_mem_fun_ref_t< _Ret, _Tp > mem_fun_ref (_Ret(_Tp::*__f)() const)
template<typename _Ret , typename _Tp , typename _Arg >
mem_fun1_ref_t< _Ret, _Tp, _Arg > mem_fun_ref (_Ret(_Tp::*__f)(_Arg))
template<typename _Ret , typename _Tp , typename _Arg >
const_mem_fun1_ref_t< _Ret, _Tp, _Arg > mem_fun_ref (_Ret(_Tp::*__f)(_Arg) const)
template<typename _IIter1 , typename _IIter2 , typename _OIter >
_OIter merge (_IIter1, _IIter1, _IIter2, _IIter2, _OIter)
template<typename _IIter1 , typename _IIter2 , typename _OIter , typename _Compare >
_OIter merge (_IIter1, _IIter1, _IIter2, _IIter2, _OIter, _Compare)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator >
_OutputIterator merge (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator , typename _Compare >
_OutputIterator merge (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result, _Compare __comp)
template<typename _Tp >
_GLIBCXX14_CONSTEXPR const _Tp & min (const _Tp &__a, const _Tp &__b)
template<typename _Tp , typename _Compare >
_GLIBCXX14_CONSTEXPR const _Tp & min (const _Tp &__a, const _Tp &__b, _Compare __comp)
template<typename _Tp >
_GLIBCXX14_CONSTEXPR _Tp min (initializer_list< _Tp >)
template<typename _Tp , typename _Compare >
_GLIBCXX14_CONSTEXPR _Tp min (initializer_list< _Tp >, _Compare)
template<typename _FIter >
_GLIBCXX14_CONSTEXPR _FIter min_element (_FIter, _FIter)
template<typename _FIter , typename _Compare >
_GLIBCXX14_CONSTEXPR _FIter min_element (_FIter, _FIter, _Compare)
template<typename _ForwardIterator >
_GLIBCXX14_CONSTEXPR _ForwardIterator min_element (_ForwardIterator __first, _ForwardIterator __last)
template<typename _ForwardIterator , typename _Compare >
_GLIBCXX14_CONSTEXPR _ForwardIterator min_element (_ForwardIterator __first, _ForwardIterator __last, _Compare __comp)
template<typename _Tp >
_GLIBCXX14_CONSTEXPR pair< const _Tp &, const _Tp & > minmax (const _Tp &__a, const _Tp &__b)
template<typename _Tp , typename _Compare >
_GLIBCXX14_CONSTEXPR pair< const _Tp &, const _Tp & > minmax (const _Tp &__a, const _Tp &__b, _Compare __comp)
template<typename _Tp >
_GLIBCXX14_CONSTEXPR pair< _Tp, _Tp > minmax (initializer_list< _Tp >)
template<typename _Tp , typename _Compare >
_GLIBCXX14_CONSTEXPR pair< _Tp, _Tp > minmax (initializer_list< _Tp >, _Compare)
template<typename _FIter >
_GLIBCXX14_CONSTEXPR pair< _FIter, _FIter > minmax_element (_FIter, _FIter)
template<typename _FIter , typename _Compare >
_GLIBCXX14_CONSTEXPR pair< _FIter, _FIter > minmax_element (_FIter, _FIter, _Compare)
template<typename _ForwardIterator >
_GLIBCXX14_CONSTEXPR pair< _ForwardIterator, _ForwardIterator > minmax_element (_ForwardIterator __first, _ForwardIterator __last)
template<typename _ForwardIterator , typename _Compare >
_GLIBCXX14_CONSTEXPR pair< _ForwardIterator, _ForwardIterator > minmax_element (_ForwardIterator __first, _ForwardIterator __last, _Compare __comp)
template<typename _IIter1 , typename _IIter2 >
pair< _IIter1, _IIter2 > mismatch (_IIter1, _IIter1, _IIter2)
template<typename _IIter1 , typename _IIter2 , typename _BinaryPredicate >
pair< _IIter1, _IIter2 > mismatch (_IIter1, _IIter1, _IIter2, _BinaryPredicate)
template<typename _InputIterator1 , typename _InputIterator2 >
pair< _InputIterator1, _InputIterator2 > mismatch (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2)
template<typename _InputIterator1 , typename _InputIterator2 , typename _BinaryPredicate >
pair< _InputIterator1, _InputIterator2 > mismatch (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _BinaryPredicate __binary_pred)
template<typename _Tp >
constexpr std::remove_reference< _Tp >::type && move (_Tp &&__t) noexcept
template<typename _Tp >
_Deque_iterator< _Tp, _Tp &, _Tp * > move (_Deque_iterator< _Tp, const _Tp &, const _Tp * >, _Deque_iterator< _Tp, const _Tp &, const _Tp * >, _Deque_iterator< _Tp, _Tp &, _Tp * >)
template<typename _Tp >
_Deque_iterator< _Tp, _Tp &, _Tp * > move (_Deque_iterator< _Tp, _Tp &, _Tp * > __first, _Deque_iterator< _Tp, _Tp &, _Tp * > __last, _Deque_iterator< _Tp, _Tp &, _Tp * > __result)
template<typename _II , typename _OI >
_OI move (_II __first, _II __last, _OI __result)
template<typename _Tp >
_Deque_iterator< _Tp, _Tp &, _Tp * > move_backward (_Deque_iterator< _Tp, const _Tp &, const _Tp * >, _Deque_iterator< _Tp, const _Tp &, const _Tp * >, _Deque_iterator< _Tp, _Tp &, _Tp * >)
template<typename _Tp >
_Deque_iterator< _Tp, _Tp &, _Tp * > move_backward (_Deque_iterator< _Tp, _Tp &, _Tp * > __first, _Deque_iterator< _Tp, _Tp &, _Tp * > __last, _Deque_iterator< _Tp, _Tp &, _Tp * > __result)
template<typename _BI1 , typename _BI2 >
_BI2 move_backward (_BI1 __first, _BI1 __last, _BI2 __result)
template<typename _Tp >
constexpr conditional< __move_if_noexcept_cond< _Tp >::value, const _Tp &, _Tp && >::type move_if_noexcept (_Tp &__x) noexcept
template<typename _ForwardIterator >
_ForwardIterator next (_ForwardIterator __x, typename iterator_traits< _ForwardIterator >::difference_type __n=1)
template<typename _BIter >
bool next_permutation (_BIter, _BIter)
template<typename _BIter , typename _Compare >
bool next_permutation (_BIter, _BIter, _Compare)
template<typename _BidirectionalIterator >
bool next_permutation (_BidirectionalIterator __first, _BidirectionalIterator __last)
template<typename _BidirectionalIterator , typename _Compare >
bool next_permutation (_BidirectionalIterator __first, _BidirectionalIterator __last, _Compare __comp)
ios_base & noboolalpha (ios_base &__base)
template<typename _IIter , typename _Predicate >
bool none_of (_IIter, _IIter, _Predicate)
template<typename _InputIterator , typename _Predicate >
bool none_of (_InputIterator __first, _InputIterator __last, _Predicate __pred)
ios_base & noshowbase (ios_base &__base)
ios_base & noshowpoint (ios_base &__base)
ios_base & noshowpos (ios_base &__base)
ios_base & noskipws (ios_base &__base)
template<typename _Predicate >
_GLIBCXX14_CONSTEXPR unary_negate< _Predicate > not1 (const _Predicate &__pred)
template<typename _Predicate >
_GLIBCXX14_CONSTEXPR binary_negate< _Predicate > not2 (const _Predicate &__pred)
ios_base & nounitbuf (ios_base &__base)
ios_base & nouppercase (ios_base &__base)
template<typename _RAIter >
void nth_element (_RAIter, _RAIter, _RAIter)
template<typename _RAIter , typename _Compare >
void nth_element (_RAIter, _RAIter, _RAIter, _Compare)
template<typename _RandomAccessIterator >
void nth_element (_RandomAccessIterator __first, _RandomAccessIterator __nth, _RandomAccessIterator __last)
template<typename _RandomAccessIterator , typename _Compare >
void nth_element (_RandomAccessIterator __first, _RandomAccessIterator __nth, _RandomAccessIterator __last, _Compare __comp)
ios_base & oct (ios_base &__base)
template<class _Tp , class _CharT , class _Traits , class _Dist >
bool operator!= (const istream_iterator< _Tp, _CharT, _Traits, _Dist > &__x, const istream_iterator< _Tp, _CharT, _Traits, _Dist > &__y)
template<typename _T1 , typename _T2 >
bool operator!= (const allocator< _T1 > &, const allocator< _T2 > &) noexcept
template<typename _Tp >
bool operator!= (const allocator< _Tp > &, const allocator< _Tp > &) noexcept
template<typename _CharT , typename _Traits >
bool operator!= (const istreambuf_iterator< _CharT, _Traits > &__a, const istreambuf_iterator< _CharT, _Traits > &__b)
template<typename _StateT >
bool operator!= (const fpos< _StateT > &__lhs, const fpos< _StateT > &__rhs)
template<class _T1 , class _T2 >
constexpr bool operator!= (const pair< _T1, _T2 > &__x, const pair< _T1, _T2 > &__y)
template<typename _Tp >
bool operator!= (const _Fwd_list_iterator< _Tp > &__x, const _Fwd_list_const_iterator< _Tp > &__y) noexcept
template<typename _Tp , typename _Seq >
bool operator!= (const stack< _Tp, _Seq > &__x, const stack< _Tp, _Seq > &__y)
template<typename _Tp , typename _Ref , typename _Ptr >
bool operator!= (const _Deque_iterator< _Tp, _Ref, _Ptr > &__x, const _Deque_iterator< _Tp, _Ref, _Ptr > &__y) noexcept
template<typename _Tp , typename _RefL , typename _PtrL , typename _RefR , typename _PtrR >
bool operator!= (const _Deque_iterator< _Tp, _RefL, _PtrL > &__x, const _Deque_iterator< _Tp, _RefR, _PtrR > &__y) noexcept
template<typename _Val >
bool operator!= (const _List_iterator< _Val > &__x, const _List_const_iterator< _Val > &__y) noexcept
template<typename _Tp , typename _Seq >
bool operator!= (const queue< _Tp, _Seq > &__x, const queue< _Tp, _Seq > &__y)
template<typename _Iterator >
bool operator!= (const reverse_iterator< _Iterator > &__x, const reverse_iterator< _Iterator > &__y)
template<typename _Val >
bool operator!= (const _Rb_tree_iterator< _Val > &__x, const _Rb_tree_const_iterator< _Val > &__y) noexcept
template<typename _Tp1 , typename _Tp2 >
bool operator!= (const shared_ptr< _Tp1 > &__a, const shared_ptr< _Tp2 > &__b) noexcept
template<typename _IteratorL , typename _IteratorR >
bool operator!= (const reverse_iterator< _IteratorL > &__x, const reverse_iterator< _IteratorR > &__y)
template<typename _Tp >
bool operator!= (const shared_ptr< _Tp > &__a, nullptr_t) noexcept
template<typename _Tp >
bool operator!= (nullptr_t, const shared_ptr< _Tp > &__a) noexcept
template<typename _UIntType , _UIntType __a, _UIntType __c, _UIntType __m>
bool operator!= (const std::linear_congruential_engine< _UIntType, __a, __c, __m > &__lhs, const std::linear_congruential_engine< _UIntType, __a, __c, __m > &__rhs)
template<class _Dom1 , class _Dom2 >
_Expr< _BinClos< __not_equal_to, _Expr, _Expr, _Dom1, _Dom2 >, typename __fun< __not_equal_to, typename _Dom1::value_type >::result_type > operator!= (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<class _Dom >
_Expr< _BinClos< __not_equal_to, _Expr, _Constant, _Dom, typename _Dom::value_type >, typename __fun< __not_equal_to, typename _Dom::value_type >::result_type > operator!= (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom >
_Expr< _BinClos< __not_equal_to, _Expr, _ValArray, _Dom, typename _Dom::value_type >, typename __fun< __not_equal_to, typename _Dom::value_type >::result_type > operator!= (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom >
_Expr< _BinClos< __not_equal_to, _ValArray, _Expr, typename _Dom::value_type, _Dom >, typename __fun< __not_equal_to, typename _Dom::value_type >::result_type > operator!= (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<class _Dom >
_Expr< _BinClos< __not_equal_to, _Constant, _Expr, typename _Dom::value_type, _Dom >, typename __fun< __not_equal_to, typename _Dom::value_type >::result_type > operator!= (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<typename _Tp , typename _Dp , typename _Up , typename _Ep >
bool operator!= (const unique_ptr< _Tp, _Dp > &__x, const unique_ptr< _Up, _Ep > &__y)
template<typename _UIntType , size_t __w, size_t __n, size_t __m, size_t __r, _UIntType __a, size_t __u, _UIntType __d, size_t __s, _UIntType __b, size_t __t, _UIntType __c, size_t __l, _UIntType __f>
bool operator!= (const std::mersenne_twister_engine< _UIntType, __w, __n, __m, __r, __a, __u, __d, __s, __b, __t, __c, __l, __f > &__lhs, const std::mersenne_twister_engine< _UIntType, __w, __n, __m, __r, __a, __u, __d, __s, __b, __t, __c, __l, __f > &__rhs)
template<typename _Tp , typename _Dp >
bool operator!= (const unique_ptr< _Tp, _Dp > &__x, nullptr_t) noexcept
template<typename _Tp , typename _Dp >
bool operator!= (nullptr_t, const unique_ptr< _Tp, _Dp > &__x) noexcept
template<typename _UIntType , size_t __w, size_t __s, size_t __r>
bool operator!= (const std::subtract_with_carry_engine< _UIntType, __w, __s, __r > &__lhs, const std::subtract_with_carry_engine< _UIntType, __w, __s, __r > &__rhs)
template<typename _Key , typename _Compare , typename _Alloc >
bool operator!= (const multiset< _Key, _Compare, _Alloc > &__x, const multiset< _Key, _Compare, _Alloc > &__y)
template<typename _Key , typename _Compare , typename _Alloc >
bool operator!= (const set< _Key, _Compare, _Alloc > &__x, const set< _Key, _Compare, _Alloc > &__y)
template<typename _BiIter >
bool operator!= (const sub_match< _BiIter > &__lhs, const sub_match< _BiIter > &__rhs)
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc >
bool operator!= (const multimap< _Key, _Tp, _Compare, _Alloc > &__x, const multimap< _Key, _Tp, _Compare, _Alloc > &__y)
template<typename _Bi_iter , typename _Ch_traits , typename _Ch_alloc >
bool operator!= (const __sub_match_string< _Bi_iter, _Ch_traits, _Ch_alloc > &__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _RandomNumberEngine , size_t __p, size_t __r>
bool operator!= (const std::discard_block_engine< _RandomNumberEngine, __p, __r > &__lhs, const std::discard_block_engine< _RandomNumberEngine, __p, __r > &__rhs)
template<typename _IteratorL , typename _IteratorR >
bool operator!= (const move_iterator< _IteratorL > &__x, const move_iterator< _IteratorR > &__y)
template<typename _Iterator >
bool operator!= (const move_iterator< _Iterator > &__x, const move_iterator< _Iterator > &__y)
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc >
bool operator!= (const map< _Key, _Tp, _Compare, _Alloc > &__x, const map< _Key, _Tp, _Compare, _Alloc > &__y)
template<typename _Bi_iter , typename _Ch_traits , typename _Ch_alloc >
bool operator!= (const sub_match< _Bi_iter > &__lhs, const __sub_match_string< _Bi_iter, _Ch_traits, _Ch_alloc > &__rhs)
template<typename _Bi_iter >
bool operator!= (typename iterator_traits< _Bi_iter >::value_type const *__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Tp1 , typename _Tp2 , _Lock_policy _Lp>
bool operator!= (const __shared_ptr< _Tp1, _Lp > &__a, const __shared_ptr< _Tp2, _Lp > &__b) noexcept
template<typename _Tp , _Lock_policy _Lp>
bool operator!= (const __shared_ptr< _Tp, _Lp > &__a, nullptr_t) noexcept
template<typename _Tp , _Lock_policy _Lp>
bool operator!= (nullptr_t, const __shared_ptr< _Tp, _Lp > &__a) noexcept
template<typename _RandomNumberEngine , size_t __w, typename _UIntType >
bool operator!= (const std::independent_bits_engine< _RandomNumberEngine, __w, _UIntType > &__lhs, const std::independent_bits_engine< _RandomNumberEngine, __w, _UIntType > &__rhs)
template<typename _Bi_iter >
bool operator!= (const sub_match< _Bi_iter > &__lhs, typename iterator_traits< _Bi_iter >::value_type const *__rhs)
template<typename _Key , typename _Val , typename _KeyOfValue , typename _Compare , typename _Alloc >
bool operator!= (const _Rb_tree< _Key, _Val, _KeyOfValue, _Compare, _Alloc > &__x, const _Rb_tree< _Key, _Val, _KeyOfValue, _Compare, _Alloc > &__y)
template<typename _Bi_iter >
bool operator!= (typename iterator_traits< _Bi_iter >::value_type const &__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Tp , typename _Alloc >
bool operator!= (const forward_list< _Tp, _Alloc > &__lx, const forward_list< _Tp, _Alloc > &__ly)
template<typename _Bi_iter >
bool operator!= (const sub_match< _Bi_iter > &__lhs, typename iterator_traits< _Bi_iter >::value_type const &__rhs)
template<class _Value , class _Hash , class _Pred , class _Alloc >
bool operator!= (const unordered_set< _Value, _Hash, _Pred, _Alloc > &__x, const unordered_set< _Value, _Hash, _Pred, _Alloc > &__y)
template<class _Value , class _Hash , class _Pred , class _Alloc >
bool operator!= (const unordered_multiset< _Value, _Hash, _Pred, _Alloc > &__x, const unordered_multiset< _Value, _Hash, _Pred, _Alloc > &__y)
template<typename _RandomNumberEngine , size_t __k>
bool operator!= (const std::shuffle_order_engine< _RandomNumberEngine, __k > &__lhs, const std::shuffle_order_engine< _RandomNumberEngine, __k > &__rhs)
template<typename _Tp , typename _Alloc >
bool operator!= (const vector< _Tp, _Alloc > &__x, const vector< _Tp, _Alloc > &__y)
template<class _Key , class _Tp , class _Hash , class _Pred , class _Alloc >
bool operator!= (const unordered_map< _Key, _Tp, _Hash, _Pred, _Alloc > &__x, const unordered_map< _Key, _Tp, _Hash, _Pred, _Alloc > &__y)
template<class _Key , class _Tp , class _Hash , class _Pred , class _Alloc >
bool operator!= (const unordered_multimap< _Key, _Tp, _Hash, _Pred, _Alloc > &__x, const unordered_multimap< _Key, _Tp, _Hash, _Pred, _Alloc > &__y)
template<typename _IntType >
bool operator!= (const std::uniform_int_distribution< _IntType > &__d1, const std::uniform_int_distribution< _IntType > &__d2)
template<typename _Tp , typename _Alloc >
bool operator!= (const list< _Tp, _Alloc > &__x, const list< _Tp, _Alloc > &__y)
template<typename _Bi_iter , class _Alloc >
bool operator!= (const match_results< _Bi_iter, _Alloc > &__m1, const match_results< _Bi_iter, _Alloc > &__m2)
template<typename _IntType >
bool operator!= (const std::uniform_real_distribution< _IntType > &__d1, const std::uniform_real_distribution< _IntType > &__d2)
template<typename _Tp , typename _Alloc >
bool operator!= (const deque< _Tp, _Alloc > &__x, const deque< _Tp, _Alloc > &__y)
template<typename _RealType >
bool operator!= (const std::normal_distribution< _RealType > &__d1, const std::normal_distribution< _RealType > &__d2)
template<typename _RealType >
bool operator!= (const std::lognormal_distribution< _RealType > &__d1, const std::lognormal_distribution< _RealType > &__d2)
template<typename _RealType >
bool operator!= (const std::gamma_distribution< _RealType > &__d1, const std::gamma_distribution< _RealType > &__d2)
template<typename _RealType >
bool operator!= (const std::chi_squared_distribution< _RealType > &__d1, const std::chi_squared_distribution< _RealType > &__d2)
template<typename _RealType >
bool operator!= (const std::cauchy_distribution< _RealType > &__d1, const std::cauchy_distribution< _RealType > &__d2)
template<typename _RealType >
bool operator!= (const std::fisher_f_distribution< _RealType > &__d1, const std::fisher_f_distribution< _RealType > &__d2)
template<typename _RealType >
bool operator!= (const std::student_t_distribution< _RealType > &__d1, const std::student_t_distribution< _RealType > &__d2)
bool operator!= (const std::bernoulli_distribution &__d1, const std::bernoulli_distribution &__d2)
template<typename _IntType >
bool operator!= (const std::binomial_distribution< _IntType > &__d1, const std::binomial_distribution< _IntType > &__d2)
template<typename _IntType >
bool operator!= (const std::geometric_distribution< _IntType > &__d1, const std::geometric_distribution< _IntType > &__d2)
template<typename _IntType >
bool operator!= (const std::negative_binomial_distribution< _IntType > &__d1, const std::negative_binomial_distribution< _IntType > &__d2)
template<typename _IntType >
bool operator!= (const std::poisson_distribution< _IntType > &__d1, const std::poisson_distribution< _IntType > &__d2)
template<typename _RealType >
bool operator!= (const std::exponential_distribution< _RealType > &__d1, const std::exponential_distribution< _RealType > &__d2)
template<typename _CharT , typename _Traits , typename _Alloc >
bool operator!= (const basic_string< _CharT, _Traits, _Alloc > &__lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs)
template<typename _CharT , typename _Traits , typename _Alloc >
bool operator!= (const _CharT *__lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs)
template<typename _CharT , typename _Traits , typename _Alloc >
bool operator!= (const basic_string< _CharT, _Traits, _Alloc > &__lhs, const _CharT *__rhs)
template<typename _RealType >
bool operator!= (const std::weibull_distribution< _RealType > &__d1, const std::weibull_distribution< _RealType > &__d2)
template<typename _RealType >
bool operator!= (const std::extreme_value_distribution< _RealType > &__d1, const std::extreme_value_distribution< _RealType > &__d2)
template<typename _IntType >
bool operator!= (const std::discrete_distribution< _IntType > &__d1, const std::discrete_distribution< _IntType > &__d2)
template<typename _RealType >
bool operator!= (const std::piecewise_constant_distribution< _RealType > &__d1, const std::piecewise_constant_distribution< _RealType > &__d2)
template<typename _RealType >
bool operator!= (const std::piecewise_linear_distribution< _RealType > &__d1, const std::piecewise_linear_distribution< _RealType > &__d2)
template<class _Dom >
_Expr< _BinClos< __modulus, _Expr, _Constant, _Dom, typename _Dom::value_type >, typename __fun< __modulus, typename _Dom::value_type >::result_type > operator% (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom >
_Expr< _BinClos< __modulus, _Expr, _ValArray, _Dom, typename _Dom::value_type >, typename __fun< __modulus, typename _Dom::value_type >::result_type > operator% (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom1 , class _Dom2 >
_Expr< _BinClos< __modulus, _Expr, _Expr, _Dom1, _Dom2 >, typename __fun< __modulus, typename _Dom1::value_type >::result_type > operator% (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<class _Dom >
_Expr< _BinClos< __modulus, _Constant, _Expr, typename _Dom::value_type, _Dom >, typename __fun< __modulus, typename _Dom::value_type >::result_type > operator% (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<class _Dom >
_Expr< _BinClos< __modulus, _ValArray, _Expr, typename _Dom::value_type, _Dom >, typename __fun< __modulus, typename _Dom::value_type >::result_type > operator% (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
constexpr memory_order operator& (memory_order __m, __memory_order_modifier __mod)
constexpr _Ios_Fmtflags operator& (_Ios_Fmtflags __a, _Ios_Fmtflags __b)
constexpr _Ios_Openmode operator& (_Ios_Openmode __a, _Ios_Openmode __b)
constexpr _Ios_Iostate operator& (_Ios_Iostate __a, _Ios_Iostate __b)
template<class _Dom1 , class _Dom2 >
_Expr< _BinClos< __bitwise_and, _Expr, _Expr, _Dom1, _Dom2 >, typename __fun< __bitwise_and, typename _Dom1::value_type >::result_type > operator& (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<class _Dom >
_Expr< _BinClos< __bitwise_and, _Expr, _Constant, _Dom, typename _Dom::value_type >, typename __fun< __bitwise_and, typename _Dom::value_type >::result_type > operator& (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom >
_Expr< _BinClos< __bitwise_and, _Constant, _Expr, typename _Dom::value_type, _Dom >, typename __fun< __bitwise_and, typename _Dom::value_type >::result_type > operator& (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<class _Dom >
_Expr< _BinClos< __bitwise_and, _Expr, _ValArray, _Dom, typename _Dom::value_type >, typename __fun< __bitwise_and, typename _Dom::value_type >::result_type > operator& (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom >
_Expr< _BinClos< __bitwise_and, _ValArray, _Expr, typename _Dom::value_type, _Dom >, typename __fun< __bitwise_and, typename _Dom::value_type >::result_type > operator& (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<class _Dom >
_Expr< _BinClos< __logical_and, _Expr, _Constant, _Dom, typename _Dom::value_type >, typename __fun< __logical_and, typename _Dom::value_type >::result_type > operator&& (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom1 , class _Dom2 >
_Expr< _BinClos< __logical_and, _Expr, _Expr, _Dom1, _Dom2 >, typename __fun< __logical_and, typename _Dom1::value_type >::result_type > operator&& (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<class _Dom >
_Expr< _BinClos< __logical_and, _Constant, _Expr, typename _Dom::value_type, _Dom >, typename __fun< __logical_and, typename _Dom::value_type >::result_type > operator&& (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<class _Dom >
_Expr< _BinClos< __logical_and, _Expr, _ValArray, _Dom, typename _Dom::value_type >, typename __fun< __logical_and, typename _Dom::value_type >::result_type > operator&& (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom >
_Expr< _BinClos< __logical_and, _ValArray, _Expr, typename _Dom::value_type, _Dom >, typename __fun< __logical_and, typename _Dom::value_type >::result_type > operator&& (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
const _Ios_Fmtflags & operator&= (_Ios_Fmtflags &__a, _Ios_Fmtflags __b)
const _Ios_Openmode & operator&= (_Ios_Openmode &__a, _Ios_Openmode __b)
const _Ios_Iostate & operator&= (_Ios_Iostate &__a, _Ios_Iostate __b)
template<class _Dom >
_Expr< _BinClos< __multiplies, _Expr, _ValArray, _Dom, typename _Dom::value_type >, typename __fun< __multiplies, typename _Dom::value_type >::result_type > operator* (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom >
_Expr< _BinClos< __multiplies, _Expr, _Constant, _Dom, typename _Dom::value_type >, typename __fun< __multiplies, typename _Dom::value_type >::result_type > operator* (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom1 , class _Dom2 >
_Expr< _BinClos< __multiplies, _Expr, _Expr, _Dom1, _Dom2 >, typename __fun< __multiplies, typename _Dom1::value_type >::result_type > operator* (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<class _Dom >
_Expr< _BinClos< __multiplies, _Constant, _Expr, typename _Dom::value_type, _Dom >, typename __fun< __multiplies, typename _Dom::value_type >::result_type > operator* (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<class _Dom >
_Expr< _BinClos< __multiplies, _ValArray, _Expr, typename _Dom::value_type, _Dom >, typename __fun< __multiplies, typename _Dom::value_type >::result_type > operator* (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
_Bit_iterator operator+ (ptrdiff_t __n, const _Bit_iterator &__x)
template<typename _Iterator >
reverse_iterator< _Iterator > operator+ (typename reverse_iterator< _Iterator >::difference_type __n, const reverse_iterator< _Iterator > &__x)
template<typename _Tp , typename _Ref , typename _Ptr >
_Deque_iterator< _Tp, _Ref, _Ptr > operator+ (ptrdiff_t __n, const _Deque_iterator< _Tp, _Ref, _Ptr > &__x) noexcept
_Bit_const_iterator operator+ (ptrdiff_t __n, const _Bit_const_iterator &__x)
template<class _Dom >
_Expr< _BinClos< __plus, _Expr, _ValArray, _Dom, typename _Dom::value_type >, typename __fun< __plus, typename _Dom::value_type >::result_type > operator+ (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom1 , class _Dom2 >
_Expr< _BinClos< __plus, _Expr, _Expr, _Dom1, _Dom2 >, typename __fun< __plus, typename _Dom1::value_type >::result_type > operator+ (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<class _Dom >
_Expr< _BinClos< __plus, _Expr, _Constant, _Dom, typename _Dom::value_type >, typename __fun< __plus, typename _Dom::value_type >::result_type > operator+ (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom >
_Expr< _BinClos< __plus, _Constant, _Expr, typename _Dom::value_type, _Dom >, typename __fun< __plus, typename _Dom::value_type >::result_type > operator+ (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<class _Dom >
_Expr< _BinClos< __plus, _ValArray, _Expr, typename _Dom::value_type, _Dom >, typename __fun< __plus, typename _Dom::value_type >::result_type > operator+ (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Iterator >
move_iterator< _Iterator > operator+ (typename move_iterator< _Iterator >::difference_type __n, const move_iterator< _Iterator > &__x)
template<typename _CharT , typename _Traits , typename _Alloc >
basic_string< _CharT, _Traits, _Alloc > operator+ (const basic_string< _CharT, _Traits, _Alloc > &__lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs)
template<typename _CharT , typename _Traits , typename _Alloc >
basic_string< _CharT, _Traits, _Alloc > operator+ (const _CharT *__lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs)
template<typename _CharT , typename _Traits , typename _Alloc >
basic_string< _CharT, _Traits, _Alloc > operator+ (_CharT __lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs)
template<typename _CharT , typename _Traits , typename _Alloc >
basic_string< _CharT, _Traits, _Alloc > operator+ (const basic_string< _CharT, _Traits, _Alloc > &__lhs, const _CharT *__rhs)
template<typename _CharT , typename _Traits , typename _Alloc >
basic_string< _CharT, _Traits, _Alloc > operator+ (const basic_string< _CharT, _Traits, _Alloc > &__lhs, _CharT __rhs)
template<typename _CharT , typename _Traits , typename _Alloc >
basic_string< _CharT, _Traits, _Alloc > operator+ (basic_string< _CharT, _Traits, _Alloc > &&__lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs)
template<typename _CharT , typename _Traits , typename _Alloc >
basic_string< _CharT, _Traits, _Alloc > operator+ (const basic_string< _CharT, _Traits, _Alloc > &__lhs, basic_string< _CharT, _Traits, _Alloc > &&__rhs)
template<typename _CharT , typename _Traits , typename _Alloc >
basic_string< _CharT, _Traits, _Alloc > operator+ (basic_string< _CharT, _Traits, _Alloc > &&__lhs, basic_string< _CharT, _Traits, _Alloc > &&__rhs)
template<typename _CharT , typename _Traits , typename _Alloc >
basic_string< _CharT, _Traits, _Alloc > operator+ (const _CharT *__lhs, basic_string< _CharT, _Traits, _Alloc > &&__rhs)
template<typename _CharT , typename _Traits , typename _Alloc >
basic_string< _CharT, _Traits, _Alloc > operator+ (_CharT __lhs, basic_string< _CharT, _Traits, _Alloc > &&__rhs)
template<typename _CharT , typename _Traits , typename _Alloc >
basic_string< _CharT, _Traits, _Alloc > operator+ (basic_string< _CharT, _Traits, _Alloc > &&__lhs, const _CharT *__rhs)
template<typename _CharT , typename _Traits , typename _Alloc >
basic_string< _CharT, _Traits, _Alloc > operator+ (basic_string< _CharT, _Traits, _Alloc > &&__lhs, _CharT __rhs)
ptrdiff_t operator- (const _Bit_iterator_base &__x, const _Bit_iterator_base &__y)
template<typename _Iterator >
reverse_iterator< _Iterator >::difference_type operator- (const reverse_iterator< _Iterator > &__x, const reverse_iterator< _Iterator > &__y)
template<typename _Tp , typename _Ref , typename _Ptr >
_Deque_iterator< _Tp, _Ref, _Ptr >::difference_type operator- (const _Deque_iterator< _Tp, _Ref, _Ptr > &__x, const _Deque_iterator< _Tp, _Ref, _Ptr > &__y) noexcept
template<typename _Tp , typename _RefL , typename _PtrL , typename _RefR , typename _PtrR >
_Deque_iterator< _Tp, _RefL, _PtrL >::difference_type operator- (const _Deque_iterator< _Tp, _RefL, _PtrL > &__x, const _Deque_iterator< _Tp, _RefR, _PtrR > &__y) noexcept
template<typename _IteratorL , typename _IteratorR >
auto operator- (const reverse_iterator< _IteratorL > &__x, const reverse_iterator< _IteratorR > &__y) -> decltype(__y.base()-__x.base())
template<class _Dom >
_Expr< _BinClos< __minus, _Constant, _Expr, typename _Dom::value_type, _Dom >, typename __fun< __minus, typename _Dom::value_type >::result_type > operator- (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<class _Dom >
_Expr< _BinClos< __minus, _ValArray, _Expr, typename _Dom::value_type, _Dom >, typename __fun< __minus, typename _Dom::value_type >::result_type > operator- (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<class _Dom1 , class _Dom2 >
_Expr< _BinClos< __minus, _Expr, _Expr, _Dom1, _Dom2 >, typename __fun< __minus, typename _Dom1::value_type >::result_type > operator- (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<class _Dom >
_Expr< _BinClos< __minus, _Expr, _Constant, _Dom, typename _Dom::value_type >, typename __fun< __minus, typename _Dom::value_type >::result_type > operator- (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom >
_Expr< _BinClos< __minus, _Expr, _ValArray, _Dom, typename _Dom::value_type >, typename __fun< __minus, typename _Dom::value_type >::result_type > operator- (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<typename _IteratorL , typename _IteratorR >
auto operator- (const move_iterator< _IteratorL > &__x, const move_iterator< _IteratorR > &__y) -> decltype(__x.base()-__y.base())
template<typename _Iterator >
auto operator- (const move_iterator< _Iterator > &__x, const move_iterator< _Iterator > &__y) -> decltype(__x.base()-__y.base())
template<class _Dom1 , class _Dom2 >
_Expr< _BinClos< __divides, _Expr, _Expr, _Dom1, _Dom2 >, typename __fun< __divides, typename _Dom1::value_type >::result_type > operator/ (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<class _Dom >
_Expr< _BinClos< __divides, _ValArray, _Expr, typename _Dom::value_type, _Dom >, typename __fun< __divides, typename _Dom::value_type >::result_type > operator/ (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<class _Dom >
_Expr< _BinClos< __divides, _Expr, _ValArray, _Dom, typename _Dom::value_type >, typename __fun< __divides, typename _Dom::value_type >::result_type > operator/ (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom >
_Expr< _BinClos< __divides, _Constant, _Expr, typename _Dom::value_type, _Dom >, typename __fun< __divides, typename _Dom::value_type >::result_type > operator/ (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<class _Dom >
_Expr< _BinClos< __divides, _Expr, _Constant, _Dom, typename _Dom::value_type >, typename __fun< __divides, typename _Dom::value_type >::result_type > operator/ (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _T1 , class _T2 >
constexpr bool operator< (const pair< _T1, _T2 > &__x, const pair< _T1, _T2 > &__y)
template<typename _Tp , typename _Seq >
bool operator< (const stack< _Tp, _Seq > &__x, const stack< _Tp, _Seq > &__y)
template<typename _Tp , typename _Seq >
bool operator< (const queue< _Tp, _Seq > &__x, const queue< _Tp, _Seq > &__y)
template<typename _Tp , typename _Ref , typename _Ptr >
bool operator< (const _Deque_iterator< _Tp, _Ref, _Ptr > &__x, const _Deque_iterator< _Tp, _Ref, _Ptr > &__y) noexcept
template<typename _Iterator >
bool operator< (const reverse_iterator< _Iterator > &__x, const reverse_iterator< _Iterator > &__y)
template<typename _Tp , typename _RefL , typename _PtrL , typename _RefR , typename _PtrR >
bool operator< (const _Deque_iterator< _Tp, _RefL, _PtrL > &__x, const _Deque_iterator< _Tp, _RefR, _PtrR > &__y) noexcept
template<typename _IteratorL , typename _IteratorR >
bool operator< (const reverse_iterator< _IteratorL > &__x, const reverse_iterator< _IteratorR > &__y)
template<typename _Tp1 , typename _Tp2 >
bool operator< (const shared_ptr< _Tp1 > &__a, const shared_ptr< _Tp2 > &__b) noexcept
template<typename _Tp >
bool operator< (const shared_ptr< _Tp > &__a, nullptr_t) noexcept
template<typename _Tp >
bool operator< (nullptr_t, const shared_ptr< _Tp > &__a) noexcept
template<class _Dom1 , class _Dom2 >
_Expr< _BinClos< __less, _Expr, _Expr, _Dom1, _Dom2 >, typename __fun< __less, typename _Dom1::value_type >::result_type > operator< (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<class _Dom >
_Expr< _BinClos< __less, _Constant, _Expr, typename _Dom::value_type, _Dom >, typename __fun< __less, typename _Dom::value_type >::result_type > operator< (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<class _Dom >
_Expr< _BinClos< __less, _ValArray, _Expr, typename _Dom::value_type, _Dom >, typename __fun< __less, typename _Dom::value_type >::result_type > operator< (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<class _Dom >
_Expr< _BinClos< __less, _Expr, _Constant, _Dom, typename _Dom::value_type >, typename __fun< __less, typename _Dom::value_type >::result_type > operator< (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom >
_Expr< _BinClos< __less, _Expr, _ValArray, _Dom, typename _Dom::value_type >, typename __fun< __less, typename _Dom::value_type >::result_type > operator< (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<typename _Tp , typename _Dp , typename _Up , typename _Ep >
bool operator< (const unique_ptr< _Tp, _Dp > &__x, const unique_ptr< _Up, _Ep > &__y)
template<typename _Tp , typename _Dp >
bool operator< (const unique_ptr< _Tp, _Dp > &__x, nullptr_t)
template<typename _Tp , typename _Dp >
bool operator< (nullptr_t, const unique_ptr< _Tp, _Dp > &__x)
template<typename _Key , typename _Compare , typename _Alloc >
bool operator< (const multiset< _Key, _Compare, _Alloc > &__x, const multiset< _Key, _Compare, _Alloc > &__y)
template<typename _Key , typename _Compare , typename _Alloc >
bool operator< (const set< _Key, _Compare, _Alloc > &__x, const set< _Key, _Compare, _Alloc > &__y)
template<typename _BiIter >
bool operator< (const sub_match< _BiIter > &__lhs, const sub_match< _BiIter > &__rhs)
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc >
bool operator< (const multimap< _Key, _Tp, _Compare, _Alloc > &__x, const multimap< _Key, _Tp, _Compare, _Alloc > &__y)
template<typename _Bi_iter , typename _Ch_traits , typename _Ch_alloc >
bool operator< (const __sub_match_string< _Bi_iter, _Ch_traits, _Ch_alloc > &__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _IteratorL , typename _IteratorR >
bool operator< (const move_iterator< _IteratorL > &__x, const move_iterator< _IteratorR > &__y)
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc >
bool operator< (const map< _Key, _Tp, _Compare, _Alloc > &__x, const map< _Key, _Tp, _Compare, _Alloc > &__y)
template<typename _Iterator >
bool operator< (const move_iterator< _Iterator > &__x, const move_iterator< _Iterator > &__y)
template<typename _Bi_iter , class _Ch_traits , class _Ch_alloc >
bool operator< (const sub_match< _Bi_iter > &__lhs, const __sub_match_string< _Bi_iter, _Ch_traits, _Ch_alloc > &__rhs)
template<typename _Bi_iter >
bool operator< (typename iterator_traits< _Bi_iter >::value_type const *__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Tp1 , typename _Tp2 , _Lock_policy _Lp>
bool operator< (const __shared_ptr< _Tp1, _Lp > &__a, const __shared_ptr< _Tp2, _Lp > &__b) noexcept
template<typename _Tp , _Lock_policy _Lp>
bool operator< (const __shared_ptr< _Tp, _Lp > &__a, nullptr_t) noexcept
template<typename _Tp , _Lock_policy _Lp>
bool operator< (nullptr_t, const __shared_ptr< _Tp, _Lp > &__a) noexcept
template<typename _Bi_iter >
bool operator< (const sub_match< _Bi_iter > &__lhs, typename iterator_traits< _Bi_iter >::value_type const *__rhs)
template<typename _Key , typename _Val , typename _KeyOfValue , typename _Compare , typename _Alloc >
bool operator< (const _Rb_tree< _Key, _Val, _KeyOfValue, _Compare, _Alloc > &__x, const _Rb_tree< _Key, _Val, _KeyOfValue, _Compare, _Alloc > &__y)
template<typename _Bi_iter >
bool operator< (typename iterator_traits< _Bi_iter >::value_type const &__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Tp , typename _Alloc >
bool operator< (const forward_list< _Tp, _Alloc > &__lx, const forward_list< _Tp, _Alloc > &__ly)
template<typename _Bi_iter >
bool operator< (const sub_match< _Bi_iter > &__lhs, typename iterator_traits< _Bi_iter >::value_type const &__rhs)
template<typename _Tp , typename _Alloc >
bool operator< (const vector< _Tp, _Alloc > &__x, const vector< _Tp, _Alloc > &__y)
template<typename _Tp , typename _Alloc >
bool operator< (const list< _Tp, _Alloc > &__x, const list< _Tp, _Alloc > &__y)
template<typename _Tp , typename _Alloc >
bool operator< (const deque< _Tp, _Alloc > &__x, const deque< _Tp, _Alloc > &__y)
template<typename _CharT , typename _Traits , typename _Alloc >
bool operator< (const basic_string< _CharT, _Traits, _Alloc > &__lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs)
template<typename _CharT , typename _Traits , typename _Alloc >
bool operator< (const basic_string< _CharT, _Traits, _Alloc > &__lhs, const _CharT *__rhs)
template<typename _CharT , typename _Traits , typename _Alloc >
bool operator< (const _CharT *__lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs)
template<typename _Ch , typename _Tr , typename _Tp , _Lock_policy _Lp>
std::basic_ostream< _Ch, _Tr > & operator<< (std::basic_ostream< _Ch, _Tr > &__os, const __shared_ptr< _Tp, _Lp > &__p)
template<class _Dom >
_Expr< _BinClos< __shift_left, _Expr, _ValArray, _Dom, typename _Dom::value_type >, typename __fun< __shift_left, typename _Dom::value_type >::result_type > operator<< (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom1 , class _Dom2 >
_Expr< _BinClos< __shift_left, _Expr, _Expr, _Dom1, _Dom2 >, typename __fun< __shift_left, typename _Dom1::value_type >::result_type > operator<< (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<class _Dom >
_Expr< _BinClos< __shift_left, _Expr, _Constant, _Dom, typename _Dom::value_type >, typename __fun< __shift_left, typename _Dom::value_type >::result_type > operator<< (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom >
_Expr< _BinClos< __shift_left, _Constant, _Expr, typename _Dom::value_type, _Dom >, typename __fun< __shift_left, typename _Dom::value_type >::result_type > operator<< (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<class _Dom >
_Expr< _BinClos< __shift_left, _ValArray, _Expr, typename _Dom::value_type, _Dom >, typename __fun< __shift_left, typename _Dom::value_type >::result_type > operator<< (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _RandomNumberEngine , size_t __w, typename _UIntType , typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const std::independent_bits_engine< _RandomNumberEngine, __w, _UIntType > &__x)
template<typename _Ch_type , typename _Ch_traits , typename _Bi_iter >
basic_ostream< _Ch_type, _Ch_traits > & operator<< (basic_ostream< _Ch_type, _Ch_traits > &__os, const sub_match< _Bi_iter > &__m)
template<typename _IntType , typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &, const std::uniform_int_distribution< _IntType > &)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &, const std::uniform_real_distribution< _RealType > &)
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base>
basic_ostream< _CharT, _Traits > & operator<< (basic_ostream< _CharT, _Traits > &__os, const __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base > &__str)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const std::cauchy_distribution< _RealType > &__x)
template<typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const std::bernoulli_distribution &__x)
template<typename _IntType , typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const std::geometric_distribution< _IntType > &__x)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const std::exponential_distribution< _RealType > &__x)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const std::weibull_distribution< _RealType > &__x)
template<typename _CharT , typename _Traits , typename _Alloc >
basic_ostream< _CharT, _Traits > & operator<< (basic_ostream< _CharT, _Traits > &__os, const basic_string< _CharT, _Traits, _Alloc > &__str)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const std::extreme_value_distribution< _RealType > &__x)
template<class _T1 , class _T2 >
constexpr bool operator<= (const pair< _T1, _T2 > &__x, const pair< _T1, _T2 > &__y)
template<typename _Tp , typename _Seq >
bool operator<= (const stack< _Tp, _Seq > &__x, const stack< _Tp, _Seq > &__y)
template<typename _Tp , typename _Seq >
bool operator<= (const queue< _Tp, _Seq > &__x, const queue< _Tp, _Seq > &__y)
template<typename _Iterator >
bool operator<= (const reverse_iterator< _Iterator > &__x, const reverse_iterator< _Iterator > &__y)
template<typename _Tp , typename _Ref , typename _Ptr >
bool operator<= (const _Deque_iterator< _Tp, _Ref, _Ptr > &__x, const _Deque_iterator< _Tp, _Ref, _Ptr > &__y) noexcept
template<typename _Tp , typename _RefL , typename _PtrL , typename _RefR , typename _PtrR >
bool operator<= (const _Deque_iterator< _Tp, _RefL, _PtrL > &__x, const _Deque_iterator< _Tp, _RefR, _PtrR > &__y) noexcept
template<typename _IteratorL , typename _IteratorR >
bool operator<= (const reverse_iterator< _IteratorL > &__x, const reverse_iterator< _IteratorR > &__y)
template<typename _Tp1 , typename _Tp2 >
bool operator<= (const shared_ptr< _Tp1 > &__a, const shared_ptr< _Tp2 > &__b) noexcept
template<typename _Tp >
bool operator<= (const shared_ptr< _Tp > &__a, nullptr_t) noexcept
template<typename _Tp >
bool operator<= (nullptr_t, const shared_ptr< _Tp > &__a) noexcept
template<class _Dom1 , class _Dom2 >
_Expr< _BinClos< __less_equal, _Expr, _Expr, _Dom1, _Dom2 >, typename __fun< __less_equal, typename _Dom1::value_type >::result_type > operator<= (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<class _Dom >
_Expr< _BinClos< __less_equal, _Expr, _Constant, _Dom, typename _Dom::value_type >, typename __fun< __less_equal, typename _Dom::value_type >::result_type > operator<= (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom >
_Expr< _BinClos< __less_equal, _ValArray, _Expr, typename _Dom::value_type, _Dom >, typename __fun< __less_equal, typename _Dom::value_type >::result_type > operator<= (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<class _Dom >
_Expr< _BinClos< __less_equal, _Expr, _ValArray, _Dom, typename _Dom::value_type >, typename __fun< __less_equal, typename _Dom::value_type >::result_type > operator<= (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom >
_Expr< _BinClos< __less_equal, _Constant, _Expr, typename _Dom::value_type, _Dom >, typename __fun< __less_equal, typename _Dom::value_type >::result_type > operator<= (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<typename _Tp , typename _Dp , typename _Up , typename _Ep >
bool operator<= (const unique_ptr< _Tp, _Dp > &__x, const unique_ptr< _Up, _Ep > &__y)
template<typename _Tp , typename _Dp >
bool operator<= (const unique_ptr< _Tp, _Dp > &__x, nullptr_t)
template<typename _Tp , typename _Dp >
bool operator<= (nullptr_t, const unique_ptr< _Tp, _Dp > &__x)
template<typename _Key , typename _Compare , typename _Alloc >
bool operator<= (const multiset< _Key, _Compare, _Alloc > &__x, const multiset< _Key, _Compare, _Alloc > &__y)
template<typename _Key , typename _Compare , typename _Alloc >
bool operator<= (const set< _Key, _Compare, _Alloc > &__x, const set< _Key, _Compare, _Alloc > &__y)
template<typename _BiIter >
bool operator<= (const sub_match< _BiIter > &__lhs, const sub_match< _BiIter > &__rhs)
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc >
bool operator<= (const multimap< _Key, _Tp, _Compare, _Alloc > &__x, const multimap< _Key, _Tp, _Compare, _Alloc > &__y)
template<typename _Bi_iter , typename _Ch_traits , typename _Ch_alloc >
bool operator<= (const __sub_match_string< _Bi_iter, _Ch_traits, _Ch_alloc > &__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _IteratorL , typename _IteratorR >
bool operator<= (const move_iterator< _IteratorL > &__x, const move_iterator< _IteratorR > &__y)
template<typename _Iterator >
bool operator<= (const move_iterator< _Iterator > &__x, const move_iterator< _Iterator > &__y)
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc >
bool operator<= (const map< _Key, _Tp, _Compare, _Alloc > &__x, const map< _Key, _Tp, _Compare, _Alloc > &__y)
template<typename _Bi_iter , class _Ch_traits , class _Ch_alloc >
bool operator<= (const sub_match< _Bi_iter > &__lhs, const __sub_match_string< _Bi_iter, _Ch_traits, _Ch_alloc > &__rhs)
template<typename _Bi_iter >
bool operator<= (typename iterator_traits< _Bi_iter >::value_type const *__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Tp1 , typename _Tp2 , _Lock_policy _Lp>
bool operator<= (const __shared_ptr< _Tp1, _Lp > &__a, const __shared_ptr< _Tp2, _Lp > &__b) noexcept
template<typename _Tp , _Lock_policy _Lp>
bool operator<= (const __shared_ptr< _Tp, _Lp > &__a, nullptr_t) noexcept
template<typename _Tp , _Lock_policy _Lp>
bool operator<= (nullptr_t, const __shared_ptr< _Tp, _Lp > &__a) noexcept
template<typename _Bi_iter >
bool operator<= (const sub_match< _Bi_iter > &__lhs, typename iterator_traits< _Bi_iter >::value_type const *__rhs)
template<typename _Key , typename _Val , typename _KeyOfValue , typename _Compare , typename _Alloc >
bool operator<= (const _Rb_tree< _Key, _Val, _KeyOfValue, _Compare, _Alloc > &__x, const _Rb_tree< _Key, _Val, _KeyOfValue, _Compare, _Alloc > &__y)
template<typename _Bi_iter >
bool operator<= (typename iterator_traits< _Bi_iter >::value_type const &__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Tp , typename _Alloc >
bool operator<= (const forward_list< _Tp, _Alloc > &__lx, const forward_list< _Tp, _Alloc > &__ly)
template<typename _Bi_iter >
bool operator<= (const sub_match< _Bi_iter > &__lhs, typename iterator_traits< _Bi_iter >::value_type const &__rhs)
template<typename _Tp , typename _Alloc >
bool operator<= (const vector< _Tp, _Alloc > &__x, const vector< _Tp, _Alloc > &__y)
template<typename _Tp , typename _Alloc >
bool operator<= (const list< _Tp, _Alloc > &__x, const list< _Tp, _Alloc > &__y)
template<typename _Tp , typename _Alloc >
bool operator<= (const deque< _Tp, _Alloc > &__x, const deque< _Tp, _Alloc > &__y)
template<typename _CharT , typename _Traits , typename _Alloc >
bool operator<= (const basic_string< _CharT, _Traits, _Alloc > &__lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs)
template<typename _CharT , typename _Traits , typename _Alloc >
bool operator<= (const basic_string< _CharT, _Traits, _Alloc > &__lhs, const _CharT *__rhs)
template<typename _CharT , typename _Traits , typename _Alloc >
bool operator<= (const _CharT *__lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs)
template<typename _T1 , typename _T2 >
bool operator== (const allocator< _T1 > &, const allocator< _T2 > &) noexcept
template<typename _Tp , typename _CharT , typename _Traits , typename _Dist >
bool operator== (const istream_iterator< _Tp, _CharT, _Traits, _Dist > &__x, const istream_iterator< _Tp, _CharT, _Traits, _Dist > &__y)
template<typename _Tp >
bool operator== (const allocator< _Tp > &, const allocator< _Tp > &) noexcept
template<typename _CharT , typename _Traits >
bool operator== (const istreambuf_iterator< _CharT, _Traits > &__a, const istreambuf_iterator< _CharT, _Traits > &__b)
template<class _T1 , class _T2 >
constexpr bool operator== (const pair< _T1, _T2 > &__x, const pair< _T1, _T2 > &__y)
template<typename _StateT >
bool operator== (const fpos< _StateT > &__lhs, const fpos< _StateT > &__rhs)
template<typename _Tp , typename _Seq >
bool operator== (const stack< _Tp, _Seq > &__x, const stack< _Tp, _Seq > &__y)
template<typename _Tp >
bool operator== (const _Fwd_list_iterator< _Tp > &__x, const _Fwd_list_const_iterator< _Tp > &__y) noexcept
template<typename _Tp , typename _Ref , typename _Ptr >
bool operator== (const _Deque_iterator< _Tp, _Ref, _Ptr > &__x, const _Deque_iterator< _Tp, _Ref, _Ptr > &__y) noexcept
template<typename _Tp , typename _Seq >
bool operator== (const queue< _Tp, _Seq > &__x, const queue< _Tp, _Seq > &__y)
template<typename _Tp , typename _RefL , typename _PtrL , typename _RefR , typename _PtrR >
bool operator== (const _Deque_iterator< _Tp, _RefL, _PtrL > &__x, const _Deque_iterator< _Tp, _RefR, _PtrR > &__y) noexcept
template<typename _Val >
bool operator== (const _List_iterator< _Val > &__x, const _List_const_iterator< _Val > &__y) noexcept
template<typename _Iterator >
bool operator== (const reverse_iterator< _Iterator > &__x, const reverse_iterator< _Iterator > &__y)
template<typename _Val >
bool operator== (const _Rb_tree_iterator< _Val > &__x, const _Rb_tree_const_iterator< _Val > &__y) noexcept
template<typename _Tp1 , typename _Tp2 >
bool operator== (const shared_ptr< _Tp1 > &__a, const shared_ptr< _Tp2 > &__b) noexcept
template<typename _Tp >
bool operator== (const shared_ptr< _Tp > &__a, nullptr_t) noexcept
template<typename _IteratorL , typename _IteratorR >
bool operator== (const reverse_iterator< _IteratorL > &__x, const reverse_iterator< _IteratorR > &__y)
template<typename _Tp >
bool operator== (nullptr_t, const shared_ptr< _Tp > &__a) noexcept
template<class _Dom1 , class _Dom2 >
_Expr< _BinClos< __equal_to, _Expr, _Expr, _Dom1, _Dom2 >, typename __fun< __equal_to, typename _Dom1::value_type >::result_type > operator== (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<class _Dom >
_Expr< _BinClos< __equal_to, _Constant, _Expr, typename _Dom::value_type, _Dom >, typename __fun< __equal_to, typename _Dom::value_type >::result_type > operator== (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<class _Dom >
_Expr< _BinClos< __equal_to, _ValArray, _Expr, typename _Dom::value_type, _Dom >, typename __fun< __equal_to, typename _Dom::value_type >::result_type > operator== (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<class _Dom >
_Expr< _BinClos< __equal_to, _Expr, _ValArray, _Dom, typename _Dom::value_type >, typename __fun< __equal_to, typename _Dom::value_type >::result_type > operator== (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom >
_Expr< _BinClos< __equal_to, _Expr, _Constant, _Dom, typename _Dom::value_type >, typename __fun< __equal_to, typename _Dom::value_type >::result_type > operator== (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<typename _Tp , typename _Dp , typename _Up , typename _Ep >
bool operator== (const unique_ptr< _Tp, _Dp > &__x, const unique_ptr< _Up, _Ep > &__y)
template<typename _Tp , typename _Dp >
bool operator== (const unique_ptr< _Tp, _Dp > &__x, nullptr_t) noexcept
template<typename _Tp , typename _Dp >
bool operator== (nullptr_t, const unique_ptr< _Tp, _Dp > &__x) noexcept
template<typename _Key , typename _Compare , typename _Alloc >
bool operator== (const multiset< _Key, _Compare, _Alloc > &__x, const multiset< _Key, _Compare, _Alloc > &__y)
template<typename _Key , typename _Compare , typename _Alloc >
bool operator== (const set< _Key, _Compare, _Alloc > &__x, const set< _Key, _Compare, _Alloc > &__y)
template<typename _BiIter >
bool operator== (const sub_match< _BiIter > &__lhs, const sub_match< _BiIter > &__rhs)
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc >
bool operator== (const multimap< _Key, _Tp, _Compare, _Alloc > &__x, const multimap< _Key, _Tp, _Compare, _Alloc > &__y)
template<typename _Bi_iter , typename _Ch_traits , typename _Ch_alloc >
bool operator== (const __sub_match_string< _Bi_iter, _Ch_traits, _Ch_alloc > &__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _IteratorL , typename _IteratorR >
bool operator== (const move_iterator< _IteratorL > &__x, const move_iterator< _IteratorR > &__y)
template<typename _Iterator >
bool operator== (const move_iterator< _Iterator > &__x, const move_iterator< _Iterator > &__y)
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc >
bool operator== (const map< _Key, _Tp, _Compare, _Alloc > &__x, const map< _Key, _Tp, _Compare, _Alloc > &__y)
template<typename _Bi_iter , typename _Ch_traits , typename _Ch_alloc >
bool operator== (const sub_match< _Bi_iter > &__lhs, const __sub_match_string< _Bi_iter, _Ch_traits, _Ch_alloc > &__rhs)
template<typename _Bi_iter >
bool operator== (typename iterator_traits< _Bi_iter >::value_type const *__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Tp1 , typename _Tp2 , _Lock_policy _Lp>
bool operator== (const __shared_ptr< _Tp1, _Lp > &__a, const __shared_ptr< _Tp2, _Lp > &__b) noexcept
template<typename _Tp , _Lock_policy _Lp>
bool operator== (const __shared_ptr< _Tp, _Lp > &__a, nullptr_t) noexcept
template<typename _Tp , _Lock_policy _Lp>
bool operator== (nullptr_t, const __shared_ptr< _Tp, _Lp > &__a) noexcept
template<typename _Bi_iter >
bool operator== (const sub_match< _Bi_iter > &__lhs, typename iterator_traits< _Bi_iter >::value_type const *__rhs)
template<typename _Key , typename _Val , typename _KeyOfValue , typename _Compare , typename _Alloc >
bool operator== (const _Rb_tree< _Key, _Val, _KeyOfValue, _Compare, _Alloc > &__x, const _Rb_tree< _Key, _Val, _KeyOfValue, _Compare, _Alloc > &__y)
template<typename _Bi_iter >
bool operator== (typename iterator_traits< _Bi_iter >::value_type const &__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Tp , typename _Alloc >
bool operator== (const forward_list< _Tp, _Alloc > &__lx, const forward_list< _Tp, _Alloc > &__ly)
template<typename _Bi_iter >
bool operator== (const sub_match< _Bi_iter > &__lhs, typename iterator_traits< _Bi_iter >::value_type const &__rhs)
template<class _Value , class _Hash , class _Pred , class _Alloc >
bool operator== (const unordered_set< _Value, _Hash, _Pred, _Alloc > &__x, const unordered_set< _Value, _Hash, _Pred, _Alloc > &__y)
template<class _Value , class _Hash , class _Pred , class _Alloc >
bool operator== (const unordered_multiset< _Value, _Hash, _Pred, _Alloc > &__x, const unordered_multiset< _Value, _Hash, _Pred, _Alloc > &__y)
template<typename _Tp , typename _Alloc >
bool operator== (const vector< _Tp, _Alloc > &__x, const vector< _Tp, _Alloc > &__y)
template<class _Key , class _Tp , class _Hash , class _Pred , class _Alloc >
bool operator== (const unordered_map< _Key, _Tp, _Hash, _Pred, _Alloc > &__x, const unordered_map< _Key, _Tp, _Hash, _Pred, _Alloc > &__y)
template<class _Key , class _Tp , class _Hash , class _Pred , class _Alloc >
bool operator== (const unordered_multimap< _Key, _Tp, _Hash, _Pred, _Alloc > &__x, const unordered_multimap< _Key, _Tp, _Hash, _Pred, _Alloc > &__y)
template<typename _Tp , typename _Alloc >
_GLIBCXX_END_NAMESPACE_CXX11 bool operator== (const list< _Tp, _Alloc > &__x, const list< _Tp, _Alloc > &__y)
template<typename _Bi_iter , typename _Alloc >
bool operator== (const match_results< _Bi_iter, _Alloc > &__m1, const match_results< _Bi_iter, _Alloc > &__m2)
template<typename _Tp , typename _Alloc >
bool operator== (const deque< _Tp, _Alloc > &__x, const deque< _Tp, _Alloc > &__y)
template<typename _CharT , typename _Traits , typename _Alloc >
bool operator== (const basic_string< _CharT, _Traits, _Alloc > &__lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs)
template<typename _CharT >
__gnu_cxx::__enable_if< __is_char< _CharT >::__value, bool >::__type operator== (const basic_string< _CharT > &__lhs, const basic_string< _CharT > &__rhs)
template<typename _CharT , typename _Traits , typename _Alloc >
bool operator== (const _CharT *__lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs)
template<typename _CharT , typename _Traits , typename _Alloc >
bool operator== (const basic_string< _CharT, _Traits, _Alloc > &__lhs, const _CharT *__rhs)
template<class _T1 , class _T2 >
constexpr bool operator> (const pair< _T1, _T2 > &__x, const pair< _T1, _T2 > &__y)
template<typename _Tp , typename _Seq >
bool operator> (const stack< _Tp, _Seq > &__x, const stack< _Tp, _Seq > &__y)
template<typename _Tp , typename _Seq >
bool operator> (const queue< _Tp, _Seq > &__x, const queue< _Tp, _Seq > &__y)
template<typename _Tp , typename _Ref , typename _Ptr >
bool operator> (const _Deque_iterator< _Tp, _Ref, _Ptr > &__x, const _Deque_iterator< _Tp, _Ref, _Ptr > &__y) noexcept
template<typename _Iterator >
bool operator> (const reverse_iterator< _Iterator > &__x, const reverse_iterator< _Iterator > &__y)
template<typename _Tp , typename _RefL , typename _PtrL , typename _RefR , typename _PtrR >
bool operator> (const _Deque_iterator< _Tp, _RefL, _PtrL > &__x, const _Deque_iterator< _Tp, _RefR, _PtrR > &__y) noexcept
template<typename _IteratorL , typename _IteratorR >
bool operator> (const reverse_iterator< _IteratorL > &__x, const reverse_iterator< _IteratorR > &__y)
template<typename _Tp1 , typename _Tp2 >
bool operator> (const shared_ptr< _Tp1 > &__a, const shared_ptr< _Tp2 > &__b) noexcept
template<typename _Tp >
bool operator> (const shared_ptr< _Tp > &__a, nullptr_t) noexcept
template<typename _Tp >
bool operator> (nullptr_t, const shared_ptr< _Tp > &__a) noexcept
template<class _Dom >
_Expr< _BinClos< __greater, _Expr, _Constant, _Dom, typename _Dom::value_type >, typename __fun< __greater, typename _Dom::value_type >::result_type > operator> (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom >
_Expr< _BinClos< __greater, _Constant, _Expr, typename _Dom::value_type, _Dom >, typename __fun< __greater, typename _Dom::value_type >::result_type > operator> (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<class _Dom1 , class _Dom2 >
_Expr< _BinClos< __greater, _Expr, _Expr, _Dom1, _Dom2 >, typename __fun< __greater, typename _Dom1::value_type >::result_type > operator> (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<class _Dom >
_Expr< _BinClos< __greater, _ValArray, _Expr, typename _Dom::value_type, _Dom >, typename __fun< __greater, typename _Dom::value_type >::result_type > operator> (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<class _Dom >
_Expr< _BinClos< __greater, _Expr, _ValArray, _Dom, typename _Dom::value_type >, typename __fun< __greater, typename _Dom::value_type >::result_type > operator> (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<typename _Tp , typename _Dp , typename _Up , typename _Ep >
bool operator> (const unique_ptr< _Tp, _Dp > &__x, const unique_ptr< _Up, _Ep > &__y)
template<typename _Tp , typename _Dp >
bool operator> (const unique_ptr< _Tp, _Dp > &__x, nullptr_t)
template<typename _Tp , typename _Dp >
bool operator> (nullptr_t, const unique_ptr< _Tp, _Dp > &__x)
template<typename _Key , typename _Compare , typename _Alloc >
bool operator> (const multiset< _Key, _Compare, _Alloc > &__x, const multiset< _Key, _Compare, _Alloc > &__y)
template<typename _Key , typename _Compare , typename _Alloc >
bool operator> (const set< _Key, _Compare, _Alloc > &__x, const set< _Key, _Compare, _Alloc > &__y)
template<typename _BiIter >
bool operator> (const sub_match< _BiIter > &__lhs, const sub_match< _BiIter > &__rhs)
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc >
bool operator> (const multimap< _Key, _Tp, _Compare, _Alloc > &__x, const multimap< _Key, _Tp, _Compare, _Alloc > &__y)
template<typename _Bi_iter , typename _Ch_traits , typename _Ch_alloc >
bool operator> (const __sub_match_string< _Bi_iter, _Ch_traits, _Ch_alloc > &__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc >
bool operator> (const map< _Key, _Tp, _Compare, _Alloc > &__x, const map< _Key, _Tp, _Compare, _Alloc > &__y)
template<typename _IteratorL , typename _IteratorR >
bool operator> (const move_iterator< _IteratorL > &__x, const move_iterator< _IteratorR > &__y)
template<typename _Iterator >
bool operator> (const move_iterator< _Iterator > &__x, const move_iterator< _Iterator > &__y)
template<typename _Bi_iter , class _Ch_traits , class _Ch_alloc >
bool operator> (const sub_match< _Bi_iter > &__lhs, const __sub_match_string< _Bi_iter, _Ch_traits, _Ch_alloc > &__rhs)
template<typename _Bi_iter >
bool operator> (typename iterator_traits< _Bi_iter >::value_type const *__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Tp1 , typename _Tp2 , _Lock_policy _Lp>
bool operator> (const __shared_ptr< _Tp1, _Lp > &__a, const __shared_ptr< _Tp2, _Lp > &__b) noexcept
template<typename _Tp , _Lock_policy _Lp>
bool operator> (const __shared_ptr< _Tp, _Lp > &__a, nullptr_t) noexcept
template<typename _Tp , _Lock_policy _Lp>
bool operator> (nullptr_t, const __shared_ptr< _Tp, _Lp > &__a) noexcept
template<typename _Bi_iter >
bool operator> (const sub_match< _Bi_iter > &__lhs, typename iterator_traits< _Bi_iter >::value_type const *__rhs)
template<typename _Key , typename _Val , typename _KeyOfValue , typename _Compare , typename _Alloc >
bool operator> (const _Rb_tree< _Key, _Val, _KeyOfValue, _Compare, _Alloc > &__x, const _Rb_tree< _Key, _Val, _KeyOfValue, _Compare, _Alloc > &__y)
template<typename _Bi_iter >
bool operator> (typename iterator_traits< _Bi_iter >::value_type const &__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Tp , typename _Alloc >
bool operator> (const forward_list< _Tp, _Alloc > &__lx, const forward_list< _Tp, _Alloc > &__ly)
template<typename _Bi_iter >
bool operator> (const sub_match< _Bi_iter > &__lhs, typename iterator_traits< _Bi_iter >::value_type const &__rhs)
template<typename _Tp , typename _Alloc >
bool operator> (const vector< _Tp, _Alloc > &__x, const vector< _Tp, _Alloc > &__y)
template<typename _Tp , typename _Alloc >
bool operator> (const list< _Tp, _Alloc > &__x, const list< _Tp, _Alloc > &__y)
template<typename _Tp , typename _Alloc >
bool operator> (const deque< _Tp, _Alloc > &__x, const deque< _Tp, _Alloc > &__y)
template<typename _CharT , typename _Traits , typename _Alloc >
bool operator> (const basic_string< _CharT, _Traits, _Alloc > &__lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs)
template<typename _CharT , typename _Traits , typename _Alloc >
bool operator> (const basic_string< _CharT, _Traits, _Alloc > &__lhs, const _CharT *__rhs)
template<typename _CharT , typename _Traits , typename _Alloc >
bool operator> (const _CharT *__lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs)
template<class _T1 , class _T2 >
constexpr bool operator>= (const pair< _T1, _T2 > &__x, const pair< _T1, _T2 > &__y)
template<typename _Tp , typename _Seq >
bool operator>= (const stack< _Tp, _Seq > &__x, const stack< _Tp, _Seq > &__y)
template<typename _Tp , typename _Seq >
bool operator>= (const queue< _Tp, _Seq > &__x, const queue< _Tp, _Seq > &__y)
template<typename _Iterator >
bool operator>= (const reverse_iterator< _Iterator > &__x, const reverse_iterator< _Iterator > &__y)
template<typename _Tp , typename _Ref , typename _Ptr >
bool operator>= (const _Deque_iterator< _Tp, _Ref, _Ptr > &__x, const _Deque_iterator< _Tp, _Ref, _Ptr > &__y) noexcept
template<typename _Tp , typename _RefL , typename _PtrL , typename _RefR , typename _PtrR >
bool operator>= (const _Deque_iterator< _Tp, _RefL, _PtrL > &__x, const _Deque_iterator< _Tp, _RefR, _PtrR > &__y) noexcept
template<typename _IteratorL , typename _IteratorR >
bool operator>= (const reverse_iterator< _IteratorL > &__x, const reverse_iterator< _IteratorR > &__y)
template<class _Dom >
_Expr< _BinClos< __greater_equal, _Expr, _Constant, _Dom, typename _Dom::value_type >, typename __fun< __greater_equal, typename _Dom::value_type >::result_type > operator>= (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom >
_Expr< _BinClos< __greater_equal, _ValArray, _Expr, typename _Dom::value_type, _Dom >, typename __fun< __greater_equal, typename _Dom::value_type >::result_type > operator>= (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<class _Dom >
_Expr< _BinClos< __greater_equal, _Constant, _Expr, typename _Dom::value_type, _Dom >, typename __fun< __greater_equal, typename _Dom::value_type >::result_type > operator>= (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<class _Dom1 , class _Dom2 >
_Expr< _BinClos< __greater_equal, _Expr, _Expr, _Dom1, _Dom2 >, typename __fun< __greater_equal, typename _Dom1::value_type >::result_type > operator>= (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<typename _Tp1 , typename _Tp2 >
bool operator>= (const shared_ptr< _Tp1 > &__a, const shared_ptr< _Tp2 > &__b) noexcept
template<class _Dom >
_Expr< _BinClos< __greater_equal, _Expr, _ValArray, _Dom, typename _Dom::value_type >, typename __fun< __greater_equal, typename _Dom::value_type >::result_type > operator>= (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<typename _Tp >
bool operator>= (const shared_ptr< _Tp > &__a, nullptr_t) noexcept
template<typename _Tp >
bool operator>= (nullptr_t, const shared_ptr< _Tp > &__a) noexcept
template<typename _Tp , typename _Dp , typename _Up , typename _Ep >
bool operator>= (const unique_ptr< _Tp, _Dp > &__x, const unique_ptr< _Up, _Ep > &__y)
template<typename _Tp , typename _Dp >
bool operator>= (const unique_ptr< _Tp, _Dp > &__x, nullptr_t)
template<typename _Tp , typename _Dp >
bool operator>= (nullptr_t, const unique_ptr< _Tp, _Dp > &__x)
template<typename _Key , typename _Compare , typename _Alloc >
bool operator>= (const multiset< _Key, _Compare, _Alloc > &__x, const multiset< _Key, _Compare, _Alloc > &__y)
template<typename _Key , typename _Compare , typename _Alloc >
bool operator>= (const set< _Key, _Compare, _Alloc > &__x, const set< _Key, _Compare, _Alloc > &__y)
template<typename _BiIter >
bool operator>= (const sub_match< _BiIter > &__lhs, const sub_match< _BiIter > &__rhs)
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc >
bool operator>= (const multimap< _Key, _Tp, _Compare, _Alloc > &__x, const multimap< _Key, _Tp, _Compare, _Alloc > &__y)
template<typename _Bi_iter , typename _Ch_traits , typename _Ch_alloc >
bool operator>= (const __sub_match_string< _Bi_iter, _Ch_traits, _Ch_alloc > &__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc >
bool operator>= (const map< _Key, _Tp, _Compare, _Alloc > &__x, const map< _Key, _Tp, _Compare, _Alloc > &__y)
template<typename _IteratorL , typename _IteratorR >
bool operator>= (const move_iterator< _IteratorL > &__x, const move_iterator< _IteratorR > &__y)
template<typename _Iterator >
bool operator>= (const move_iterator< _Iterator > &__x, const move_iterator< _Iterator > &__y)
template<typename _Bi_iter , class _Ch_traits , class _Ch_alloc >
bool operator>= (const sub_match< _Bi_iter > &__lhs, const __sub_match_string< _Bi_iter, _Ch_traits, _Ch_alloc > &__rhs)
template<typename _Bi_iter >
bool operator>= (typename iterator_traits< _Bi_iter >::value_type const *__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Tp1 , typename _Tp2 , _Lock_policy _Lp>
bool operator>= (const __shared_ptr< _Tp1, _Lp > &__a, const __shared_ptr< _Tp2, _Lp > &__b) noexcept
template<typename _Tp , _Lock_policy _Lp>
bool operator>= (const __shared_ptr< _Tp, _Lp > &__a, nullptr_t) noexcept
template<typename _Tp , _Lock_policy _Lp>
bool operator>= (nullptr_t, const __shared_ptr< _Tp, _Lp > &__a) noexcept
template<typename _Bi_iter >
bool operator>= (const sub_match< _Bi_iter > &__lhs, typename iterator_traits< _Bi_iter >::value_type const *__rhs)
template<typename _Key , typename _Val , typename _KeyOfValue , typename _Compare , typename _Alloc >
bool operator>= (const _Rb_tree< _Key, _Val, _KeyOfValue, _Compare, _Alloc > &__x, const _Rb_tree< _Key, _Val, _KeyOfValue, _Compare, _Alloc > &__y)
template<typename _Bi_iter >
bool operator>= (typename iterator_traits< _Bi_iter >::value_type const &__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Tp , typename _Alloc >
bool operator>= (const forward_list< _Tp, _Alloc > &__lx, const forward_list< _Tp, _Alloc > &__ly)
template<typename _Bi_iter >
bool operator>= (const sub_match< _Bi_iter > &__lhs, typename iterator_traits< _Bi_iter >::value_type const &__rhs)
template<typename _Tp , typename _Alloc >
bool operator>= (const vector< _Tp, _Alloc > &__x, const vector< _Tp, _Alloc > &__y)
template<typename _Tp , typename _Alloc >
bool operator>= (const list< _Tp, _Alloc > &__x, const list< _Tp, _Alloc > &__y)
template<typename _Tp , typename _Alloc >
bool operator>= (const deque< _Tp, _Alloc > &__x, const deque< _Tp, _Alloc > &__y)
template<typename _CharT , typename _Traits , typename _Alloc >
bool operator>= (const basic_string< _CharT, _Traits, _Alloc > &__lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs)
template<typename _CharT , typename _Traits , typename _Alloc >
bool operator>= (const basic_string< _CharT, _Traits, _Alloc > &__lhs, const _CharT *__rhs)
template<typename _CharT , typename _Traits , typename _Alloc >
bool operator>= (const _CharT *__lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs)
template<class _Dom >
_Expr< _BinClos< __shift_right, _Constant, _Expr, typename _Dom::value_type, _Dom >, typename __fun< __shift_right, typename _Dom::value_type >::result_type > operator>> (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<class _Dom >
_Expr< _BinClos< __shift_right, _ValArray, _Expr, typename _Dom::value_type, _Dom >, typename __fun< __shift_right, typename _Dom::value_type >::result_type > operator>> (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<class _Dom >
_Expr< _BinClos< __shift_right, _Expr, _Constant, _Dom, typename _Dom::value_type >, typename __fun< __shift_right, typename _Dom::value_type >::result_type > operator>> (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom >
_Expr< _BinClos< __shift_right, _Expr, _ValArray, _Dom, typename _Dom::value_type >, typename __fun< __shift_right, typename _Dom::value_type >::result_type > operator>> (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom1 , class _Dom2 >
_Expr< _BinClos< __shift_right, _Expr, _Expr, _Dom1, _Dom2 >, typename __fun< __shift_right, typename _Dom1::value_type >::result_type > operator>> (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<typename _IntType , typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &, std::uniform_int_distribution< _IntType > &)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &, std::uniform_real_distribution< _RealType > &)
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base>
basic_istream< _CharT, _Traits > & operator>> (basic_istream< _CharT, _Traits > &__is, __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base > &__str)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, std::cauchy_distribution< _RealType > &__x)
template<typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, std::bernoulli_distribution &__x)
template<typename _IntType , typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, std::geometric_distribution< _IntType > &__x)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, std::exponential_distribution< _RealType > &__x)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, std::weibull_distribution< _RealType > &__x)
template<typename _CharT , typename _Traits , typename _Alloc >
basic_istream< _CharT, _Traits > & operator>> (basic_istream< _CharT, _Traits > &__is, basic_string< _CharT, _Traits, _Alloc > &__str)
template<>
basic_istream< char > & operator>> (basic_istream< char > &__is, basic_string< char > &__str)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, std::extreme_value_distribution< _RealType > &__x)
constexpr _Ios_Fmtflags operator^ (_Ios_Fmtflags __a, _Ios_Fmtflags __b)
constexpr _Ios_Openmode operator^ (_Ios_Openmode __a, _Ios_Openmode __b)
constexpr _Ios_Iostate operator^ (_Ios_Iostate __a, _Ios_Iostate __b)
template<class _Dom >
_Expr< _BinClos< __bitwise_xor, _Expr, _ValArray, _Dom, typename _Dom::value_type >, typename __fun< __bitwise_xor, typename _Dom::value_type >::result_type > operator^ (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom >
_Expr< _BinClos< __bitwise_xor, _Expr, _Constant, _Dom, typename _Dom::value_type >, typename __fun< __bitwise_xor, typename _Dom::value_type >::result_type > operator^ (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom >
_Expr< _BinClos< __bitwise_xor, _Constant, _Expr, typename _Dom::value_type, _Dom >, typename __fun< __bitwise_xor, typename _Dom::value_type >::result_type > operator^ (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<class _Dom1 , class _Dom2 >
_Expr< _BinClos< __bitwise_xor, _Expr, _Expr, _Dom1, _Dom2 >, typename __fun< __bitwise_xor, typename _Dom1::value_type >::result_type > operator^ (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<class _Dom >
_Expr< _BinClos< __bitwise_xor, _ValArray, _Expr, typename _Dom::value_type, _Dom >, typename __fun< __bitwise_xor, typename _Dom::value_type >::result_type > operator^ (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
const _Ios_Fmtflags & operator^= (_Ios_Fmtflags &__a, _Ios_Fmtflags __b)
const _Ios_Openmode & operator^= (_Ios_Openmode &__a, _Ios_Openmode __b)
const _Ios_Iostate & operator^= (_Ios_Iostate &__a, _Ios_Iostate __b)
constexpr memory_order operator| (memory_order __m, __memory_order_modifier __mod)
constexpr _Ios_Fmtflags operator| (_Ios_Fmtflags __a, _Ios_Fmtflags __b)
constexpr _Ios_Openmode operator| (_Ios_Openmode __a, _Ios_Openmode __b)
constexpr _Ios_Iostate operator| (_Ios_Iostate __a, _Ios_Iostate __b)
template<class _Dom >
_Expr< _BinClos< __bitwise_or, _ValArray, _Expr, typename _Dom::value_type, _Dom >, typename __fun< __bitwise_or, typename _Dom::value_type >::result_type > operator| (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<class _Dom >
_Expr< _BinClos< __bitwise_or, _Constant, _Expr, typename _Dom::value_type, _Dom >, typename __fun< __bitwise_or, typename _Dom::value_type >::result_type > operator| (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<class _Dom1 , class _Dom2 >
_Expr< _BinClos< __bitwise_or, _Expr, _Expr, _Dom1, _Dom2 >, typename __fun< __bitwise_or, typename _Dom1::value_type >::result_type > operator| (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<class _Dom >
_Expr< _BinClos< __bitwise_or, _Expr, _ValArray, _Dom, typename _Dom::value_type >, typename __fun< __bitwise_or, typename _Dom::value_type >::result_type > operator| (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom >
_Expr< _BinClos< __bitwise_or, _Expr, _Constant, _Dom, typename _Dom::value_type >, typename __fun< __bitwise_or, typename _Dom::value_type >::result_type > operator| (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
const _Ios_Fmtflags & operator|= (_Ios_Fmtflags &__a, _Ios_Fmtflags __b)
const _Ios_Openmode & operator|= (_Ios_Openmode &__a, _Ios_Openmode __b)
const _Ios_Iostate & operator|= (_Ios_Iostate &__a, _Ios_Iostate __b)
template<class _Dom >
_Expr< _BinClos< __logical_or, _Constant, _Expr, typename _Dom::value_type, _Dom >, typename __fun< __logical_or, typename _Dom::value_type >::result_type > operator|| (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<class _Dom >
_Expr< _BinClos< __logical_or, _ValArray, _Expr, typename _Dom::value_type, _Dom >, typename __fun< __logical_or, typename _Dom::value_type >::result_type > operator|| (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<class _Dom1 , class _Dom2 >
_Expr< _BinClos< __logical_or, _Expr, _Expr, _Dom1, _Dom2 >, typename __fun< __logical_or, typename _Dom1::value_type >::result_type > operator|| (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<class _Dom >
_Expr< _BinClos< __logical_or, _Expr, _ValArray, _Dom, typename _Dom::value_type >, typename __fun< __logical_or, typename _Dom::value_type >::result_type > operator|| (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom >
_Expr< _BinClos< __logical_or, _Expr, _Constant, _Dom, typename _Dom::value_type >, typename __fun< __logical_or, typename _Dom::value_type >::result_type > operator|| (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
constexpr _Ios_Fmtflags operator~ (_Ios_Fmtflags __a)
constexpr _Ios_Openmode operator~ (_Ios_Openmode __a)
constexpr _Ios_Iostate operator~ (_Ios_Iostate __a)
template<typename _RAIter >
void partial_sort (_RAIter, _RAIter, _RAIter)
template<typename _RAIter , typename _Compare >
void partial_sort (_RAIter, _RAIter, _RAIter, _Compare)
template<typename _RandomAccessIterator >
void partial_sort (_RandomAccessIterator __first, _RandomAccessIterator __middle, _RandomAccessIterator __last)
template<typename _RandomAccessIterator , typename _Compare >
void partial_sort (_RandomAccessIterator __first, _RandomAccessIterator __middle, _RandomAccessIterator __last, _Compare __comp)
template<typename _IIter , typename _RAIter >
_RAIter partial_sort_copy (_IIter, _IIter, _RAIter, _RAIter)
template<typename _IIter , typename _RAIter , typename _Compare >
_RAIter partial_sort_copy (_IIter, _IIter, _RAIter, _RAIter, _Compare)
template<typename _InputIterator , typename _RandomAccessIterator >
_RandomAccessIterator partial_sort_copy (_InputIterator __first, _InputIterator __last, _RandomAccessIterator __result_first, _RandomAccessIterator __result_last)
template<typename _InputIterator , typename _RandomAccessIterator , typename _Compare >
_RandomAccessIterator partial_sort_copy (_InputIterator __first, _InputIterator __last, _RandomAccessIterator __result_first, _RandomAccessIterator __result_last, _Compare __comp)
template<typename _InputIterator , typename _OutputIterator >
_OutputIterator partial_sum (_InputIterator __first, _InputIterator __last, _OutputIterator __result)
template<typename _InputIterator , typename _OutputIterator , typename _BinaryOperation >
_OutputIterator partial_sum (_InputIterator __first, _InputIterator __last, _OutputIterator __result, _BinaryOperation __binary_op)
template<typename _BIter , typename _Predicate >
_BIter partition (_BIter, _BIter, _Predicate)
template<typename _ForwardIterator , typename _Predicate >
_ForwardIterator partition (_ForwardIterator __first, _ForwardIterator __last, _Predicate __pred)
template<typename _IIter , typename _OIter1 , typename _OIter2 , typename _Predicate >
pair< _OIter1, _OIter2 > partition_copy (_IIter, _IIter, _OIter1, _OIter2, _Predicate)
template<typename _InputIterator , typename _OutputIterator1 , typename _OutputIterator2 , typename _Predicate >
pair< _OutputIterator1, _OutputIterator2 > partition_copy (_InputIterator __first, _InputIterator __last, _OutputIterator1 __out_true, _OutputIterator2 __out_false, _Predicate __pred)
template<typename _FIter , typename _Predicate >
_FIter partition_point (_FIter, _FIter, _Predicate)
template<typename _ForwardIterator , typename _Predicate >
_ForwardIterator partition_point (_ForwardIterator __first, _ForwardIterator __last, _Predicate __pred)
template<typename _RandomAccessIterator >
void pop_heap (_RandomAccessIterator __first, _RandomAccessIterator __last)
template<typename _RandomAccessIterator , typename _Compare >
void pop_heap (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _RAIter >
void pop_heap (_RAIter, _RAIter)
template<typename _RAIter , typename _Compare >
void pop_heap (_RAIter, _RAIter, _Compare)
template<class _Dom >
_Expr< _BinClos< _Pow, _Constant, _Expr, typename _Dom::value_type, _Dom >, typename _Dom::value_type > pow (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<class _Dom >
_Expr< _BinClos< _Pow, _ValArray, _Expr, typename _Dom::value_type, _Dom >, typename _Dom::value_type > pow (const valarray< typename _Dom::valarray > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp >
_Expr< _BinClos< _Pow, _ValArray, _Constant, _Tp, _Tp >, _Tp > pow (const valarray< _Tp > &__v, const _Tp &__t)
template<class _Dom >
_Expr< _BinClos< _Pow, _Expr, _ValArray, _Dom, typename _Dom::value_type >, typename _Dom::value_type > pow (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<typename _Tp >
_Expr< _BinClos< _Pow, _Constant, _ValArray, _Tp, _Tp >, _Tp > pow (const _Tp &__t, const valarray< _Tp > &__v)
template<typename _Tp >
_Expr< _BinClos< _Pow, _ValArray, _ValArray, _Tp, _Tp >, _Tp > pow (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<class _Dom >
_Expr< _BinClos< _Pow, _Expr, _Constant, _Dom, typename _Dom::value_type >, typename _Dom::value_type > pow (const _Expr< _Dom, typename _Dom::value_type > &__e, const typename _Dom::value_type &__t)
template<class _Dom1 , class _Dom2 >
_Expr< _BinClos< _Pow, _Expr, _Expr, _Dom1, _Dom2 >, typename _Dom1::value_type > pow (const _Expr< _Dom1, typename _Dom1::value_type > &__e1, const _Expr< _Dom2, typename _Dom2::value_type > &__e2)
template<typename _BidirectionalIterator >
_BidirectionalIterator prev (_BidirectionalIterator __x, typename iterator_traits< _BidirectionalIterator >::difference_type __n=1)
template<typename _BIter >
bool prev_permutation (_BIter, _BIter)
template<typename _BIter , typename _Compare >
bool prev_permutation (_BIter, _BIter, _Compare)
template<typename _BidirectionalIterator >
bool prev_permutation (_BidirectionalIterator __first, _BidirectionalIterator __last)
template<typename _BidirectionalIterator , typename _Compare >
bool prev_permutation (_BidirectionalIterator __first, _BidirectionalIterator __last, _Compare __comp)
template<typename _Arg , typename _Result >
pointer_to_unary_function< _Arg, _Result > ptr_fun (_Result(*__x)(_Arg))
template<typename _Arg1 , typename _Arg2 , typename _Result >
pointer_to_binary_function< _Arg1, _Arg2, _Result > ptr_fun (_Result(*__x)(_Arg1, _Arg2))
template<typename _RandomAccessIterator >
void push_heap (_RandomAccessIterator __first, _RandomAccessIterator __last)
template<typename _RandomAccessIterator , typename _Compare >
void push_heap (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _RAIter >
void push_heap (_RAIter, _RAIter)
template<typename _RAIter , typename _Compare >
void push_heap (_RAIter, _RAIter, _Compare)
template<typename _RAIter >
void random_shuffle (_RAIter, _RAIter)
template<typename _RAIter , typename _Generator >
void random_shuffle (_RAIter, _RAIter, _Generator &&)
template<typename _RandomAccessIterator >
void random_shuffle (_RandomAccessIterator __first, _RandomAccessIterator __last)
template<typename _RandomAccessIterator , typename _RandomNumberGenerator >
void random_shuffle (_RandomAccessIterator __first, _RandomAccessIterator __last, _RandomNumberGenerator &&__rand)
template<typename _FIter , typename _Tp >
_FIter remove (_FIter, _FIter, const _Tp &)
template<typename _ForwardIterator , typename _Tp >
_ForwardIterator remove (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__value)
template<typename _IIter , typename _OIter , typename _Tp >
_OIter remove_copy (_IIter, _IIter, _OIter, const _Tp &)
template<typename _InputIterator , typename _OutputIterator , typename _Tp >
_OutputIterator remove_copy (_InputIterator __first, _InputIterator __last, _OutputIterator __result, const _Tp &__value)
template<typename _IIter , typename _OIter , typename _Predicate >
_OIter remove_copy_if (_IIter, _IIter, _OIter, _Predicate)
template<typename _InputIterator , typename _OutputIterator , typename _Predicate >
_OutputIterator remove_copy_if (_InputIterator __first, _InputIterator __last, _OutputIterator __result, _Predicate __pred)
template<typename _FIter , typename _Predicate >
_FIter remove_if (_FIter, _FIter, _Predicate)
template<typename _ForwardIterator , typename _Predicate >
_ForwardIterator remove_if (_ForwardIterator __first, _ForwardIterator __last, _Predicate __pred)
template<typename _FIter , typename _Tp >
void replace (_FIter, _FIter, const _Tp &, const _Tp &)
template<typename _ForwardIterator , typename _Tp >
void replace (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__old_value, const _Tp &__new_value)
template<typename _IIter , typename _OIter , typename _Tp >
_OIter replace_copy (_IIter, _IIter, _OIter, const _Tp &, const _Tp &)
template<typename _InputIterator , typename _OutputIterator , typename _Tp >
_OutputIterator replace_copy (_InputIterator __first, _InputIterator __last, _OutputIterator __result, const _Tp &__old_value, const _Tp &__new_value)
template<typename _Iter , typename _OIter , typename _Predicate , typename _Tp >
_OIter replace_copy_if (_Iter, _Iter, _OIter, _Predicate, const _Tp &)
template<typename _InputIterator , typename _OutputIterator , typename _Predicate , typename _Tp >
_OutputIterator replace_copy_if (_InputIterator __first, _InputIterator __last, _OutputIterator __result, _Predicate __pred, const _Tp &__new_value)
template<typename _FIter , typename _Predicate , typename _Tp >
void replace_if (_FIter, _FIter, _Predicate, const _Tp &)
template<typename _ForwardIterator , typename _Predicate , typename _Tp >
void replace_if (_ForwardIterator __first, _ForwardIterator __last, _Predicate __pred, const _Tp &__new_value)
void rethrow_exception (exception_ptr) __attribute__((__noreturn__))
template<typename _Ex >
void rethrow_if_nested (const _Ex &__ex)
template<typename _Tp >
void return_temporary_buffer (_Tp *__p)
template<typename _BIter >
void reverse (_BIter, _BIter)
template<typename _BidirectionalIterator >
void reverse (_BidirectionalIterator __first, _BidirectionalIterator __last)
template<typename _BIter , typename _OIter >
_OIter reverse_copy (_BIter, _BIter, _OIter)
template<typename _BidirectionalIterator , typename _OutputIterator >
_OutputIterator reverse_copy (_BidirectionalIterator __first, _BidirectionalIterator __last, _OutputIterator __result)
ios_base & right (ios_base &__base)
template<typename _FIter , typename _OIter >
_OIter rotate_copy (_FIter, _FIter, _FIter, _OIter)
template<typename _ForwardIterator , typename _OutputIterator >
_OutputIterator rotate_copy (_ForwardIterator __first, _ForwardIterator __middle, _ForwardIterator __last, _OutputIterator __result)
ios_base & scientific (ios_base &__base)
template<typename _FIter1 , typename _FIter2 >
_FIter1 search (_FIter1, _FIter1, _FIter2, _FIter2)
template<typename _FIter1 , typename _FIter2 , typename _BinaryPredicate >
_FIter1 search (_FIter1, _FIter1, _FIter2, _FIter2, _BinaryPredicate)
template<typename _ForwardIterator1 , typename _ForwardIterator2 >
_ForwardIterator1 search (_ForwardIterator1 __first1, _ForwardIterator1 __last1, _ForwardIterator2 __first2, _ForwardIterator2 __last2)
template<typename _ForwardIterator1 , typename _ForwardIterator2 , typename _BinaryPredicate >
_ForwardIterator1 search (_ForwardIterator1 __first1, _ForwardIterator1 __last1, _ForwardIterator2 __first2, _ForwardIterator2 __last2, _BinaryPredicate __predicate)
template<typename _FIter , typename _Size , typename _Tp >
_FIter search_n (_FIter, _FIter, _Size, const _Tp &)
template<typename _FIter , typename _Size , typename _Tp , typename _BinaryPredicate >
_FIter search_n (_FIter, _FIter, _Size, const _Tp &, _BinaryPredicate)
template<typename _ForwardIterator , typename _Integer , typename _Tp >
_ForwardIterator search_n (_ForwardIterator __first, _ForwardIterator __last, _Integer __count, const _Tp &__val)
template<typename _ForwardIterator , typename _Integer , typename _Tp , typename _BinaryPredicate >
_ForwardIterator search_n (_ForwardIterator __first, _ForwardIterator __last, _Integer __count, const _Tp &__val, _BinaryPredicate __binary_pred)
template<typename _IIter1 , typename _IIter2 , typename _OIter >
_OIter set_difference (_IIter1, _IIter1, _IIter2, _IIter2, _OIter)
template<typename _IIter1 , typename _IIter2 , typename _OIter , typename _Compare >
_OIter set_difference (_IIter1, _IIter1, _IIter2, _IIter2, _OIter, _Compare)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator >
_OutputIterator set_difference (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator , typename _Compare >
_OutputIterator set_difference (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result, _Compare __comp)
template<typename _IIter1 , typename _IIter2 , typename _OIter >
_OIter set_intersection (_IIter1, _IIter1, _IIter2, _IIter2, _OIter)
template<typename _IIter1 , typename _IIter2 , typename _OIter , typename _Compare >
_OIter set_intersection (_IIter1, _IIter1, _IIter2, _IIter2, _OIter, _Compare)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator >
_OutputIterator set_intersection (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator , typename _Compare >
_OutputIterator set_intersection (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result, _Compare __comp)
template<typename _IIter1 , typename _IIter2 , typename _OIter >
_OIter set_symmetric_difference (_IIter1, _IIter1, _IIter2, _IIter2, _OIter)
template<typename _IIter1 , typename _IIter2 , typename _OIter , typename _Compare >
_OIter set_symmetric_difference (_IIter1, _IIter1, _IIter2, _IIter2, _OIter, _Compare)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator >
_OutputIterator set_symmetric_difference (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator , typename _Compare >
_OutputIterator set_symmetric_difference (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result, _Compare __comp)
template<typename _IIter1 , typename _IIter2 , typename _OIter >
_OIter set_union (_IIter1, _IIter1, _IIter2, _IIter2, _OIter)
template<typename _IIter1 , typename _IIter2 , typename _OIter , typename _Compare >
_OIter set_union (_IIter1, _IIter1, _IIter2, _IIter2, _OIter, _Compare)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator >
_OutputIterator set_union (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator , typename _Compare >
_OutputIterator set_union (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result, _Compare __comp)
ios_base & showbase (ios_base &__base)
ios_base & showpoint (ios_base &__base)
ios_base & showpos (ios_base &__base)
template<typename _RAIter , typename _UGenerator >
void shuffle (_RAIter, _RAIter, _UGenerator &&)
template<typename _RandomAccessIterator , typename _UniformRandomNumberGenerator >
void shuffle (_RandomAccessIterator __first, _RandomAccessIterator __last, _UniformRandomNumberGenerator &&__g)
template<class _Dom >
_Expr< _UnClos< _Sin, _Expr, _Dom >, typename _Dom::value_type > sin (const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp >
_Expr< _UnClos< _Sin, _ValArray, _Tp >, _Tp > sin (const valarray< _Tp > &__v)
template<typename _Tp >
_Expr< _UnClos< _Sinh, _ValArray, _Tp >, _Tp > sinh (const valarray< _Tp > &__v)
template<class _Dom >
_Expr< _UnClos< _Sinh, _Expr, _Dom >, typename _Dom::value_type > sinh (const _Expr< _Dom, typename _Dom::value_type > &__e)
ios_base & skipws (ios_base &__base)
template<typename _RAIter >
void sort (_RAIter, _RAIter)
template<typename _RAIter , typename _Compare >
void sort (_RAIter, _RAIter, _Compare)
template<typename _RandomAccessIterator >
void sort (_RandomAccessIterator __first, _RandomAccessIterator __last)
template<typename _RandomAccessIterator , typename _Compare >
void sort (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _RandomAccessIterator >
void sort_heap (_RandomAccessIterator __first, _RandomAccessIterator __last)
template<typename _RandomAccessIterator , typename _Compare >
void sort_heap (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _RAIter >
void sort_heap (_RAIter, _RAIter)
template<typename _RAIter , typename _Compare >
void sort_heap (_RAIter, _RAIter, _Compare)
template<typename _Tp >
_Expr< _UnClos< _Sqrt, _ValArray, _Tp >, _Tp > sqrt (const valarray< _Tp > &__v)
template<class _Dom >
_Expr< _UnClos< _Sqrt, _Expr, _Dom >, typename _Dom::value_type > sqrt (const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _BIter , typename _Predicate >
_BIter stable_partition (_BIter, _BIter, _Predicate)
template<typename _ForwardIterator , typename _Predicate >
_ForwardIterator stable_partition (_ForwardIterator __first, _ForwardIterator __last, _Predicate __pred)
template<typename _RAIter >
void stable_sort (_RAIter, _RAIter)
template<typename _RAIter , typename _Compare >
void stable_sort (_RAIter, _RAIter, _Compare)
template<typename _RandomAccessIterator >
void stable_sort (_RandomAccessIterator __first, _RandomAccessIterator __last)
template<typename _RandomAccessIterator , typename _Compare >
void stable_sort (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _Tp , typename _Tp1 >
shared_ptr< _Tp > static_pointer_cast (const shared_ptr< _Tp1 > &__r) noexcept
template<typename _Tp , typename _Tp1 , _Lock_policy _Lp>
__shared_ptr< _Tp, _Lp > static_pointer_cast (const __shared_ptr< _Tp1, _Lp > &__r) noexcept
void swap (_Bit_reference __x, _Bit_reference __y) noexcept
void swap (_Bit_reference __x, bool &__y) noexcept
void swap (bool &__x, _Bit_reference __y) noexcept
template<class _T1 , class _T2 >
void swap (pair< _T1, _T2 > &__x, pair< _T1, _T2 > &__y) noexcept(noexcept(__x.swap(__y)))
template<typename _Tp , typename _Seq >
void swap (stack< _Tp, _Seq > &__x, stack< _Tp, _Seq > &__y) noexcept(noexcept(__x.swap(__y)))
template<typename _Tp , typename _Seq >
void swap (queue< _Tp, _Seq > &__x, queue< _Tp, _Seq > &__y) noexcept(noexcept(__x.swap(__y)))
template<typename _Tp >
void swap (shared_ptr< _Tp > &__a, shared_ptr< _Tp > &__b) noexcept
template<typename _Tp >
void swap (weak_ptr< _Tp > &__a, weak_ptr< _Tp > &__b) noexcept
template<typename _Tp , typename _Sequence , typename _Compare >
void swap (priority_queue< _Tp, _Sequence, _Compare > &__x, priority_queue< _Tp, _Sequence, _Compare > &__y) noexcept(noexcept(__x.swap(__y)))
template<typename _Tp >
void swap (_Tp &__a, _Tp &__b) noexcept(__and_< is_nothrow_move_constructible< _Tp >,is_nothrow_move_assignable< _Tp >>::value)
template<typename _Tp , size_t _Nm>
void swap (_Tp(&__a)[_Nm], _Tp(&__b)[_Nm]) noexcept(noexcept(swap(*__a,*__b)))
template<typename _Tp , typename _Dp >
void swap (unique_ptr< _Tp, _Dp > &__x, unique_ptr< _Tp, _Dp > &__y) noexcept
template<typename _Ch_type , typename _Rx_traits >
void swap (basic_regex< _Ch_type, _Rx_traits > &__lhs, basic_regex< _Ch_type, _Rx_traits > &__rhs)
template<typename _Key , typename _Compare , typename _Alloc >
void swap (multiset< _Key, _Compare, _Alloc > &__x, multiset< _Key, _Compare, _Alloc > &__y)
template<typename _Key , typename _Compare , typename _Alloc >
void swap (set< _Key, _Compare, _Alloc > &__x, set< _Key, _Compare, _Alloc > &__y)
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc >
void swap (multimap< _Key, _Tp, _Compare, _Alloc > &__x, multimap< _Key, _Tp, _Compare, _Alloc > &__y)
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc >
void swap (map< _Key, _Tp, _Compare, _Alloc > &__x, map< _Key, _Tp, _Compare, _Alloc > &__y)
template<typename _Tp , _Lock_policy _Lp>
void swap (__shared_ptr< _Tp, _Lp > &__a, __shared_ptr< _Tp, _Lp > &__b) noexcept
template<typename _Key , typename _Val , typename _KeyOfValue , typename _Compare , typename _Alloc >
void swap (_Rb_tree< _Key, _Val, _KeyOfValue, _Compare, _Alloc > &__x, _Rb_tree< _Key, _Val, _KeyOfValue, _Compare, _Alloc > &__y)
template<typename _Tp , typename _Alloc >
void swap (forward_list< _Tp, _Alloc > &__lx, forward_list< _Tp, _Alloc > &__ly)
template<class _Value , class _Hash , class _Pred , class _Alloc >
void swap (unordered_set< _Value, _Hash, _Pred, _Alloc > &__x, unordered_set< _Value, _Hash, _Pred, _Alloc > &__y)
template<class _Value , class _Hash , class _Pred , class _Alloc >
void swap (unordered_multiset< _Value, _Hash, _Pred, _Alloc > &__x, unordered_multiset< _Value, _Hash, _Pred, _Alloc > &__y)
template<typename _Tp , _Lock_policy _Lp>
void swap (__weak_ptr< _Tp, _Lp > &__a, __weak_ptr< _Tp, _Lp > &__b) noexcept
template<class _Key , class _Tp , class _Hash , class _Pred , class _Alloc >
void swap (unordered_map< _Key, _Tp, _Hash, _Pred, _Alloc > &__x, unordered_map< _Key, _Tp, _Hash, _Pred, _Alloc > &__y)
template<class _Key , class _Tp , class _Hash , class _Pred , class _Alloc >
void swap (unordered_multimap< _Key, _Tp, _Hash, _Pred, _Alloc > &__x, unordered_multimap< _Key, _Tp, _Hash, _Pred, _Alloc > &__y)
template<typename _Tp , typename _Alloc >
void swap (vector< _Tp, _Alloc > &__x, vector< _Tp, _Alloc > &__y)
template<typename _Tp , typename _Alloc >
void swap (list< _Tp, _Alloc > &__x, list< _Tp, _Alloc > &__y)
template<typename _Bi_iter , typename _Alloc >
void swap (match_results< _Bi_iter, _Alloc > &__lhs, match_results< _Bi_iter, _Alloc > &__rhs)
template<typename _Tp , typename _Alloc >
void swap (deque< _Tp, _Alloc > &__x, deque< _Tp, _Alloc > &__y)
template<typename _CharT , typename _Traits , typename _Alloc >
void swap (basic_string< _CharT, _Traits, _Alloc > &__lhs, basic_string< _CharT, _Traits, _Alloc > &__rhs)
template<typename _ForwardIterator1 , typename _ForwardIterator2 >
_ForwardIterator2 swap_ranges (_ForwardIterator1 __first1, _ForwardIterator1 __last1, _ForwardIterator2 __first2)
template<typename _FIter1 , typename _FIter2 >
_FIter2 swap_ranges (_FIter1, _FIter1, _FIter2)
template<class _Dom >
_Expr< _UnClos< _Tan, _Expr, _Dom >, typename _Dom::value_type > tan (const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp >
_Expr< _UnClos< _Tan, _ValArray, _Tp >, _Tp > tan (const valarray< _Tp > &__v)
template<class _Dom >
_Expr< _UnClos< _Tanh, _Expr, _Dom >, typename _Dom::value_type > tanh (const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp >
_Expr< _UnClos< _Tanh, _ValArray, _Tp >, _Tp > tanh (const valarray< _Tp > &__v)
template<typename _Tp >
void throw_with_nested (_Tp &&__t)
template<typename _CharT >
_CharT tolower (_CharT __c, const locale &__loc)
template<typename _CharT >
_CharT toupper (_CharT __c, const locale &__loc)
template<typename _IIter , typename _OIter , typename _UnaryOperation >
_OIter transform (_IIter, _IIter, _OIter, _UnaryOperation)
template<typename _IIter1 , typename _IIter2 , typename _OIter , typename _BinaryOperation >
_OIter transform (_IIter1, _IIter1, _IIter2, _OIter, _BinaryOperation)
template<typename _InputIterator , typename _OutputIterator , typename _UnaryOperation >
_OutputIterator transform (_InputIterator __first, _InputIterator __last, _OutputIterator __result, _UnaryOperation __unary_op)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator , typename _BinaryOperation >
_OutputIterator transform (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _OutputIterator __result, _BinaryOperation __binary_op)
template<typename _InputIterator , typename _ForwardIterator >
_ForwardIterator uninitialized_copy (_InputIterator __first, _InputIterator __last, _ForwardIterator __result)
template<typename _InputIterator , typename _Size , typename _ForwardIterator >
_ForwardIterator uninitialized_copy_n (_InputIterator __first, _Size __n, _ForwardIterator __result)
template<typename _ForwardIterator , typename _Tp >
void uninitialized_fill (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__x)
template<typename _ForwardIterator , typename _Size , typename _Tp >
_ForwardIterator uninitialized_fill_n (_ForwardIterator __first, _Size __n, const _Tp &__x)
template<typename _FIter >
_FIter unique (_FIter, _FIter)
template<typename _FIter , typename _BinaryPredicate >
_FIter unique (_FIter, _FIter, _BinaryPredicate)
template<typename _ForwardIterator >
_ForwardIterator unique (_ForwardIterator __first, _ForwardIterator __last)
template<typename _ForwardIterator , typename _BinaryPredicate >
_ForwardIterator unique (_ForwardIterator __first, _ForwardIterator __last, _BinaryPredicate __binary_pred)
template<typename _IIter , typename _OIter >
_OIter unique_copy (_IIter, _IIter, _OIter)
template<typename _IIter , typename _OIter , typename _BinaryPredicate >
_OIter unique_copy (_IIter, _IIter, _OIter, _BinaryPredicate)
template<typename _InputIterator , typename _OutputIterator >
_OutputIterator unique_copy (_InputIterator __first, _InputIterator __last, _OutputIterator __result)
template<typename _InputIterator , typename _OutputIterator , typename _BinaryPredicate >
_OutputIterator unique_copy (_InputIterator __first, _InputIterator __last, _OutputIterator __result, _BinaryPredicate __binary_pred)
ios_base & unitbuf (ios_base &__base)
template<typename _FIter , typename _Tp >
_FIter upper_bound (_FIter, _FIter, const _Tp &)
template<typename _FIter , typename _Tp , typename _Compare >
_FIter upper_bound (_FIter, _FIter, const _Tp &, _Compare)
template<typename _ForwardIterator , typename _Tp >
_ForwardIterator upper_bound (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__val)
template<typename _ForwardIterator , typename _Tp , typename _Compare >
_ForwardIterator upper_bound (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__val, _Compare __comp)
ios_base & uppercase (ios_base &__base)
template<typename _Facet >
const _Facet & use_facet (const locale &)
Matching, Searching, and Replacing
template<typename _Bi_iter , typename _Alloc , typename _Ch_type , typename _Rx_traits >
bool regex_match (_Bi_iter __s, _Bi_iter __e, match_results< _Bi_iter, _Alloc > &__m, const basic_regex< _Ch_type, _Rx_traits > &__re, regex_constants::match_flag_type __flags=regex_constants::match_default)
template<typename _Bi_iter , typename _Ch_type , typename _Rx_traits >
bool regex_match (_Bi_iter __first, _Bi_iter __last, const basic_regex< _Ch_type, _Rx_traits > &__re, regex_constants::match_flag_type __flags=regex_constants::match_default)
template<typename _Ch_type , typename _Alloc , typename _Rx_traits >
bool regex_match (const _Ch_type *__s, match_results< const _Ch_type *, _Alloc > &__m, const basic_regex< _Ch_type, _Rx_traits > &__re, regex_constants::match_flag_type __f=regex_constants::match_default)
template<typename _Ch_traits , typename _Ch_alloc , typename _Alloc , typename _Ch_type , typename _Rx_traits >
bool regex_match (const basic_string< _Ch_type, _Ch_traits, _Ch_alloc > &__s, match_results< typename basic_string< _Ch_type, _Ch_traits, _Ch_alloc >::const_iterator, _Alloc > &__m, const basic_regex< _Ch_type, _Rx_traits > &__re, regex_constants::match_flag_type __flags=regex_constants::match_default)
template<typename _Ch_traits , typename _Ch_alloc , typename _Alloc , typename _Ch_type , typename _Rx_traits >
bool regex_match (const basic_string< _Ch_type, _Ch_traits, _Ch_alloc > &&, match_results< typename basic_string< _Ch_type, _Ch_traits, _Ch_alloc >::const_iterator, _Alloc > &, const basic_regex< _Ch_type, _Rx_traits > &, regex_constants::match_flag_type=regex_constants::match_default)=delete
template<typename _Ch_type , class _Rx_traits >
bool regex_match (const _Ch_type *__s, const basic_regex< _Ch_type, _Rx_traits > &__re, regex_constants::match_flag_type __f=regex_constants::match_default)
template<typename _Ch_traits , typename _Str_allocator , typename _Ch_type , typename _Rx_traits >
bool regex_match (const basic_string< _Ch_type, _Ch_traits, _Str_allocator > &__s, const basic_regex< _Ch_type, _Rx_traits > &__re, regex_constants::match_flag_type __flags=regex_constants::match_default)
template<typename _Bi_iter , typename _Alloc , typename _Ch_type , typename _Rx_traits >
bool regex_search (_Bi_iter __s, _Bi_iter __e, match_results< _Bi_iter, _Alloc > &__m, const basic_regex< _Ch_type, _Rx_traits > &__re, regex_constants::match_flag_type __flags=regex_constants::match_default)
template<typename _Bi_iter , typename _Ch_type , typename _Rx_traits >
bool regex_search (_Bi_iter __first, _Bi_iter __last, const basic_regex< _Ch_type, _Rx_traits > &__re, regex_constants::match_flag_type __flags=regex_constants::match_default)
template<typename _Ch_type , class _Alloc , class _Rx_traits >
bool regex_search (const _Ch_type *__s, match_results< const _Ch_type *, _Alloc > &__m, const basic_regex< _Ch_type, _Rx_traits > &__e, regex_constants::match_flag_type __f=regex_constants::match_default)
template<typename _Ch_type , typename _Rx_traits >
bool regex_search (const _Ch_type *__s, const basic_regex< _Ch_type, _Rx_traits > &__e, regex_constants::match_flag_type __f=regex_constants::match_default)
template<typename _Ch_traits , typename _String_allocator , typename _Ch_type , typename _Rx_traits >
bool regex_search (const basic_string< _Ch_type, _Ch_traits, _String_allocator > &__s, const basic_regex< _Ch_type, _Rx_traits > &__e, regex_constants::match_flag_type __flags=regex_constants::match_default)
template<typename _Ch_traits , typename _Ch_alloc , typename _Alloc , typename _Ch_type , typename _Rx_traits >
bool regex_search (const basic_string< _Ch_type, _Ch_traits, _Ch_alloc > &__s, match_results< typename basic_string< _Ch_type, _Ch_traits, _Ch_alloc >::const_iterator, _Alloc > &__m, const basic_regex< _Ch_type, _Rx_traits > &__e, regex_constants::match_flag_type __f=regex_constants::match_default)
template<typename _Ch_traits , typename _Ch_alloc , typename _Alloc , typename _Ch_type , typename _Rx_traits >
bool regex_search (const basic_string< _Ch_type, _Ch_traits, _Ch_alloc > &&, match_results< typename basic_string< _Ch_type, _Ch_traits, _Ch_alloc >::const_iterator, _Alloc > &, const basic_regex< _Ch_type, _Rx_traits > &, regex_constants::match_flag_type=regex_constants::match_default)=delete
template<typename _Out_iter , typename _Bi_iter , typename _Rx_traits , typename _Ch_type , typename _St , typename _Sa >
_Out_iter regex_replace (_Out_iter __out, _Bi_iter __first, _Bi_iter __last, const basic_regex< _Ch_type, _Rx_traits > &__e, const basic_string< _Ch_type, _St, _Sa > &__fmt, regex_constants::match_flag_type __flags=regex_constants::match_default)
template<typename _Out_iter , typename _Bi_iter , typename _Rx_traits , typename _Ch_type >
_Out_iter regex_replace (_Out_iter __out, _Bi_iter __first, _Bi_iter __last, const basic_regex< _Ch_type, _Rx_traits > &__e, const _Ch_type *__fmt, regex_constants::match_flag_type __flags=regex_constants::match_default)
template<typename _Rx_traits , typename _Ch_type , typename _St , typename _Sa , typename _Fst , typename _Fsa >
basic_string< _Ch_type, _St, _Sa > regex_replace (const basic_string< _Ch_type, _St, _Sa > &__s, const basic_regex< _Ch_type, _Rx_traits > &__e, const basic_string< _Ch_type, _Fst, _Fsa > &__fmt, regex_constants::match_flag_type __flags=regex_constants::match_default)
template<typename _Rx_traits , typename _Ch_type , typename _St , typename _Sa >
basic_string< _Ch_type, _St, _Sa > regex_replace (const basic_string< _Ch_type, _St, _Sa > &__s, const basic_regex< _Ch_type, _Rx_traits > &__e, const _Ch_type *__fmt, regex_constants::match_flag_type __flags=regex_constants::match_default)
template<typename _Rx_traits , typename _Ch_type , typename _St , typename _Sa >
basic_string< _Ch_type > regex_replace (const _Ch_type *__s, const basic_regex< _Ch_type, _Rx_traits > &__e, const basic_string< _Ch_type, _St, _Sa > &__fmt, regex_constants::match_flag_type __flags=regex_constants::match_default)
template<typename _Rx_traits , typename _Ch_type >
basic_string< _Ch_type > regex_replace (const _Ch_type *__s, const basic_regex< _Ch_type, _Rx_traits > &__e, const _Ch_type *__fmt, regex_constants::match_flag_type __flags=regex_constants::match_default)
template<typename _Tp , _Lock_policy _Lp>
bool atomic_is_lock_free (const __shared_ptr< _Tp, _Lp > *__p)
template<typename _Tp >
bool atomic_is_lock_free (const shared_ptr< _Tp > *__p)
template<typename _Tp >
shared_ptr< _Tp > atomic_load_explicit (const shared_ptr< _Tp > *__p, memory_order)
template<typename _Tp >
shared_ptr< _Tp > atomic_load (const shared_ptr< _Tp > *__p)
template<typename _Tp , _Lock_policy _Lp>
__shared_ptr< _Tp, _Lp > atomic_load_explicit (const __shared_ptr< _Tp, _Lp > *__p, memory_order)
template<typename _Tp , _Lock_policy _Lp>
__shared_ptr< _Tp, _Lp > atomic_load (const __shared_ptr< _Tp, _Lp > *__p)
template<typename _Tp >
void atomic_store_explicit (shared_ptr< _Tp > *__p, shared_ptr< _Tp > __r, memory_order)
template<typename _Tp >
void atomic_store (shared_ptr< _Tp > *__p, shared_ptr< _Tp > __r)
template<typename _Tp , _Lock_policy _Lp>
void atomic_store_explicit (__shared_ptr< _Tp, _Lp > *__p, __shared_ptr< _Tp, _Lp > __r, memory_order)
template<typename _Tp , _Lock_policy _Lp>
void atomic_store (__shared_ptr< _Tp, _Lp > *__p, __shared_ptr< _Tp, _Lp > __r)
template<typename _Tp >
shared_ptr< _Tp > atomic_exchange_explicit (shared_ptr< _Tp > *__p, shared_ptr< _Tp > __r, memory_order)
template<typename _Tp >
shared_ptr< _Tp > atomic_exchange (shared_ptr< _Tp > *__p, shared_ptr< _Tp > __r)
template<typename _Tp , _Lock_policy _Lp>
__shared_ptr< _Tp, _Lp > atomic_exchange_explicit (__shared_ptr< _Tp, _Lp > *__p, __shared_ptr< _Tp, _Lp > __r, memory_order)
template<typename _Tp , _Lock_policy _Lp>
__shared_ptr< _Tp, _Lp > atomic_exchange (__shared_ptr< _Tp, _Lp > *__p, __shared_ptr< _Tp, _Lp > __r)
template<typename _Tp >
bool atomic_compare_exchange_strong_explicit (shared_ptr< _Tp > *__p, shared_ptr< _Tp > *__v, shared_ptr< _Tp > __w, memory_order, memory_order)
template<typename _Tp >
bool atomic_compare_exchange_strong (shared_ptr< _Tp > *__p, shared_ptr< _Tp > *__v, shared_ptr< _Tp > __w)
template<typename _Tp >
bool atomic_compare_exchange_weak_explicit (shared_ptr< _Tp > *__p, shared_ptr< _Tp > *__v, shared_ptr< _Tp > __w, memory_order __success, memory_order __failure)
template<typename _Tp >
bool atomic_compare_exchange_weak (shared_ptr< _Tp > *__p, shared_ptr< _Tp > *__v, shared_ptr< _Tp > __w)
template<typename _Tp , _Lock_policy _Lp>
bool atomic_compare_exchange_strong_explicit (__shared_ptr< _Tp, _Lp > *__p, __shared_ptr< _Tp, _Lp > *__v, __shared_ptr< _Tp, _Lp > __w, memory_order, memory_order)
template<typename _Tp , _Lock_policy _Lp>
bool atomic_compare_exchange_strong (__shared_ptr< _Tp, _Lp > *__p, __shared_ptr< _Tp, _Lp > *__v, __shared_ptr< _Tp, _Lp > __w)
template<typename _Tp , _Lock_policy _Lp>
bool atomic_compare_exchange_weak_explicit (__shared_ptr< _Tp, _Lp > *__p, __shared_ptr< _Tp, _Lp > *__v, __shared_ptr< _Tp, _Lp > __w, memory_order __success, memory_order __failure)
template<typename _Tp , _Lock_policy _Lp>
bool atomic_compare_exchange_weak (__shared_ptr< _Tp, _Lp > *__p, __shared_ptr< _Tp, _Lp > *__v, __shared_ptr< _Tp, _Lp > __w)
Variables
constexpr allocator_arg_t allocator_arg
decltype(nullptr) typedef nullptr_t
constexpr piecewise_construct_t piecewise_construct
Detailed Description
ISO C++ entities toplevel namespace is std.
Typedef Documentation
template<bool _Cache> using std::__umap_traits = typedef __detail::_Hashtable_traits<_Cache, false, true>
Base types for unordered_map.
Definition at line 39 of file unordered_map.h.
template<bool _Cache> using std::__ummap_traits = typedef __detail::_Hashtable_traits<_Cache, false, false>
Base types for unordered_multimap.
Definition at line 56 of file unordered_map.h.
template<bool _Cache> using std::__umset_traits = typedef __detail::_Hashtable_traits<_Cache, true, false>
Base types for unordered_multiset.
Definition at line 54 of file unordered_set.h.
template<bool _Cache> using std::__uset_traits = typedef __detail::_Hashtable_traits<_Cache, true, true>
Base types for unordered_set.
Definition at line 39 of file unordered_set.h.
typedef long long std::streamoff
Type used by fpos, char_traits<char>, and char_traits<wchar_t>.
In clauses 21.1.3.1 and 27.4.1 streamoff is described as an implementation defined type. Note: In versions of GCC up to and including GCC 3.3, streamoff was typedef long.
Definition at line 94 of file postypes.h.
typedef fpos<mbstate_t> std::streampos
File position for char streams.
Definition at line 228 of file postypes.h.
typedef ptrdiff_t std::streamsize
Integral type for I/O operation counts and buffer sizes.
Definition at line 98 of file postypes.h.
typedef fpos<mbstate_t> std::u16streampos
File position for char16_t streams.
Definition at line 234 of file postypes.h.
typedef fpos<mbstate_t> std::u32streampos
File position for char32_t streams.
Definition at line 236 of file postypes.h.
typedef fpos<mbstate_t> std::wstreampos
File position for wchar_t streams.
Definition at line 230 of file postypes.h.
Enumeration Type Documentation
anonymous enum
Todo:
Needs documentation! See http://gcc.gnu.org/onlinedocs/libstdc++/manual/documentation_style.html This controls some aspect of the sort routines.
Definition at line 1870 of file stl_algo.h.
enum std::io_errc strong
I/O error code.
Definition at line 203 of file ios_base.h.
Function Documentation
template<typename _Alloc > __allocated_ptr<_Alloc> std::__allocate_guarded (_Alloc & __a)
Allocate space for a single object using __a.
Definition at line 100 of file allocated_ptr.h.
References std::allocator_traits< _Alloc >::allocate().
template<typename _RandomAccessIterator , typename _Compare > void std::__final_insertion_sort (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
This is a helper function for the sort routine.
Definition at line 1875 of file stl_algo.h.
References __insertion_sort(), and __unguarded_insertion_sort().
template<typename _InputIterator , typename _Predicate > _InputIterator std::__find_if (_InputIterator __first, _InputIterator __last, _Predicate __pred, input_iterator_tag) inline
This is an overload used by find algos for the Input Iterator case.
Definition at line 101 of file stl_algo.h.
Referenced by __find_if_not(), __search_n_aux(), find(), and find_if().
template<typename _RandomAccessIterator , typename _Predicate > _RandomAccessIterator std::__find_if (_RandomAccessIterator __first, _RandomAccessIterator __last, _Predicate __pred, random_access_iterator_tag)
This is an overload used by find algos for the RAI case.
Definition at line 112 of file stl_algo.h.
template<typename _InputIterator , typename _Predicate > _InputIterator std::__find_if_not (_InputIterator __first, _InputIterator __last, _Predicate __pred) inline
Provided for stable_partition to use.
Definition at line 168 of file stl_algo.h.
References __find_if(), and __iterator_category().
Referenced by find_if_not().
template<typename _InputIterator , typename _Predicate , typename _Distance > _InputIterator std::__find_if_not_n (_InputIterator __first, _Distance & __len, _Predicate __pred)
Like find_if_not(), but uses and updates a count of the remaining range length instead of comparing against an end iterator.
Definition at line 181 of file stl_algo.h.
Referenced by __stable_partition_adaptive().
template<typename _EuclideanRingElement > _EuclideanRingElement std::__gcd (_EuclideanRingElement __m, _EuclideanRingElement __n)
This is a helper function for the rotate algorithm specialized on RAIs. It returns the greatest common divisor of two integer values.
Definition at line 1229 of file stl_algo.h.
template<typename _RandomAccessIterator , typename _Compare > void std::__heap_select (_RandomAccessIterator __first, _RandomAccessIterator __middle, _RandomAccessIterator __last, _Compare __comp)
This is a helper function for the sort routines.
Definition at line 1665 of file stl_algo.h.
template<typename _RandomAccessIterator , typename _Compare > void std::__inplace_stable_sort (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
This is a helper function for the stable sorting routines.
Definition at line 2771 of file stl_algo.h.
References __insertion_sort(), and __merge_without_buffer().
template<typename _RandomAccessIterator , typename _Compare > void std::__insertion_sort (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
This is a helper function for the sort routine.
Definition at line 1835 of file stl_algo.h.
References __unguarded_linear_insert().
Referenced by __final_insertion_sort(), and __inplace_stable_sort().
template<typename _RandomAccessIterator , typename _Size , typename _Compare > void std::__introsort_loop (_RandomAccessIterator __first, _RandomAccessIterator __last, _Size __depth_limit, _Compare __comp)
This is a helper function for the sort routine.
Definition at line 1935 of file stl_algo.h.
References __unguarded_partition_pivot().
constexpr int std::__lg (int __n) inline
This is a helper function for the sort routines and for random.tcc.
Definition at line 1012 of file stl_algobase.h.
Referenced by nth_element().
template<typename _BidirectionalIterator , typename _Distance , typename _Pointer , typename _Compare > void std::__merge_adaptive (_BidirectionalIterator __first, _BidirectionalIterator __middle, _BidirectionalIterator __last, _Distance __len1, _Distance __len2, _Pointer __buffer, _Distance __buffer_size, _Compare __comp)
This is a helper function for the merge routines.
Definition at line 2427 of file stl_algo.h.
References __move_merge_adaptive(), __move_merge_adaptive_backward(), __rotate_adaptive(), advance(), and distance().
template<typename _BidirectionalIterator , typename _Distance , typename _Compare > void std::__merge_without_buffer (_BidirectionalIterator __first, _BidirectionalIterator __middle, _BidirectionalIterator __last, _Distance __len1, _Distance __len2, _Compare __comp)
This is a helper function for the merge routines.
Definition at line 2488 of file stl_algo.h.
References advance(), distance(), iter_swap(), and std::_V2::rotate().
Referenced by __inplace_stable_sort().
template<typename _Iterator , typename _Compare > void std::__move_median_to_first (_Iterator __result, _Iterator __a, _Iterator __b, _Iterator __c, _Compare __comp)
Swaps the median value of *__a, *__b and *__c under __comp to *__result.
Definition at line 78 of file stl_algo.h.
References iter_swap().
Referenced by __unguarded_partition_pivot().
template<typename _InputIterator , typename _OutputIterator , typename _Compare > _OutputIterator std::__move_merge (_InputIterator __first1, _InputIterator __last1, _InputIterator __first2, _InputIterator __last2, _OutputIterator __result, _Compare __comp)
This is a helper function for the __merge_sort_loop routines.
Definition at line 2649 of file stl_algo.h.
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator , typename _Compare > void std::__move_merge_adaptive (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result, _Compare __comp)
This is a helper function for the __merge_adaptive routines.
Definition at line 2316 of file stl_algo.h.
Referenced by __merge_adaptive().
template<typename _BidirectionalIterator1 , typename _BidirectionalIterator2 , typename _BidirectionalIterator3 , typename _Compare > void std::__move_merge_adaptive_backward (_BidirectionalIterator1 __first1, _BidirectionalIterator1 __last1, _BidirectionalIterator2 __first2, _BidirectionalIterator2 __last2, _BidirectionalIterator3 __result, _Compare __comp)
This is a helper function for the __merge_adaptive routines.
Definition at line 2342 of file stl_algo.h.
Referenced by __merge_adaptive().
template<typename _ForwardIterator , typename _Predicate > _ForwardIterator std::__partition (_ForwardIterator __first, _ForwardIterator __last, _Predicate __pred, forward_iterator_tag)
This is a helper function...
Definition at line 1485 of file stl_algo.h.
References iter_swap().
Referenced by partition().
template<typename _BidirectionalIterator , typename _Predicate > _BidirectionalIterator std::__partition (_BidirectionalIterator __first, _BidirectionalIterator __last, _Predicate __pred, bidirectional_iterator_tag)
This is a helper function...
Definition at line 1510 of file stl_algo.h.
References iter_swap().
template<typename _BidirectionalIterator > void std::__reverse (_BidirectionalIterator __first, _BidirectionalIterator __last, bidirectional_iterator_tag)
This is an uglified reverse(_BidirectionalIterator, _BidirectionalIterator) overloaded for bidirectional iterators.
Definition at line 1129 of file stl_algo.h.
References iter_swap().
Referenced by reverse().
template<typename _RandomAccessIterator > void std::__reverse (_RandomAccessIterator __first, _RandomAccessIterator __last, random_access_iterator_tag)
This is an uglified reverse(_BidirectionalIterator, _BidirectionalIterator) overloaded for random access iterators.
Definition at line 1149 of file stl_algo.h.
References iter_swap().
template<typename _BidirectionalIterator1 , typename _BidirectionalIterator2 , typename _Distance > _BidirectionalIterator1 std::__rotate_adaptive (_BidirectionalIterator1 __first, _BidirectionalIterator1 __middle, _BidirectionalIterator1 __last, _Distance __len1, _Distance __len2, _BidirectionalIterator2 __buffer, _Distance __buffer_size)
This is a helper function for the merge routines.
Definition at line 2385 of file stl_algo.h.
References advance(), distance(), and std::_V2::rotate().
Referenced by __merge_adaptive().
template<typename _ForwardIterator , typename _Integer , typename _UnaryPredicate > _ForwardIterator std::__search_n_aux (_ForwardIterator __first, _ForwardIterator __last, _Integer __count, _UnaryPredicate __unary_pred, std::forward_iterator_tag)
This is an helper function for search_n overloaded for forward iterators.
Definition at line 257 of file stl_algo.h.
References __find_if().
template<typename _RandomAccessIter , typename _Integer , typename _UnaryPredicate > _RandomAccessIter std::__search_n_aux (_RandomAccessIter __first, _RandomAccessIter __last, _Integer __count, _UnaryPredicate __unary_pred, std::random_access_iterator_tag)
This is an helper function for search_n overloaded for random access iterators.
Definition at line 289 of file stl_algo.h.
template<typename _ForwardIterator , typename _Pointer , typename _Predicate , typename _Distance > _ForwardIterator std::__stable_partition_adaptive (_ForwardIterator __first, _ForwardIterator __last, _Predicate __pred, _Distance __len, _Pointer __buffer, _Distance __buffer_size)
This is a helper function... Requires __first != __last and !__pred(__first) and __len == distance(__first, __last).
!__pred(__first) allows us to guarantee that we don't move-assign an element onto itself.
Definition at line 1546 of file stl_algo.h.
References __find_if_not_n(), advance(), distance(), and std::_V2::rotate().
template<typename _RandomAccessIterator , typename _Compare > void std::__unguarded_insertion_sort (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp) inline
This is a helper function for the sort routine.
Definition at line 1858 of file stl_algo.h.
References __unguarded_linear_insert().
Referenced by __final_insertion_sort().
template<typename _RandomAccessIterator , typename _Compare > void std::__unguarded_linear_insert (_RandomAccessIterator __last, _Compare __comp)
This is a helper function for the sort routine.
Definition at line 1816 of file stl_algo.h.
Referenced by __insertion_sort(), and __unguarded_insertion_sort().
template<typename _RandomAccessIterator , typename _Compare > _RandomAccessIterator std::__unguarded_partition (_RandomAccessIterator __first, _RandomAccessIterator __last, _RandomAccessIterator __pivot, _Compare __comp)
This is a helper function...
Definition at line 1891 of file stl_algo.h.
References iter_swap().
Referenced by __unguarded_partition_pivot().
template<typename _RandomAccessIterator , typename _Compare > _RandomAccessIterator std::__unguarded_partition_pivot (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp) inline
This is a helper function...
Definition at line 1912 of file stl_algo.h.
References __move_median_to_first(), and __unguarded_partition().
Referenced by __introsort_loop().
template<typename _ForwardIterator , typename _OutputIterator , typename _BinaryPredicate > _OutputIterator std::__unique_copy (_ForwardIterator __first, _ForwardIterator __last, _OutputIterator __result, _BinaryPredicate __binary_pred, forward_iterator_tag , output_iterator_tag)
This is an uglified unique_copy(_InputIterator, _InputIterator, _OutputIterator, _BinaryPredicate) overloaded for forward iterators and output iterator as result.
Definition at line 1046 of file stl_algo.h.
Referenced by unique_copy().
template<typename _InputIterator , typename _OutputIterator , typename _BinaryPredicate > _OutputIterator std::__unique_copy (_InputIterator __first, _InputIterator __last, _OutputIterator __result, _BinaryPredicate __binary_pred, input_iterator_tag , output_iterator_tag)
This is an uglified unique_copy(_InputIterator, _InputIterator, _OutputIterator, _BinaryPredicate) overloaded for input iterators and output iterator as result.
Definition at line 1075 of file stl_algo.h.
template<typename _InputIterator , typename _ForwardIterator , typename _BinaryPredicate > _ForwardIterator std::__unique_copy (_InputIterator __first, _InputIterator __last, _ForwardIterator __result, _BinaryPredicate __binary_pred, input_iterator_tag , forward_iterator_tag)
This is an uglified unique_copy(_InputIterator, _InputIterator, _OutputIterator, _BinaryPredicate) overloaded for input iterators and forward iterator as result.
Definition at line 1107 of file stl_algo.h.
template<typename _T1 , typename... _Args> void std::_Construct (_T1 * __p, _Args &&... __args) inline
Constructs an object in existing memory by invoking an allocated object's constructor with an initializer.
Definition at line 74 of file stl_construct.h.
template<typename _Tp > void std::_Destroy (_Tp * __pointer) inline
Destroy the object pointed to by a pointer type.
Definition at line 92 of file stl_construct.h.
Referenced by std::vector< sub_match< _Bi_iter >, allocator< sub_match< _Bi_iter > > >::~vector().
template<typename _ForwardIterator > void std::_Destroy (_ForwardIterator __first, _ForwardIterator __last) inline
Destroy a range of objects. If the value_type of the object has a trivial destructor, the compiler should optimize all of this away, otherwise the objects' destructors must be invoked.
Definition at line 122 of file stl_construct.h.
template<typename _ForwardIterator , typename _Allocator > void std::_Destroy (_ForwardIterator __first, _ForwardIterator __last, _Allocator & __alloc)
Destroy a range of objects using the supplied allocator. For nondefault allocators we do not optimize away invocation of destroy() even if _Tp has a trivial destructor.
Definition at line 138 of file stl_construct.h.
References __addressof().
template<typename _InputIterator , typename _Tp > _Tp std::accumulate (_InputIterator __first, _InputIterator __last, _Tp __init) inline
Accumulate values in a range.
Accumulates the values in the range [first,last) using operator+(). The initial value is init. The values are processed in order.
Parameters
__first Start of range.
__last End of range.
__init Starting value to add other values to.
Returns
The final sum.
Definition at line 120 of file stl_numeric.h.
Referenced by __gnu_parallel::__parallel_partial_sum_linear().
template<typename _InputIterator , typename _Tp , typename _BinaryOperation > _Tp std::accumulate (_InputIterator __first, _InputIterator __last, _Tp __init, _BinaryOperation __binary_op) inline
Accumulate values in a range with operation.
Accumulates the values in the range [first,last) using the function object __binary_op. The initial value is __init. The values are processed in order.
Parameters
__first Start of range.
__last End of range.
__init Starting value to add other values to.
__binary_op Function object to accumulate with.
Returns
The final sum.
Definition at line 146 of file stl_numeric.h.
template<typename _InputIterator , typename _OutputIterator > _OutputIterator std::adjacent_difference (_InputIterator __first, _InputIterator __last, _OutputIterator __result)
Return differences between adjacent values.
Computes the difference between adjacent values in the range [first,last) using operator-() and writes the result to __result.
Parameters
__first Start of input range.
__last End of input range.
__result Output sums.
Returns
Iterator pointing just beyond the values written to result.
_GLIBCXX_RESOLVE_LIB_DEFECTS DR 539. partial_sum and adjacent_difference should mention requirements
Definition at line 317 of file stl_numeric.h.
template<typename _InputIterator , typename _OutputIterator , typename _BinaryOperation > _OutputIterator std::adjacent_difference (_InputIterator __first, _InputIterator __last, _OutputIterator __result, _BinaryOperation __binary_op)
Return differences between adjacent values.
Computes the difference between adjacent values in the range [__first,__last) using the function object __binary_op and writes the result to __result.
Parameters
__first Start of input range.
__last End of input range.
__result Output sum.
__binary_op Function object.
Returns
Iterator pointing just beyond the values written to result.
_GLIBCXX_RESOLVE_LIB_DEFECTS DR 539. partial_sum and adjacent_difference should mention requirements
Definition at line 360 of file stl_numeric.h.
template<typename _InputIterator , typename _Distance > void std::advance (_InputIterator & __i, _Distance __n) inline
A generalization of pointer arithmetic.
Parameters
__i An input iterator.
__n The delta by which to change __i.
Returns
Nothing.
This increments i by n. For bidirectional and random access iterators, __n may be negative, in which case __i is decremented.
For random access iterators, this uses their + and - operations and are constant time. For other iterator classes they are linear time.
Definition at line 173 of file stl_iterator_base_funcs.h.
References __iterator_category().
Referenced by __merge_adaptive(), __merge_without_buffer(), __rotate_adaptive(), __stable_partition_adaptive(), __gnu_pbds::detail::pat_trie_base::_Node_citer< Node, Leaf, Head, Inode, _CIterator, Iterator, _Alloc >::get_child(), __gnu_pbds::detail::pat_trie_base::_Node_iter< Node, Leaf, Head, Inode, _CIterator, Iterator, _Alloc >::get_child(), and partition_point().
template<class _Container > auto std::begin (_Container & __cont) -> decltype(__cont.begin()) inline
Return an iterator pointing to the first element of the container.
Parameters
__cont Container.
Definition at line 48 of file range_access.h.
Referenced by __gnu_pbds::detail::pat_trie_base::_Node_iter< Node, Leaf, Head, Inode, _CIterator, Iterator, _Alloc >::get_child().
template<class _Container > auto std::begin (const _Container & __cont) -> decltype(__cont.begin()) inline
Return an iterator pointing to the first element of the const container.
Parameters
__cont Container.
Definition at line 58 of file range_access.h.
template<class _Tp , size_t _Nm> _GLIBCXX14_CONSTEXPR _Tp* std::begin (_Tp(&) __arr[_Nm]) inline
Return an iterator pointing to the first element of the array.
Parameters
__arr Array.
Definition at line 87 of file range_access.h.
ios_base& std::boolalpha (ios_base & __base) inline
Calls base.setf(ios_base::boolalpha).
Definition at line 878 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::boolalpha, and std::ios_base::setf().
template<typename _Tp , typename _Tp1 , _Lock_policy _Lp> __shared_ptr<_Tp, _Lp> std::const_pointer_cast (const __shared_ptr< _Tp1, _Lp > & __r) inline noexcept
const_pointer_cast
Definition at line 1321 of file shared_ptr_base.h.
ios_base& std::dec (ios_base & __base) inline
Calls base.setf(ios_base::dec, ios_base::basefield).
Definition at line 1016 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::basefield, std::ios_base::dec, and std::ios_base::setf().
ios_base& std::defaultfloat (ios_base & __base) inline
Calls base.unsetf(ios_base::floatfield)
Definition at line 1069 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::floatfield, and std::ios_base::unsetf().
template<typename _InputIterator > iterator_traits<_InputIterator>::difference_type std::distance (_InputIterator __first, _InputIterator __last) inline
A generalization of pointer arithmetic.
Parameters
__first An input iterator.
__last An input iterator.
Returns
The distance between them.
Returns n such that __first + n == __last. This requires that __last must be reachable from __first. Note that n may be negative.
For random access iterators, this uses their + and - operations and are constant time. For other iterator classes they are linear time.
Definition at line 114 of file stl_iterator_base_funcs.h.
References __iterator_category().
Referenced by __merge_adaptive(), __merge_without_buffer(), __rotate_adaptive(), __stable_partition_adaptive(), is_heap_until(), std::sub_match< _Bi_iter >::length(), __gnu_parallel::multiseq_partition(), __gnu_parallel::multiseq_selection(), __gnu_pbds::detail::pat_trie_base::_Node_citer< Node, Leaf, Head, Inode, _CIterator, Iterator, _Alloc >::num_children(), partition_point(), and std::match_results< _Bi_iter >::position().
template<typename _Tp , typename _Tp1 , _Lock_policy _Lp> __shared_ptr<_Tp, _Lp> std::dynamic_pointer_cast (const __shared_ptr< _Tp1, _Lp > & __r) inline noexcept
dynamic_pointer_cast
Definition at line 1331 of file shared_ptr_base.h.
template<class _Container > auto std::end (_Container & __cont) -> decltype(__cont.end()) inline
Return an iterator pointing to one past the last element of the container.
Parameters
__cont Container.
Definition at line 68 of file range_access.h.
template<class _Container > auto std::end (const _Container & __cont) -> decltype(__cont.end()) inline
Return an iterator pointing to one past the last element of the const container.
Parameters
__cont Container.
Definition at line 78 of file range_access.h.
template<class _Tp , size_t _Nm> _GLIBCXX14_CONSTEXPR _Tp* std::end (_Tp(&) __arr[_Nm]) inline
Return an iterator pointing to one past the last element of the array.
Parameters
__arr Array.
Definition at line 97 of file range_access.h.
ios_base& std::fixed (ios_base & __base) inline
Calls base.setf(ios_base::fixed, ios_base::floatfield).
Definition at line 1041 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::fixed, std::ios_base::floatfield, and std::ios_base::setf().
template<typename _Tp > pair<_Tp*, ptrdiff_t> std::get_temporary_buffer (ptrdiff_t __len) noexcept
Allocates a temporary buffer.
Parameters
__len The number of objects of type Tp.
Returns
See full description.
Reinventing the wheel, but this time with prettier spokes!
This function tries to obtain storage for __len adjacent Tp objects. The objects themselves are not constructed, of course. A pair<> is returned containing the buffer s address and capacity (in the units of sizeof(_Tp)), or a pair of 0 values if no storage can be obtained. Note that the capacity obtained may be less than that requested if the memory is unavailable; you should compare len with the .second return value.
Provides the nothrow exception guarantee.
Definition at line 85 of file stl_tempbuf.h.
Referenced by std::_Temporary_buffer< _ForwardIterator, _Tp >::_Temporary_buffer().
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> basic_istream<_CharT, _Traits>& std::getline (basic_istream< _CharT, _Traits > & __is, __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base > & __str, _CharT __delim)
Read a line from stream into a string.
Parameters
__is Input stream.
__str Buffer to store into.
__delim Character marking end of line.
Returns
Reference to the input stream.
Stores characters from __is into __str until __delim is found, the end of the stream is encountered, or str.max_size() is reached. If is.width() is non-zero, that is the limit on the number of characters stored into __str. Any previous contents of __str are erased. If delim was encountered, it is extracted but not stored into __str.
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> basic_istream<_CharT, _Traits>& std::getline (basic_istream< _CharT, _Traits > & __is, __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base > & __str) inline
Read a line from stream into a string.
Parameters
__is Input stream.
__str Buffer to store into.
Returns
Reference to the input stream.
Stores characters from is into __str until '
' is found, the end of the stream is encountered, or str.max_size() is reached. If is.width() is non-zero, that is the limit on the number of characters stored into __str. Any previous contents of __str are erased. If end of line was encountered, it is extracted but not stored into __str.
Definition at line 2676 of file vstring.h.
References getline().
template<typename _CharT , typename _Traits , typename _Alloc > basic_istream<_CharT, _Traits>& std::getline (basic_istream< _CharT, _Traits > & __is, basic_string< _CharT, _Traits, _Alloc > & __str, _CharT __delim)
Read a line from stream into a string.
Parameters
__is Input stream.
__str Buffer to store into.
__delim Character marking end of line.
Returns
Reference to the input stream.
Stores characters from __is into __str until __delim is found, the end of the stream is encountered, or str.max_size() is reached. Any previous contents of __str are erased. If __delim is encountered, it is extracted but not stored into __str.
Referenced by getline().
template<typename _CharT , typename _Traits , typename _Alloc > basic_istream<_CharT, _Traits>& std::getline (basic_istream< _CharT, _Traits > & __is, basic_string< _CharT, _Traits, _Alloc > & __str) inline
Read a line from stream into a string.
Parameters
__is Input stream.
__str Buffer to store into.
Returns
Reference to the input stream.
Stores characters from is into __str until '
' is found, the end of the stream is encountered, or str.max_size() is reached. Any previous contents of __str are erased. If end of line is encountered, it is extracted but not stored into __str.
Definition at line 5214 of file basic_string.h.
References getline().
template<typename _CharT , typename _Traits , typename _Alloc > basic_istream<_CharT, _Traits>& std::getline (basic_istream< _CharT, _Traits > && __is, basic_string< _CharT, _Traits, _Alloc > & __str, _CharT __delim) inline
Read a line from an rvalue stream into a string.
Definition at line 5222 of file basic_string.h.
References getline().
template<typename _CharT , typename _Traits , typename _Alloc > basic_istream<_CharT, _Traits>& std::getline (basic_istream< _CharT, _Traits > && __is, basic_string< _CharT, _Traits, _Alloc > & __str) inline
Read a line from an rvalue stream into a string.
Definition at line 5229 of file basic_string.h.
References getline().
ios_base& std::hex (ios_base & __base) inline
Calls base.setf(ios_base::hex, ios_base::basefield).
Definition at line 1024 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::basefield, std::ios_base::hex, and std::ios_base::setf().
ios_base& std::hexfloat (ios_base & __base) inline
Calls base.setf(ios_base::fixed|ios_basescientific, ios_base::floatfield)
Definition at line 1061 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::fixed, std::ios_base::floatfield, std::ios_base::scientific, and std::ios_base::setf().
template<typename _InputIterator1 , typename _InputIterator2 , typename _Tp > _Tp std::inner_product (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _Tp __init) inline
Compute inner product of two ranges.
Starting with an initial value of __init, multiplies successive elements from the two ranges and adds each product into the accumulated value using operator+(). The values in the ranges are processed in order.
Parameters
__first1 Start of range 1.
__last1 End of range 1.
__first2 Start of range 2.
__init Starting value to add other values to.
Returns
The final inner product.
Definition at line 174 of file stl_numeric.h.
template<typename _InputIterator1 , typename _InputIterator2 , typename _Tp , typename _BinaryOperation1 , typename _BinaryOperation2 > _Tp std::inner_product (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _Tp __init, _BinaryOperation1 __binary_op1, _BinaryOperation2 __binary_op2) inline
Compute inner product of two ranges.
Starting with an initial value of __init, applies __binary_op2 to successive elements from the two ranges and accumulates each result into the accumulated value using __binary_op1. The values in the ranges are processed in order.
Parameters
__first1 Start of range 1.
__last1 End of range 1.
__first2 Start of range 2.
__init Starting value to add other values to.
__binary_op1 Function object to accumulate with.
__binary_op2 Function object to apply to pairs of input values.
Returns
The final inner product.
Definition at line 206 of file stl_numeric.h.
ios_base& std::internal (ios_base & __base) inline
Calls base.setf(ios_base::internal, ios_base::adjustfield).
Definition at line 991 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::adjustfield, and std::ios_base::internal.
template<typename _ForwardIterator , typename _Tp > void std::iota (_ForwardIterator __first, _ForwardIterator __last, _Tp __value)
Create a range of sequentially increasing values.
For each element in the range [first,last) assigns value and increments value as if by ++value.
Parameters
__first Start of range.
__last End of range.
__value Starting value.
Returns
Nothing.
Definition at line 82 of file stl_numeric.h.
template<typename _CharT > bool std::isalnum (_CharT __c, const locale & __loc) inline
Convenience interface to ctype.is(ctype_base::alnum, __c).
Definition at line 2619 of file locale_facets.h.
template<typename _CharT > bool std::isalpha (_CharT __c, const locale & __loc) inline
Convenience interface to ctype.is(ctype_base::alpha, __c).
Definition at line 2595 of file locale_facets.h.
template<typename _CharT > bool std::isblank (_CharT __c, const locale & __loc) inline
Convenience interface to ctype.is(ctype_base::blank, __c).
Definition at line 2632 of file locale_facets.h.
template<typename _CharT > bool std::iscntrl (_CharT __c, const locale & __loc) inline
Convenience interface to ctype.is(ctype_base::cntrl, __c).
Definition at line 2577 of file locale_facets.h.
template<typename _CharT > bool std::isdigit (_CharT __c, const locale & __loc) inline
Convenience interface to ctype.is(ctype_base::digit, __c).
Definition at line 2601 of file locale_facets.h.
template<typename _CharT > bool std::isgraph (_CharT __c, const locale & __loc) inline
Convenience interface to ctype.is(ctype_base::graph, __c).
Definition at line 2625 of file locale_facets.h.
template<typename _CharT > bool std::islower (_CharT __c, const locale & __loc) inline
Convenience interface to ctype.is(ctype_base::lower, __c).
Definition at line 2589 of file locale_facets.h.
template<typename _CharT > bool std::isprint (_CharT __c, const locale & __loc) inline
Convenience interface to ctype.is(ctype_base::print, __c).
Definition at line 2571 of file locale_facets.h.
template<typename _CharT > bool std::ispunct (_CharT __c, const locale & __loc) inline
Convenience interface to ctype.is(ctype_base::punct, __c).
Definition at line 2607 of file locale_facets.h.
template<typename _CharT > bool std::isspace (_CharT __c, const locale & __loc) inline
Convenience interface to ctype.is(ctype_base::space, __c).
Definition at line 2565 of file locale_facets.h.
template<typename _CharT > bool std::isupper (_CharT __c, const locale & __loc) inline
Convenience interface to ctype.is(ctype_base::upper, __c).
Definition at line 2583 of file locale_facets.h.
template<typename _CharT > bool std::isxdigit (_CharT __c, const locale & __loc) inline
Convenience interface to ctype.is(ctype_base::xdigit, __c).
Definition at line 2613 of file locale_facets.h.
ios_base& std::left (ios_base & __base) inline
Calls base.setf(ios_base::left, ios_base::adjustfield).
Definition at line 999 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::adjustfield, std::ios_base::left, and std::ios_base::setf().
ios_base& std::noboolalpha (ios_base & __base) inline
Calls base.unsetf(ios_base::boolalpha).
Definition at line 886 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::boolalpha, and std::ios_base::unsetf().
ios_base& std::noshowbase (ios_base & __base) inline
Calls base.unsetf(ios_base::showbase).
Definition at line 902 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::showbase, and std::ios_base::unsetf().
ios_base& std::noshowpoint (ios_base & __base) inline
Calls base.unsetf(ios_base::showpoint).
Definition at line 918 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::showpoint, and std::ios_base::unsetf().
ios_base& std::noshowpos (ios_base & __base) inline
Calls base.unsetf(ios_base::showpos).
Definition at line 934 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::showpos, and std::ios_base::unsetf().
ios_base& std::noskipws (ios_base & __base) inline
Calls base.unsetf(ios_base::skipws).
Definition at line 950 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::skipws, and std::ios_base::unsetf().
ios_base& std::nounitbuf (ios_base & __base) inline
Calls base.unsetf(ios_base::unitbuf).
Definition at line 982 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::unitbuf, and std::ios_base::unsetf().
ios_base& std::nouppercase (ios_base & __base) inline
Calls base.unsetf(ios_base::uppercase).
Definition at line 966 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::unsetf(), and std::ios_base::uppercase.
ios_base& std::oct (ios_base & __base) inline
Calls base.setf(ios_base::oct, ios_base::basefield).
Definition at line 1032 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::basefield, std::ios_base::oct, and std::ios_base::setf().
template<typename _Tp > bool std::operator!= (const _Fwd_list_iterator< _Tp > & __x, const _Fwd_list_const_iterator< _Tp > & __y) inline noexcept
Forward list iterator inequality comparison.
Definition at line 266 of file forward_list.h.
template<typename _Tp , typename _Seq > bool std::operator!= (const stack< _Tp, _Seq > & __x, const stack< _Tp, _Seq > & __y) inline
Based on operator==.
Definition at line 270 of file stl_stack.h.
template<typename _Tp , typename _Seq > bool std::operator!= (const queue< _Tp, _Seq > & __x, const queue< _Tp, _Seq > & __y) inline
Based on operator==.
Definition at line 295 of file stl_queue.h.
template<typename _Key , typename _Compare , typename _Alloc > bool std::operator!= (const multiset< _Key, _Compare, _Alloc > & __x, const multiset< _Key, _Compare, _Alloc > & __y) inline
Returns !(x == y).
Definition at line 849 of file stl_multiset.h.
template<typename _Key , typename _Compare , typename _Alloc > bool std::operator!= (const set< _Key, _Compare, _Alloc > & __x, const set< _Key, _Compare, _Alloc > & __y) inline
Returns !(x == y).
Definition at line 866 of file stl_set.h.
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool std::operator!= (const multimap< _Key, _Tp, _Compare, _Alloc > & __x, const multimap< _Key, _Tp, _Compare, _Alloc > & __y) inline
Based on operator==.
Definition at line 998 of file stl_multimap.h.
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool std::operator!= (const map< _Key, _Tp, _Compare, _Alloc > & __x, const map< _Key, _Tp, _Compare, _Alloc > & __y) inline
Based on operator==.
Definition at line 1097 of file stl_map.h.
template<typename _Tp , typename _Alloc > bool std::operator!= (const forward_list< _Tp, _Alloc > & __lx, const forward_list< _Tp, _Alloc > & __ly) inline
Based on operator==.
Definition at line 1368 of file forward_list.h.
template<typename _Tp , typename _Alloc > bool std::operator!= (const vector< _Tp, _Alloc > & __x, const vector< _Tp, _Alloc > & __y) inline
Based on operator==.
Definition at line 1535 of file stl_vector.h.
template<typename _Tp , typename _Alloc > bool std::operator!= (const list< _Tp, _Alloc > & __x, const list< _Tp, _Alloc > & __y) inline
Based on operator==.
Definition at line 1843 of file stl_list.h.
template<typename _Tp , typename _Alloc > bool std::operator!= (const deque< _Tp, _Alloc > & __x, const deque< _Tp, _Alloc > & __y) inline
Based on operator==.
Definition at line 2246 of file stl_deque.h.
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator!= (const basic_string< _CharT, _Traits, _Alloc > & __lhs, const basic_string< _CharT, _Traits, _Alloc > & __rhs) inline
Test difference of two strings.
Parameters
__lhs First string.
__rhs Second string.
Returns
True if __lhs.compare(__rhs) != 0. False otherwise.
Definition at line 4952 of file basic_string.h.
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator!= (const _CharT * __lhs, const basic_string< _CharT, _Traits, _Alloc > & __rhs) inline
Test difference of C string and string.
Parameters
__lhs C string.
__rhs String.
Returns
True if __rhs.compare(__lhs) != 0. False otherwise.
Definition at line 4964 of file basic_string.h.
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator!= (const basic_string< _CharT, _Traits, _Alloc > & __lhs, const _CharT * __rhs) inline
Test difference of string and C string.
Parameters
__lhs String.
__rhs C string.
Returns
True if __lhs.compare(__rhs) != 0. False otherwise.
Definition at line 4976 of file basic_string.h.
template<typename _CharT , typename _Traits , typename _Alloc > basic_string<_CharT, _Traits, _Alloc> std::operator+ (const basic_string< _CharT, _Traits, _Alloc > & __lhs, const basic_string< _CharT, _Traits, _Alloc > & __rhs)
Concatenate two strings.
Parameters
__lhs First string.
__rhs Last string.
Returns
New string with value of __lhs followed by __rhs.
Definition at line 4785 of file basic_string.h.
template<typename _CharT , typename _Traits , typename _Alloc > basic_string<_CharT,_Traits,_Alloc> std::operator+ (const _CharT * __lhs, const basic_string< _CharT, _Traits, _Alloc > & __rhs)
Concatenate C string and string.
Parameters
__lhs First string.
__rhs Last string.
Returns
New string with value of __lhs followed by __rhs.
template<typename _CharT , typename _Traits , typename _Alloc > basic_string<_CharT,_Traits,_Alloc> std::operator+ (_CharT __lhs, const basic_string< _CharT, _Traits, _Alloc > & __rhs)
Concatenate character and string.
Parameters
__lhs First string.
__rhs Last string.
Returns
New string with __lhs followed by __rhs.
template<typename _CharT , typename _Traits , typename _Alloc > basic_string<_CharT, _Traits, _Alloc> std::operator+ (const basic_string< _CharT, _Traits, _Alloc > & __lhs, const _CharT * __rhs) inline
Concatenate string and C string.
Parameters
__lhs First string.
__rhs Last string.
Returns
New string with __lhs followed by __rhs.
Definition at line 4822 of file basic_string.h.
template<typename _CharT , typename _Traits , typename _Alloc > basic_string<_CharT, _Traits, _Alloc> std::operator+ (const basic_string< _CharT, _Traits, _Alloc > & __lhs, _CharT __rhs) inline
Concatenate string and character.
Parameters
__lhs First string.
__rhs Last string.
Returns
New string with __lhs followed by __rhs.
Definition at line 4838 of file basic_string.h.
template<typename _Tp , typename _Seq > bool std::operator< (const stack< _Tp, _Seq > & __x, const stack< _Tp, _Seq > & __y) inline
Stack ordering relation.
Parameters
__x A stack.
__y A stack of the same type as x.
Returns
True iff x is lexicographically less than __y.
This is an total ordering relation. Complexity and semantics depend on the underlying sequence type, but the expected rules are: this relation is linear in the size of the sequences, the elements must be comparable with <, and std::lexicographical_compare() is usually used to make the determination.
Definition at line 264 of file stl_stack.h.
template<typename _Tp , typename _Seq > bool std::operator< (const queue< _Tp, _Seq > & __x, const queue< _Tp, _Seq > & __y) inline
Queue ordering relation.
Parameters
__x A queue.
__y A queue of the same type as x.
Returns
True iff __x is lexicographically less than __y.
This is an total ordering relation. Complexity and semantics depend on the underlying sequence type, but the expected rules are: this relation is linear in the size of the sequences, the elements must be comparable with <, and std::lexicographical_compare() is usually used to make the determination.
Definition at line 289 of file stl_queue.h.
References std::queue< _Tp, _Sequence >::c.
template<typename _Key , typename _Compare , typename _Alloc > bool std::operator< (const multiset< _Key, _Compare, _Alloc > & __x, const multiset< _Key, _Compare, _Alloc > & __y) inline
Multiset ordering relation.
Parameters
__x A multiset.
__y A multiset of the same type as __x.
Returns
True iff __x is lexicographically less than __y.
This is a total ordering relation. It is linear in the size of the sets. The elements must be comparable with <.
See std::lexicographical_compare() for how the determination is made.
Definition at line 842 of file stl_multiset.h.
template<typename _Key , typename _Compare , typename _Alloc > bool std::operator< (const set< _Key, _Compare, _Alloc > & __x, const set< _Key, _Compare, _Alloc > & __y) inline
Set ordering relation.
Parameters
__x A set.
__y A set of the same type as x.
Returns
True iff __x is lexicographically less than __y.
This is a total ordering relation. It is linear in the size of the sets. The elements must be comparable with <.
See std::lexicographical_compare() for how the determination is made.
Definition at line 859 of file stl_set.h.
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool std::operator< (const multimap< _Key, _Tp, _Compare, _Alloc > & __x, const multimap< _Key, _Tp, _Compare, _Alloc > & __y) inline
Multimap ordering relation.
Parameters
__x A multimap.
__y A multimap of the same type as __x.
Returns
True iff x is lexicographically less than y.
This is a total ordering relation. It is linear in the size of the multimaps. The elements must be comparable with <.
See std::lexicographical_compare() for how the determination is made.
Definition at line 991 of file stl_multimap.h.
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool std::operator< (const map< _Key, _Tp, _Compare, _Alloc > & __x, const map< _Key, _Tp, _Compare, _Alloc > & __y) inline
Map ordering relation.
Parameters
__x A map.
__y A map of the same type as x.
Returns
True iff x is lexicographically less than y.
This is a total ordering relation. It is linear in the size of the maps. The elements must be comparable with <.
See std::lexicographical_compare() for how the determination is made.
Definition at line 1090 of file stl_map.h.
template<typename _Tp , typename _Alloc > bool std::operator< (const forward_list< _Tp, _Alloc > & __lx, const forward_list< _Tp, _Alloc > & __ly) inline
Forward list ordering relation.
Parameters
__lx A forward_list.
__ly A forward_list of the same type as __lx.
Returns
True iff __lx is lexicographically less than __ly.
This is a total ordering relation. It is linear in the number of elements of the forward lists. The elements must be comparable with <.
See std::lexicographical_compare() for how the determination is made.
Definition at line 1360 of file forward_list.h.
References lexicographical_compare().
template<typename _Tp , typename _Alloc > bool std::operator< (const vector< _Tp, _Alloc > & __x, const vector< _Tp, _Alloc > & __y) inline
Vector ordering relation.
Parameters
__x A vector.
__y A vector of the same type as __x.
Returns
True iff __x is lexicographically less than __y.
This is a total ordering relation. It is linear in the size of the vectors. The elements must be comparable with <.
See std::lexicographical_compare() for how the determination is made.
Definition at line 1528 of file stl_vector.h.
References lexicographical_compare().
template<typename _Tp , typename _Alloc > bool std::operator< (const list< _Tp, _Alloc > & __x, const list< _Tp, _Alloc > & __y) inline
List ordering relation.
Parameters
__x A list.
__y A list of the same type as __x.
Returns
True iff __x is lexicographically less than __y.
This is a total ordering relation. It is linear in the size of the lists. The elements must be comparable with <.
See std::lexicographical_compare() for how the determination is made.
Definition at line 1836 of file stl_list.h.
References lexicographical_compare().
template<typename _Tp , typename _Alloc > bool std::operator< (const deque< _Tp, _Alloc > & __x, const deque< _Tp, _Alloc > & __y) inline
Deque ordering relation.
Parameters
__x A deque.
__y A deque of the same type as __x.
Returns
True iff x is lexicographically less than __y.
This is a total ordering relation. It is linear in the size of the deques. The elements must be comparable with <.
See std::lexicographical_compare() for how the determination is made.
Definition at line 2238 of file stl_deque.h.
References lexicographical_compare().
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator< (const basic_string< _CharT, _Traits, _Alloc > & __lhs, const basic_string< _CharT, _Traits, _Alloc > & __rhs) inline
Test if string precedes string.
Parameters
__lhs First string.
__rhs Second string.
Returns
True if __lhs precedes __rhs. False otherwise.
Definition at line 4989 of file basic_string.h.
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator< (const basic_string< _CharT, _Traits, _Alloc > & __lhs, const _CharT * __rhs) inline
Test if string precedes C string.
Parameters
__lhs String.
__rhs C string.
Returns
True if __lhs precedes __rhs. False otherwise.
Definition at line 5001 of file basic_string.h.
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator< (const _CharT * __lhs, const basic_string< _CharT, _Traits, _Alloc > & __rhs) inline
Test if C string precedes string.
Parameters
__lhs C string.
__rhs String.
Returns
True if __lhs precedes __rhs. False otherwise.
Definition at line 5013 of file basic_string.h.
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> basic_ostream<_CharT, _Traits>& std::operator<< (basic_ostream< _CharT, _Traits > & __os, const __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base > & __str) inline
Write string to a stream.
Parameters
__os Output stream.
__str String to write out.
Returns
Reference to the output stream.
Output characters of __str into os following the same rules as for writing a C string.
Definition at line 2630 of file vstring.h.
References __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base >::data(), and __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base >::size().
template<typename _CharT , typename _Traits , typename _Alloc > basic_ostream<_CharT, _Traits>& std::operator<< (basic_ostream< _CharT, _Traits > & __os, const basic_string< _CharT, _Traits, _Alloc > & __str) inline
Write string to a stream.
Parameters
__os Output stream.
__str String to write out.
Returns
Reference to the output stream.
Output characters of __str into os following the same rules as for writing a C string.
Definition at line 5174 of file basic_string.h.
template<typename _Tp , typename _Seq > bool std::operator<= (const stack< _Tp, _Seq > & __x, const stack< _Tp, _Seq > & __y) inline
Based on operator<.
Definition at line 282 of file stl_stack.h.
template<typename _Tp , typename _Seq > bool std::operator<= (const queue< _Tp, _Seq > & __x, const queue< _Tp, _Seq > & __y) inline
Based on operator<.
Definition at line 307 of file stl_queue.h.
template<typename _Key , typename _Compare , typename _Alloc > bool std::operator<= (const multiset< _Key, _Compare, _Alloc > & __x, const multiset< _Key, _Compare, _Alloc > & __y) inline
Returns !(y < x)
Definition at line 863 of file stl_multiset.h.
template<typename _Key , typename _Compare , typename _Alloc > bool std::operator<= (const set< _Key, _Compare, _Alloc > & __x, const set< _Key, _Compare, _Alloc > & __y) inline
Returns !(y < x)
Definition at line 880 of file stl_set.h.
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool std::operator<= (const multimap< _Key, _Tp, _Compare, _Alloc > & __x, const multimap< _Key, _Tp, _Compare, _Alloc > & __y) inline
Based on operator<.
Definition at line 1012 of file stl_multimap.h.
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool std::operator<= (const map< _Key, _Tp, _Compare, _Alloc > & __x, const map< _Key, _Tp, _Compare, _Alloc > & __y) inline
Based on operator<.
Definition at line 1111 of file stl_map.h.
template<typename _Tp , typename _Alloc > bool std::operator<= (const forward_list< _Tp, _Alloc > & __lx, const forward_list< _Tp, _Alloc > & __ly) inline
Based on operator<.
Definition at line 1389 of file forward_list.h.
template<typename _Tp , typename _Alloc > bool std::operator<= (const vector< _Tp, _Alloc > & __x, const vector< _Tp, _Alloc > & __y) inline
Based on operator<.
Definition at line 1547 of file stl_vector.h.
template<typename _Tp , typename _Alloc > bool std::operator<= (const list< _Tp, _Alloc > & __x, const list< _Tp, _Alloc > & __y) inline
Based on operator<.
Definition at line 1855 of file stl_list.h.
template<typename _Tp , typename _Alloc > bool std::operator<= (const deque< _Tp, _Alloc > & __x, const deque< _Tp, _Alloc > & __y) inline
Based on operator<.
Definition at line 2260 of file stl_deque.h.
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator<= (const basic_string< _CharT, _Traits, _Alloc > & __lhs, const basic_string< _CharT, _Traits, _Alloc > & __rhs) inline
Test if string doesn't follow string.
Parameters
__lhs First string.
__rhs Second string.
Returns
True if __lhs doesn't follow __rhs. False otherwise.
Definition at line 5063 of file basic_string.h.
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator<= (const basic_string< _CharT, _Traits, _Alloc > & __lhs, const _CharT * __rhs) inline
Test if string doesn't follow C string.
Parameters
__lhs String.
__rhs C string.
Returns
True if __lhs doesn't follow __rhs. False otherwise.
Definition at line 5075 of file basic_string.h.
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator<= (const _CharT * __lhs, const basic_string< _CharT, _Traits, _Alloc > & __rhs) inline
Test if C string doesn't follow string.
Parameters
__lhs C string.
__rhs String.
Returns
True if __lhs doesn't follow __rhs. False otherwise.
Definition at line 5087 of file basic_string.h.
template<typename _StateT > bool std::operator== (const fpos< _StateT > & __lhs, const fpos< _StateT > & __rhs) inline
Test if equivalent to another position.
Definition at line 216 of file postypes.h.
template<typename _Tp , typename _Seq > bool std::operator== (const stack< _Tp, _Seq > & __x, const stack< _Tp, _Seq > & __y) inline
Stack equality comparison.
Parameters
__x A stack.
__y A stack of the same type as __x.
Returns
True iff the size and elements of the stacks are equal.
This is an equivalence relation. Complexity and semantics depend on the underlying sequence type, but the expected rules are: this relation is linear in the size of the sequences, and stacks are considered equivalent if their sequences compare equal.
Definition at line 246 of file stl_stack.h.
template<typename _Tp > bool std::operator== (const _Fwd_list_iterator< _Tp > & __x, const _Fwd_list_const_iterator< _Tp > & __y) inline noexcept
Forward list iterator equality comparison.
Definition at line 257 of file forward_list.h.
template<typename _Tp , typename _Seq > bool std::operator== (const queue< _Tp, _Seq > & __x, const queue< _Tp, _Seq > & __y) inline
Queue equality comparison.
Parameters
__x A queue.
__y A queue of the same type as __x.
Returns
True iff the size and elements of the queues are equal.
This is an equivalence relation. Complexity and semantics depend on the underlying sequence type, but the expected rules are: this relation is linear in the size of the sequences, and queues are considered equivalent if their sequences compare equal.
Definition at line 271 of file stl_queue.h.
References std::queue< _Tp, _Sequence >::c.
template<typename _Key , typename _Compare , typename _Alloc > bool std::operator== (const multiset< _Key, _Compare, _Alloc > & __x, const multiset< _Key, _Compare, _Alloc > & __y) inline
Multiset equality comparison.
Parameters
__x A multiset.
__y A multiset of the same type as __x.
Returns
True iff the size and elements of the multisets are equal.
This is an equivalence relation. It is linear in the size of the multisets. Multisets are considered equivalent if their sizes are equal, and if corresponding elements compare equal.
Definition at line 825 of file stl_multiset.h.
template<typename _Key , typename _Compare , typename _Alloc > bool std::operator== (const set< _Key, _Compare, _Alloc > & __x, const set< _Key, _Compare, _Alloc > & __y) inline
Set equality comparison.
Parameters
__x A set.
__y A set of the same type as x.
Returns
True iff the size and elements of the sets are equal.
This is an equivalence relation. It is linear in the size of the sets. Sets are considered equivalent if their sizes are equal, and if corresponding elements compare equal.
Definition at line 842 of file stl_set.h.
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool std::operator== (const multimap< _Key, _Tp, _Compare, _Alloc > & __x, const multimap< _Key, _Tp, _Compare, _Alloc > & __y) inline
Multimap equality comparison.
Parameters
__x A multimap.
__y A multimap of the same type as __x.
Returns
True iff the size and elements of the maps are equal.
This is an equivalence relation. It is linear in the size of the multimaps. Multimaps are considered equivalent if their sizes are equal, and if corresponding elements compare equal.
Definition at line 974 of file stl_multimap.h.
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool std::operator== (const map< _Key, _Tp, _Compare, _Alloc > & __x, const map< _Key, _Tp, _Compare, _Alloc > & __y) inline
Map equality comparison.
Parameters
__x A map.
__y A map of the same type as x.
Returns
True iff the size and elements of the maps are equal.
This is an equivalence relation. It is linear in the size of the maps. Maps are considered equivalent if their sizes are equal, and if corresponding elements compare equal.
Definition at line 1073 of file stl_map.h.
template<typename _Tp , typename _Alloc > bool std::operator== (const forward_list< _Tp, _Alloc > & __lx, const forward_list< _Tp, _Alloc > & __ly)
Forward list equality comparison.
Parameters
__lx A forward_list
__ly A forward_list of the same type as __lx.
Returns
True iff the elements of the forward lists are equal.
This is an equivalence relation. It is linear in the number of elements of the forward lists. Deques are considered equivalent if corresponding elements compare equal.
template<typename _Tp , typename _Alloc > bool std::operator== (const vector< _Tp, _Alloc > & __x, const vector< _Tp, _Alloc > & __y) inline
Vector equality comparison.
Parameters
__x A vector.
__y A vector of the same type as __x.
Returns
True iff the size and elements of the vectors are equal.
This is an equivalence relation. It is linear in the size of the vectors. Vectors are considered equivalent if their sizes are equal, and if corresponding elements compare equal.
Definition at line 1511 of file stl_vector.h.
References std::vector< _Tp, _Alloc >::begin(), std::vector< _Tp, _Alloc >::end(), equal(), and std::vector< _Tp, _Alloc >::size().
template<typename _Tp , typename _Alloc > _GLIBCXX_END_NAMESPACE_CXX11 bool std::operator== (const list< _Tp, _Alloc > & __x, const list< _Tp, _Alloc > & __y) inline
List equality comparison.
Parameters
__x A list.
__y A list of the same type as __x.
Returns
True iff the size and elements of the lists are equal.
This is an equivalence relation. It is linear in the size of the lists. Lists are considered equivalent if their sizes are equal, and if corresponding elements compare equal.
Definition at line 1807 of file stl_list.h.
References std::list< _Tp, _Alloc >::begin(), and std::list< _Tp, _Alloc >::end().
template<typename _Tp , typename _Alloc > bool std::operator== (const deque< _Tp, _Alloc > & __x, const deque< _Tp, _Alloc > & __y) inline
Deque equality comparison.
Parameters
__x A deque.
__y A deque of the same type as __x.
Returns
True iff the size and elements of the deques are equal.
This is an equivalence relation. It is linear in the size of the deques. Deques are considered equivalent if their sizes are equal, and if corresponding elements compare equal.
Definition at line 2220 of file stl_deque.h.
References std::deque< _Tp, _Alloc >::begin(), std::deque< _Tp, _Alloc >::end(), equal(), and std::deque< _Tp, _Alloc >::size().
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator== (const basic_string< _CharT, _Traits, _Alloc > & __lhs, const basic_string< _CharT, _Traits, _Alloc > & __rhs) inline
Test equivalence of two strings.
Parameters
__lhs First string.
__rhs Second string.
Returns
True if __lhs.compare(__rhs) == 0. False otherwise.
Definition at line 4906 of file basic_string.h.
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator== (const _CharT * __lhs, const basic_string< _CharT, _Traits, _Alloc > & __rhs) inline
Test equivalence of C string and string.
Parameters
__lhs C string.
__rhs String.
Returns
True if __rhs.compare(__lhs) == 0. False otherwise.
Definition at line 4927 of file basic_string.h.
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator== (const basic_string< _CharT, _Traits, _Alloc > & __lhs, const _CharT * __rhs) inline
Test equivalence of string and C string.
Parameters
__lhs String.
__rhs C string.
Returns
True if __lhs.compare(__rhs) == 0. False otherwise.
Definition at line 4939 of file basic_string.h.
template<typename _Tp , typename _Seq > bool std::operator> (const stack< _Tp, _Seq > & __x, const stack< _Tp, _Seq > & __y) inline
Based on operator<.
Definition at line 276 of file stl_stack.h.
template<typename _Tp , typename _Seq > bool std::operator> (const queue< _Tp, _Seq > & __x, const queue< _Tp, _Seq > & __y) inline
Based on operator<.
Definition at line 301 of file stl_queue.h.
template<typename _Key , typename _Compare , typename _Alloc > bool std::operator> (const multiset< _Key, _Compare, _Alloc > & __x, const multiset< _Key, _Compare, _Alloc > & __y) inline
Returns y < x.
Definition at line 856 of file stl_multiset.h.
template<typename _Key , typename _Compare , typename _Alloc > bool std::operator> (const set< _Key, _Compare, _Alloc > & __x, const set< _Key, _Compare, _Alloc > & __y) inline
Returns y < x.
Definition at line 873 of file stl_set.h.
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool std::operator> (const multimap< _Key, _Tp, _Compare, _Alloc > & __x, const multimap< _Key, _Tp, _Compare, _Alloc > & __y) inline
Based on operator<.
Definition at line 1005 of file stl_multimap.h.
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool std::operator> (const map< _Key, _Tp, _Compare, _Alloc > & __x, const map< _Key, _Tp, _Compare, _Alloc > & __y) inline
Based on operator<.
Definition at line 1104 of file stl_map.h.
template<typename _Tp , typename _Alloc > bool std::operator> (const forward_list< _Tp, _Alloc > & __lx, const forward_list< _Tp, _Alloc > & __ly) inline
Based on operator<.
Definition at line 1375 of file forward_list.h.
template<typename _Tp , typename _Alloc > bool std::operator> (const vector< _Tp, _Alloc > & __x, const vector< _Tp, _Alloc > & __y) inline
Based on operator<.
Definition at line 1541 of file stl_vector.h.
template<typename _Tp , typename _Alloc > bool std::operator> (const list< _Tp, _Alloc > & __x, const list< _Tp, _Alloc > & __y) inline
Based on operator<.
Definition at line 1849 of file stl_list.h.
template<typename _Tp , typename _Alloc > bool std::operator> (const deque< _Tp, _Alloc > & __x, const deque< _Tp, _Alloc > & __y) inline
Based on operator<.
Definition at line 2253 of file stl_deque.h.
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator> (const basic_string< _CharT, _Traits, _Alloc > & __lhs, const basic_string< _CharT, _Traits, _Alloc > & __rhs) inline
Test if string follows string.
Parameters
__lhs First string.
__rhs Second string.
Returns
True if __lhs follows __rhs. False otherwise.
Definition at line 5026 of file basic_string.h.
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator> (const basic_string< _CharT, _Traits, _Alloc > & __lhs, const _CharT * __rhs) inline
Test if string follows C string.
Parameters
__lhs String.
__rhs C string.
Returns
True if __lhs follows __rhs. False otherwise.
Definition at line 5038 of file basic_string.h.
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator> (const _CharT * __lhs, const basic_string< _CharT, _Traits, _Alloc > & __rhs) inline
Test if C string follows string.
Parameters
__lhs C string.
__rhs String.
Returns
True if __lhs follows __rhs. False otherwise.
Definition at line 5050 of file basic_string.h.
template<typename _Tp , typename _Seq > bool std::operator>= (const stack< _Tp, _Seq > & __x, const stack< _Tp, _Seq > & __y) inline
Based on operator<.
Definition at line 288 of file stl_stack.h.
template<typename _Tp , typename _Seq > bool std::operator>= (const queue< _Tp, _Seq > & __x, const queue< _Tp, _Seq > & __y) inline
Based on operator<.
Definition at line 313 of file stl_queue.h.
template<typename _Key , typename _Compare , typename _Alloc > bool std::operator>= (const multiset< _Key, _Compare, _Alloc > & __x, const multiset< _Key, _Compare, _Alloc > & __y) inline
Returns !(x < y)
Definition at line 870 of file stl_multiset.h.
template<typename _Key , typename _Compare , typename _Alloc > bool std::operator>= (const set< _Key, _Compare, _Alloc > & __x, const set< _Key, _Compare, _Alloc > & __y) inline
Returns !(x < y)
Definition at line 887 of file stl_set.h.
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool std::operator>= (const multimap< _Key, _Tp, _Compare, _Alloc > & __x, const multimap< _Key, _Tp, _Compare, _Alloc > & __y) inline
Based on operator<.
Definition at line 1019 of file stl_multimap.h.
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool std::operator>= (const map< _Key, _Tp, _Compare, _Alloc > & __x, const map< _Key, _Tp, _Compare, _Alloc > & __y) inline
Based on operator<.
Definition at line 1118 of file stl_map.h.
template<typename _Tp , typename _Alloc > bool std::operator>= (const forward_list< _Tp, _Alloc > & __lx, const forward_list< _Tp, _Alloc > & __ly) inline
Based on operator<.
Definition at line 1382 of file forward_list.h.
template<typename _Tp , typename _Alloc > bool std::operator>= (const vector< _Tp, _Alloc > & __x, const vector< _Tp, _Alloc > & __y) inline
Based on operator<.
Definition at line 1553 of file stl_vector.h.
template<typename _Tp , typename _Alloc > bool std::operator>= (const list< _Tp, _Alloc > & __x, const list< _Tp, _Alloc > & __y) inline
Based on operator<.
Definition at line 1861 of file stl_list.h.
template<typename _Tp , typename _Alloc > bool std::operator>= (const deque< _Tp, _Alloc > & __x, const deque< _Tp, _Alloc > & __y) inline
Based on operator<.
Definition at line 2267 of file stl_deque.h.
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator>= (const basic_string< _CharT, _Traits, _Alloc > & __lhs, const basic_string< _CharT, _Traits, _Alloc > & __rhs) inline
Test if string doesn't precede string.
Parameters
__lhs First string.
__rhs Second string.
Returns
True if __lhs doesn't precede __rhs. False otherwise.
Definition at line 5100 of file basic_string.h.
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator>= (const basic_string< _CharT, _Traits, _Alloc > & __lhs, const _CharT * __rhs) inline
Test if string doesn't precede C string.
Parameters
__lhs String.
__rhs C string.
Returns
True if __lhs doesn't precede __rhs. False otherwise.
Definition at line 5112 of file basic_string.h.
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator>= (const _CharT * __lhs, const basic_string< _CharT, _Traits, _Alloc > & __rhs) inline
Test if C string doesn't precede string.
Parameters
__lhs C string.
__rhs String.
Returns
True if __lhs doesn't precede __rhs. False otherwise.
Definition at line 5124 of file basic_string.h.
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> basic_istream<_CharT, _Traits>& std::operator>> (basic_istream< _CharT, _Traits > & __is, __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base > & __str)
Read stream into a string.
Parameters
__is Input stream.
__str Buffer to store into.
Returns
Reference to the input stream.
Stores characters from __is into __str until whitespace is found, the end of the stream is encountered, or str.max_size() is reached. If is.width() is non-zero, that is the limit on the number of characters stored into __str. Any previous contents of __str are erased.
template<typename _CharT , typename _Traits , typename _Alloc > basic_istream<_CharT, _Traits>& std::operator>> (basic_istream< _CharT, _Traits > & __is, basic_string< _CharT, _Traits, _Alloc > & __str)
Read stream into a string.
Parameters
__is Input stream.
__str Buffer to store into.
Returns
Reference to the input stream.
Stores characters from __is into __str until whitespace is found, the end of the stream is encountered, or str.max_size() is reached. If is.width() is non-zero, that is the limit on the number of characters stored into __str. Any previous contents of __str are erased.
template<typename _InputIterator , typename _OutputIterator > _OutputIterator std::partial_sum (_InputIterator __first, _InputIterator __last, _OutputIterator __result)
Return list of partial sums.
Accumulates the values in the range [first,last) using the + operator. As each successive input value is added into the total, that partial sum is written to __result. Therefore, the first value in __result is the first value of the input, the second value in __result is the sum of the first and second input values, and so on.
Parameters
__first Start of input range.
__last End of input range.
__result Output sum.
Returns
Iterator pointing just beyond the values written to __result.
Definition at line 237 of file stl_numeric.h.
Referenced by __gnu_parallel::__parallel_random_shuffle_drs_pu(), and __gnu_parallel::__sequential_random_shuffle().
template<typename _InputIterator , typename _OutputIterator , typename _BinaryOperation > _OutputIterator std::partial_sum (_InputIterator __first, _InputIterator __last, _OutputIterator __result, _BinaryOperation __binary_op)
Return list of partial sums.
Accumulates the values in the range [first,last) using __binary_op. As each successive input value is added into the total, that partial sum is written to __result. Therefore, the first value in __result is the first value of the input, the second value in __result is the sum of the first and second input values, and so on.
Parameters
__first Start of input range.
__last End of input range.
__result Output sum.
__binary_op Function object.
Returns
Iterator pointing just beyond the values written to __result.
Definition at line 278 of file stl_numeric.h.
template<typename _InputIterator , typename _OutputIterator , typename _Tp > _OutputIterator std::replace_copy (_InputIterator __first, _InputIterator __last, _OutputIterator __result, const _Tp & __old_value, const _Tp & __new_value) inline
Copy a sequence, replacing each element of one value with another value.
Parameters
__first An input iterator.
__last An input iterator.
__result An output iterator.
__old_value The value to be replaced.
__new_value The replacement value.
Returns
The end of the output sequence, result+(last-first).
Copies each element in the input range [__first,__last) to the output range [__result,__result+(__last-__first)) replacing elements equal to __old_value with __new_value.
Definition at line 3135 of file stl_algo.h.
template<typename _Tp > void std::return_temporary_buffer (_Tp * __p) inline
The companion to get_temporary_buffer().
Parameters
__p A buffer previously allocated by get_temporary_buffer.
Returns
None.
Frees the memory pointed to by __p.
Definition at line 112 of file stl_tempbuf.h.
Referenced by std::_Temporary_buffer< _ForwardIterator, _Tp >::_Temporary_buffer().
ios_base& std::right (ios_base & __base) inline
Calls base.setf(ios_base::right, ios_base::adjustfield).
Definition at line 1007 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::adjustfield, std::ios_base::right, and std::ios_base::setf().
ios_base& std::scientific (ios_base & __base) inline
Calls base.setf(ios_base::scientific, ios_base::floatfield).
Definition at line 1049 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::floatfield, std::ios_base::scientific, and std::ios_base::setf().
ios_base& std::showbase (ios_base & __base) inline
Calls base.setf(ios_base::showbase).
Definition at line 894 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::setf(), and std::ios_base::showbase.
ios_base& std::showpoint (ios_base & __base) inline
Calls base.setf(ios_base::showpoint).
Definition at line 910 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::setf(), and std::ios_base::showpoint.
ios_base& std::showpos (ios_base & __base) inline
Calls base.setf(ios_base::showpos).
Definition at line 926 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::setf(), and std::ios_base::showpos.
ios_base& std::skipws (ios_base & __base) inline
Calls base.setf(ios_base::skipws).
Definition at line 942 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::setf(), and std::ios_base::skipws.
Referenced by std::__detail::operator>>().
template<typename _Tp , typename _Tp1 , _Lock_policy _Lp> __shared_ptr<_Tp, _Lp> std::static_pointer_cast (const __shared_ptr< _Tp1, _Lp > & __r) inline noexcept
static_pointer_cast
Definition at line 1311 of file shared_ptr_base.h.
template<typename _Key , typename _Compare , typename _Alloc > void std::swap (multiset< _Key, _Compare, _Alloc > & __x, multiset< _Key, _Compare, _Alloc > & __y) inline
See std::multiset::swap().
Definition at line 877 of file stl_multiset.h.
References std::multiset< _Key, _Compare, _Alloc >::swap().
template<typename _Key , typename _Compare , typename _Alloc > void std::swap (set< _Key, _Compare, _Alloc > & __x, set< _Key, _Compare, _Alloc > & __y) inline
See std::set::swap().
Definition at line 894 of file stl_set.h.
References std::set< _Key, _Compare, _Alloc >::swap().
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > void std::swap (multimap< _Key, _Tp, _Compare, _Alloc > & __x, multimap< _Key, _Tp, _Compare, _Alloc > & __y) inline
See std::multimap::swap().
Definition at line 1026 of file stl_multimap.h.
References std::multimap< _Key, _Tp, _Compare, _Alloc >::swap().
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > void std::swap (map< _Key, _Tp, _Compare, _Alloc > & __x, map< _Key, _Tp, _Compare, _Alloc > & __y) inline
See std::map::swap().
Definition at line 1125 of file stl_map.h.
References std::map< _Key, _Tp, _Compare, _Alloc >::swap().
template<typename _Tp , typename _Alloc > void std::swap (forward_list< _Tp, _Alloc > & __lx, forward_list< _Tp, _Alloc > & __ly) inline
See std::forward_list::swap().
Definition at line 1396 of file forward_list.h.
References std::forward_list< _Tp, _Alloc >::swap().
template<typename _Tp , typename _Alloc > void std::swap (vector< _Tp, _Alloc > & __x, vector< _Tp, _Alloc > & __y) inline
See std::vector::swap().
Definition at line 1559 of file stl_vector.h.
References std::vector< _Tp, _Alloc >::swap().
template<typename _Tp , typename _Alloc > void std::swap (list< _Tp, _Alloc > & __x, list< _Tp, _Alloc > & __y) inline
See std::list::swap().
Definition at line 1867 of file stl_list.h.
References std::list< _Tp, _Alloc >::swap().
template<typename _Tp , typename _Alloc > void std::swap (deque< _Tp, _Alloc > & __x, deque< _Tp, _Alloc > & __y) inline
See std::deque::swap().
Definition at line 2274 of file stl_deque.h.
References std::deque< _Tp, _Alloc >::swap().
template<typename _CharT , typename _Traits , typename _Alloc > void std::swap (basic_string< _CharT, _Traits, _Alloc > & __lhs, basic_string< _CharT, _Traits, _Alloc > & __rhs) inline
Swap contents of two strings.
Parameters
__lhs First string.
__rhs Second string.
Exchanges the contents of __lhs and __rhs in constant time.
Definition at line 5137 of file basic_string.h.
template<typename _CharT > _CharT std::tolower (_CharT __c, const locale & __loc) inline
Convenience interface to ctype.tolower(__c).
Definition at line 2645 of file locale_facets.h.
template<typename _CharT > _CharT std::toupper (_CharT __c, const locale & __loc) inline
Convenience interface to ctype.toupper(__c).
Definition at line 2639 of file locale_facets.h.
template<typename _InputIterator , typename _ForwardIterator > _ForwardIterator std::uninitialized_copy (_InputIterator __first, _InputIterator __last, _ForwardIterator __result) inline
Copies the range [first,last) into result.
Parameters
__first An input iterator.
__last An input iterator.
__result An output iterator.
Returns
__result + (__first - __last)
Like copy(), but does not require an initialized output range.
Definition at line 107 of file stl_uninitialized.h.
Referenced by __gnu_parallel::parallel_sort_mwms_pu().
template<typename _InputIterator , typename _Size , typename _ForwardIterator > _ForwardIterator std::uninitialized_copy_n (_InputIterator __first, _Size __n, _ForwardIterator __result) inline
Copies the range [first,first+n) into result.
Parameters
__first An input iterator.
__n The number of elements to copy.
__result An output iterator.
Returns
__result + __n
Like copy_n(), but does not require an initialized output range.
Definition at line 679 of file stl_uninitialized.h.
References __iterator_category().
template<typename _ForwardIterator , typename _Tp > void std::uninitialized_fill (_ForwardIterator __first, _ForwardIterator __last, const _Tp & __x) inline
Copies the value x into the range [first,last).
Parameters
__first An input iterator.
__last An input iterator.
__x The source value.
Returns
Nothing.
Like fill(), but does not require an initialized output range.
Definition at line 173 of file stl_uninitialized.h.
template<typename _ForwardIterator , typename _Size , typename _Tp > _ForwardIterator std::uninitialized_fill_n (_ForwardIterator __first, _Size __n, const _Tp & __x) inline
Copies the value x into the range [first,first+n).
Parameters
__first An input iterator.
__n The number of copies to make.
__x The source value.
Returns
Nothing.
Like fill_n(), but does not require an initialized output range.
Definition at line 236 of file stl_uninitialized.h.
ios_base& std::unitbuf (ios_base & __base) inline
Calls base.setf(ios_base::unitbuf).
Definition at line 974 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::setf(), and std::ios_base::unitbuf.
ios_base& std::uppercase (ios_base & __base) inline
Calls base.setf(ios_base::uppercase).
Definition at line 958 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::setf(), and std::ios_base::uppercase.